### PR TITLE
Move prefetch handling to `Router` init - fixes #683

### LINKED ISSUE #683: Hovering on a link with `sveltekit:prefetch` before JS loads throws an error on console
**Describe the bug**
This might be related to the fix for #652 (in #654) which is working now. If the user has a slow connection and hovers on a link with the attribute `sveltekit:prefetch` before JS finishes loading, SvelteKit will throw multiple times the same error `TypeError: can't access property "parse", this.router is null` until it finishes loading. This does not seem to break anything else and the page keeps working.

**Logs**

```
Uncaught (in promise) TypeError: can't access property "parse", this.router is null
    prefetch http://localhost:3000/.svelte/dev/runtime/internal/start.js:482
    trigger_prefetch http://localhost:3000/.svelte/dev/runtime/internal/start.js:341
    mousemove_timeout http://localhost:3000/.svelte/dev/runtime/internal/start.js:352
    setTimeout handler*handle_mousemove http://localhost:3000/.svelte/dev/runtime/internal/start.js:351
    Renderer http://localhost:3000/.svelte/dev/runtime/internal/start.js:357
    start http://localhost:3000/.svelte/dev/runtime/internal/start.js:804
    <anonymous> http://localhost:3000/:138
```

**To Reproduce**
Set throttling in your browser to "Regular 2G" or something slow enough. Load the page and before the JS finishes loading, hover a link with `sveltekit:prefetch`. This should throw the above error in the console.

**Expected behavior**
No errors in console

**Stacktraces**
No stack trace

**Information about your SvelteKit Installation:**

```
 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 98.43 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 7.5.4 - ~/.volta/tools/image/npm/7.5.4/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox Developer Edition: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: 1.0.0-next.58 => 1.0.0-next.58
    svelte: ^3.0.0 => 3.35.0
 ```

- Tested in Firefox Developer Edition 87.0

- Adapter: static

**Severity**
Just annoying, doesn't seem to be breaking anything else at all (that I have noticed).

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pablo-abc**
Fix #683

I was not sure how to test for this since it would depend on network speed, so no tests were added.

### Before submitting the PR, please make sure you do the following
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [X] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [X] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks for the PR. Rather than bailing out if `this.router` is undefined, I think what we probably want to do is just not add those event listeners until the initial render has completed — i.e. move this code onwards... https://github.com/sveltejs/kit/blob/1e8be5aae053375db22bc5a8aeeb002f098ab31b/packages/kit/src/runtime/client/renderer.js#L82-L114 ...from the constructor to the end of `start`. Partly because it just doesn't really make sense for the renderer to listen for events it doesn't yet know how to handle, but partly because there's a slightly awkward edge case that currently fails noisily that would fail silently in this PR: if someone programmatically prefetches...

```js
import { prefetch } from '$app/navigation';

// assuming this runs immediately once the initial page is hydrated,
// this will currently error
prefetch('/blah');
```

...it should _either_ error (as currently) or (preferably) work correctly. So we'll need to change the implementation of the standalone `prefetch` function so that it waits until the router has initialised (which I _think_ is probably just a case of wrapping the whole thing in a `Promise.resolve()`, since the router inits as soon as hydration has occurred), though that could happen in a separate PR I think

**Comment by pablo-abc** [comment]
Thanks for the feedback! That makes sense. So from what I understand, it would make more sense for these event listeners to be added after both `renderer.start` and `router.init` are called. Since after #654 the router won't be available even inside `renderer.start`.

From what I see, the only code that depends on it being run inside of `Renderer` from the snippet you shared above would be the `prefetch` call in line 84. Would it make sense to move lines 82-102...

https://github.com/sveltejs/kit/blob/1e8be5aae053375db22bc5a8aeeb002f098ab31b/packages/kit/src/runtime/client/renderer.js#L82-L102

... to be run inside `router.init` (since `renderer` is available there anyway) and leave lines 104-114...

https://github.com/sveltejs/kit/blob/1e8be5aae053375db22bc5a8aeeb002f098ab31b/packages/kit/src/runtime/client/renderer.js#L104-L114

... inside `Renderer`'s constructor with a check for `!this.router` alongside `!ready`?

I'll update my PR to show what I mean.

**Comment by pablo-abc** [comment]
Oops. Seems one of the tests failed due to a timeout. Is it a matter of re-running the jobs or something failed on my end?

Regarding your last point:

> So we'll need to change the implementation of the standalone prefetch function so that it waits until the router has initialised

Would something like this be too hacky?

```javascript
// renderer.js

/** @type {Promise<import('./router').Router>} */
this._router = new Promise((resolve) => {
	this.set_router = resolve;
});
```

```javascript
// router.js

renderer.set_router(this);
```

Then, wherever the `router` is needed you'd do an `await this._router`.

From what I see, every function that needs `this.router` is already `async` so the signature would not change at all.

**Comment by Rich-Harris** [comment]
Sorry, lost track of this PR. I ended up making some broader changes in #766 that make the guards unnecessary, so I'll close this

**Pull request closed without merging**
