### PR TITLE
Allow fetching ArrayBufferView request body types

### LINKED ISSUE #5680: support fetching with non-string bodies
### Describe the bug

Calling fetch function from async export load({fetch} with Uint8Array body results in exception: Request body must be a string.
A little bit of investigating the problem gave me this:

```javascript
if (opts.body && typeof opts.body !== 'string') {
    // per https://developer.mozilla.org/en-US/docs/Web/API/Request/Request, this can be a
    // Blob, BufferSource, FormData, URLSearchParams, USVString, or ReadableStream object.
    // non-string bodies are irksome to deal with, but luckily aren't particularly useful
    // in this context anyway, so we take the easy route and ban them
    throw new Error('Request body must be a string');
}
```

### Reproduction

1. Create a route with load function.
```javascript
export async function load({fetch}) {
    fetch('api/endpoint', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/octet-stream'
        },
        body: new Uint8Array([1,2,3,4]);
    });
    return {};
}
```
2. Run it.

### Logs

```shell
500
Request body must be a string
Error: Request body must be a string
    at fetch (file:///Users/*******/projects/web/*******/.svelte-kit/runtime/server/index.js:2241:13)
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    npm: 8.7.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Chrome Canary: 105.0.5195.2
    Firefox: 100.0.2
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.52 => 1.0.0-next.52 
    @sveltejs/adapter-node: ^1.0.0-next.78 => 1.0.0-next.78 
    @sveltejs/kit: ^1.0.0-next.355 => 1.0.0-next.355 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

serious, but I can work around it

### Additional Information

The simplest solution is of course "use JSON or base64" and yet it's not a solution at all because I'm using high-performance PackMe binary protocol (I mean, really high performance, like hundreds of thousands pack/unpack operations per second, you can't do that with JSON or base64). Would be nice to keep it that way (obviously, not possible for now).

And it all worked perfectly until I realized that I need to make a few api calls inside load function :( It turned out that fetch from load function is not the same as browser fetch. Can we do something about it? It looks like implementing Blob, BufferSource and ReadableStream support isn't something too complicated.

### LINKED ISSUE #5710: Formdata send by Sveltekit Endpoint is send by plain/text with no data
### Describe the bug

SvelteKit:

If you try to send a POST Request from **Server-to-Server** with **FormData** the request will fail.
Sveltekits `fetch()` does not set content-type multipart/form-data. The Request will be text/plain and no Formdata will be submitted

This probably relates to
#5349
#5292

**I tried my best and created an Express Server and a Sveltekit App (see below) for debugging.**

```ts
export const POST: RequestHandler = async ({ request }) => {
//	const formDataSendbyFrontend = await request.formData();
	const demoData = new FormData();
	demoData.append('data', "lorem ipsum");
	const res = await fetch('https://sveltekit-express-bug-tester.herokuapp.com/formdata', {
		method: 'POST',
		body: demoData
	})
```

The Request will fail, because Sveltekit sends text/plain and no FormData (???)

```js
// Req Object Express Server
{
  body: {
    headers: {
      host: 'sveltekit-express-bug-tester.herokuapp.com',
      connection: 'close',
      accept: '*/*',
      'content-type': 'text/plain;charset=UTF-8',
      'accept-language': '*',
      'sec-fetch-mode': 'cors',
      'user-agent': 'undici',
      'accept-encoding': 'br, gzip, deflate',
      'x-request-id': '4f31b926-31c7-4cd2-a612-0bf85edb01fe',
      'x-forwarded-for': '1.1.1.1',
      'x-forwarded-proto': 'https',
      'x-forwarded-port': '443',
      via: '1.1 vegur',
      'connect-time': '0',
      'x-request-start': '1658828491278',
      'total-route-time': '0',
      'content-length': '17'
    },
    error: 'Not multipart/form-data'
  }
}
```

This used to Work with node-fetch and Sveltekit v.350  (not sure which version it got broken)

### Reproduction

I prepared to Repos with a Server (Express + Multer) and a minimal Sveltekit App

💻 Server Repo: https://github.com/garytube/sveltekit-formdata-bug-server
🌍 Sveltekit Repo:  https://github.com/garytube/sveltekit-formdata-bug-sveltekit

Send a `POST` Request with FormData from a SvelteKit Endpoint to `http://sveltekit-express-bug-tester.herokuapp.com/formdata` 

```js
	const demoData = new FormData();
	demoData.append('data', "lorem ipsum");
	const res = await fetch('http://sveltekit-express-bug-tester.herokuapp.com/formdata', {
		method: 'POST',
		body: demoData
	})
```

`/formdata` can also recive a File (Fieldname: image)  (can be anything txt, jpg, pdf up to 1mb)
Maybe this helps debugging

```js
<input bind:files  type="file" accept="image/*" />

formData.append('image', files[0]')
```

The Sveltekit Demo Project will

1. Send Form Data to Sveltekit Endpoint
2. Sveltekit Endpoint will forward Request TO OFF-SITE Server 
3. Request will fail because req.content-type of Sveltekit to OFF-SITE server is text/plain and formdata is missing

### Logs

```shell
REQUEST LOG EXPRESS SERVER

2022-07-26T10:52:17.994877+00:00 app[web.1]: 415 {
2022-07-26T10:52:17.994884+00:00 app[web.1]:   headers: {
2022-07-26T10:52:17.994885+00:00 app[web.1]:     host: 'sveltekit-express-bug-tester.herokuapp.com',
2022-07-26T10:52:17.994886+00:00 app[web.1]:     connection: 'close',
2022-07-26T10:52:17.994887+00:00 app[web.1]:     'content-type': 'text/plain;charset=UTF-8',
2022-07-26T10:52:17.994887+00:00 app[web.1]:     accept: '*/*',
2022-07-26T10:52:17.994888+00:00 app[web.1]:     'accept-language': '*',
2022-07-26T10:52:17.994888+00:00 app[web.1]:     'sec-fetch-mode': 'cors',
2022-07-26T10:52:17.994888+00:00 app[web.1]:     'user-agent': 'undici',
2022-07-26T10:52:17.994889+00:00 app[web.1]:     'accept-encoding': 'br, gzip, deflate',
2022-07-26T10:52:17.994889+00:00 app[web.1]:     'x-request-id': '47463367-0ee3-4c57-b58a-cbdbf0d7cf68',
2022-07-26T10:52:17.994889+00:00 app[web.1]:     'x-forwarded-for': '-------------',
2022-07-26T10:52:17.994890+00:00 app[web.1]:     'x-forwarded-proto': 'https',
2022-07-26T10:52:17.994890+00:00 app[web.1]:     'x-forwarded-port': '443',
2022-07-26T10:52:17.994890+00:00 app[web.1]:     via: '1.1 vegur',
2022-07-26T10:52:17.994890+00:00 app[web.1]:     'connect-time': '0',
2022-07-26T10:52:17.994891+00:00 app[web.1]:     'x-request-start': '1658832737992',
2022-07-26T10:52:17.994891+00:00 app[web.1]:     'total-route-time': '0',
2022-07-26T10:52:17.994891+00:00 app[web.1]:     'content-length': '17'
2022-07-26T10:52:17.994892+00:00 app[web.1]:   },
2022-07-26T10:52:17.994892+00:00 app[web.1]:   file: undefined,
2022-07-26T10:52:17.994892+00:00 app[web.1]:   body: undefined
2022-07-26T10:52:17.994892+00:00 app[web.1]: }
```

### System Info

```shell
System:
    OS: Windows 11
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.79 GB / 15.70 GB
  Binaries:
    Node: 18.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.63
    @sveltejs/kit: next => 1.0.0-next.394
    svelte: ^3.46.0 => 3.49.0
    vite: ^3.0.0 => 3.0.3
```

### Severity

blocking an upgrade

### Additional Information

**Background:**
My Realworld App is public Facing but only the Sveltekit Server is allowed to talk to the "Secure" API.
So instead of directly calling the "Secure" API from the Form, I send everything through the Sveltekit Server. This is why I need to send FromData **Server-to-Server.**

Used to work until undici came along ;)

### PR DESCRIPTION
**Pull request by repsac-by**
- Fixes #5680 
- Fixes #5710 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Conduitry** [comment]
These tests look helpful, but we'll hopefully be able to drop this node-fetch hack soon, once the next version of undici with formdata support is released.

**Comment by Rich-Harris** [comment]
Thank you for the PR. I'm a little uneasy about this change though — it adds bytes to every SvelteKit app for a feature I'm not entirely convinced warrants it. What's the use case for posting non-string data inside a `load` function (which shouldn't have side-effects, and therefore shouldn't really be using POST almost by definition)?

At the very least, we certainly shouldn't be doing `await request.clone().arrayBuffer()`. If someone is passing a `Blob` or `File` to `fetch` in `load` then our attitude should be one of detached amusement. [Everything else](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#body) can be dealt with synchronously.

**Comment by repsac-by** [comment]
Thanks for the comment.

I haven't encountered the need to send POST in `load()` function.
But I thought it was a good idea to bring it up to standards and initially overestimated the usefulness. 

I agree that it seems enough, string and [BufferSource](https://webidl.spec.whatwg.org/#BufferSource).
Only what requires synchronous processing.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Thanks for making this changes — this looks good to me. This PR is still marked as draft, is that intentional or is this good to go?

**Comment by repsac-by** [comment]
Thank you. It's already done.

**Pull request merged**
