### PR TITLE
update welcome message

### PR DESCRIPTION
**Pull request by Rich-Harris**
Not sure how the typo ('some feature might not work yet') escaped our notice this long, but I figured I'd take the opportunity to tighten up the welcome message a bit generally

### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Fixed a couple of other rough onboarding edges

**Comment by Conduitry** [comment]
I know we've changed our mind at least a time or two about whether to include an adapter by default. What's behind this latest decision?

**Comment by Rich-Harris** [comment]
a) I just think it's a bit weird to make the Node adapter the default, b) running into that message when you first build makes it much clearer that you're _supposed_ to select an adapter, and makes it more likely that someone will figure out how (and be aware of the various options). In the past I think we had to include one because it failed if you didn't

**Comment by Rich-Harris** [comment]
i am perturbed by these windows failures.

**Pull request merged**
