### PR TITLE
fix: iOS `scroll-behavior: smooth` breaks navigation scrolling

### LINKED ISSUE #2733: Page scroll position not reset to top on navigation (regression)
### Describe the bug

When navigating to a new page, if you are already scrolled partway down the page, the next page load will keep the current scroll position and not scroll back to the top.

I believe this broke with next-193. When I install next-192, this does not happen -- navigating to a new page always scrolls to the top, just like regular browser navigation.

### Reproduction

Init the SvelteKit demo project. Add the following paragraph in `about.svelte` after the last paragraph.

```html
<p>Go <a href="/">home</a></p>
```

Make the browser window small enough so that the page scrolls and scroll to the bottom of the page. Click the Home link. The Home page loads, but does not scroll to the top (i.e. the nav bar is not visible).

scroll-bug.

Tested in Chrome and Firefox on Windows 10.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 7.79 GB / 12.40 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.193 => 1.0.0-next.193
    svelte: ^3.34.0 => 3.44.1
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by s3812497**
fixes #2733 (partially)

The issue is mentioned here https://github.com/sveltejs/kit/issues/2733#issuecomment-1403705100

Sets the `scroll-behavior` to `auto` when scrolling from navigation, then resets it.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Could this be considered a breaking change, if people are currently using smooth scrolling? It feels like it might be.

**Comment by s3812497** [comment]
> Could this be considered a breaking change, if people are currently using smooth scrolling? It feels like it might be.

Yes, it's a breaking change for users that intentionally wanted smooth scrolling when navigating between different pages.

At the same time, it's a fix for users that wanted smooth scrolling but didn't want the effect to happen when navigating across different pages (the browser's default behaviour).

The current behaviour can be [seen here](https://stackblitz.com/edit/sveltejs-kit-template-default-ywm5on?file=src%2Froutes%2Fstyles.css,src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2FHeader.svelte,src%2Froutes%2F%2Bpage.svelte&terminal=dev). Scrolling down and navigating to a new page causes a long scroll upwards instead of an instant scroll to the top.

This fix has no effect on hash navigation, since it uses [`.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) that doesn't have the same issues as `scrollTo()`

**Comment by Rich-Harris** [comment]
I feel like if someone has set `scroll-behaviour: smooth` then it was probably intentional, so I'm not sure we can make this change. We should probably just document this approach instead:

```js
/** @type {string}*/
let scroll_behaviour;

beforeNavigate(() => {
  scroll_behaviour = getComputedStyle(document.documentElement).scrollBehavior;
  document.documentElement.style.scrollBehavior = 'auto';
});

afterNavigate(() => {
  if (scroll_behaviour) {
    document.documentElement.style.scrollBehavior = scroll_behaviour;
  }
});
```

Is there an iOS bug distinct from the smooth scrolling behaviour?

**Comment by jasongitmail** [comment]
FWIW, this bug currently exists in Chrome, Safari, and Firefox. I also [encountered it and wrote repro steps](https://github.com/sveltejs/kit/issues/2733#issuecomment-1590212088). 

Rich's [workaround](https://github.com/sveltejs/kit/pull/8724#issuecomment-1424436745) above works. But it'd seem better to solve it in the framework for everybody if possible.


> Yes, it's a breaking change for users that intentionally wanted smooth scrolling when navigating between different pages.

I'd consider it a bug fix of unexpected behavior, not a breaking feature change, b/c I don't think anybody would intentionally want this behavior: For example, if scrolled to the bottom of page A, it will navigate to page B _at the bottom of it_, and then immediately smooth scroll to the top of page B. The expected behavior would be for smooth scrolling to occur only on the same page, not after navigation.

**Comment by whataboutpereira** [comment]
> FWIW, this bug currently exists in Chrome, Safari, and Firefox. I also [encountered it and wrote repro steps](https://github.com/sveltejs/kit/issues/2733#issuecomment-1590212088).
> 
> Rich's [workaround](https://github.com/sveltejs/kit/pull/8724#issuecomment-1424436745) above works. But it'd seem better to solve it in the framework for everybody if possible.
> 
> > Yes, it's a breaking change for users that intentionally wanted smooth scrolling when navigating between different pages.

Rich's workaround helped me as well.

I'm using data-sveltekit-noscroll on the body, but still some pages fail to scroll properly in afterNavigate() - scroll to top is initiated before afterNavigate() even though noscroll has been specified and the scrollIntoView() I have in afterNavigate() will fail/stop halfway through.

Unfortunately I haven't been able to narrow it down why it happens on certain plain pages.

**Comment by XXFOGS** [comment]
The issue still persists even on the latest SvelteKit version, is there an official solution to this problem? Workarounds don't seem to help me on FireFox and even if they did it wouldn't be the most reliable way how to solve an unexpected behavior.

**Pull request closed without merging**
