### PR TITLE
[feat] add prerender.subfolders setting

### LINKED ISSUE #1443: Ability to prerender to `about.html` instead of `about/index.html` like Sapper
**Describe the bug**
When setting `tralilingSlash: 'ignore'` then the static adapter generates wrong files, e.g.

- `blog/hello-world.html.svelte` is generated as `blog/hello-world.html/index.html`
- `about.svelte` is generated as `about/index.html`

**To Reproduce**
Here is a repo with issue reproduction, generated files are also pushed to the main branch in `dist` directory: https://github.com/bdadam/svelte-kit-static-issue

The repo was freshly created with `npm init svelte@next .`.

**Expected behavior**

- `blog/hello-world.html.svelte` => `blog/hello-world.html.html`
- `about.svelte` is generated as `about.html`

**Information about your SvelteKit Installation:**

- The repo was freshly created with `npm init svelte@next .`
- `yarn add -D @sveltejs/adapter-node@next` to install the static adapter

**Severity**
For me this is a blocker in adopting Svelte Kit for one side project. I have a website which has 6+ years old URLs with .html extensions, e.g. `https://example.com/blog/hello-world.html`. I don't want to touch these URLs due to all the SEO rank and backlinks they received throughout the years. In all honesty this is a toy project - but I guess I'm not alone with this requirement.

### PR DESCRIPTION
**Pull request by bfanger**
Fixes #1443

Usage in svelte.config:

```js
kit: {
  prerender: {
    subfolders: false,
  },
   ...
```
Setting the `kit.prerender.subfolders` setting to **false** (default is **true**) will change the filename generation  from "/about/index.html"  to "/about.html"

Inspiration for the `subfolders` name came from nuxt:
https://nuxtjs.org/docs/configuration-glossary/configuration-generate/#subfolders

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thank you, and apologies for not getting round to this PR until now. One thing I'm not 100% sure about is the `subfolders` name — something about it feels a little non-descriptive. What about something like `createIndexFiles`?

**Comment by bfanger** [comment]
Apology is appreciated.
I agree that the naming could be better, but don't think `createIndexFiles ` is it, that name makes sense from the kit codebase standpoint, but from a user perspective it's about is not generating folders, the index files are a byproduct..

if we change the config from a boolean to an enum, that show the intent better:

`routeOutput: 'file' | 'folder'`

What do you think?

**Comment by Rich-Harris** [comment]
I think a boolean makes more sense to be honest. We discussed in the maintainers chatroom and decided to go with `createIndexFiles` — it's the sort of thing that's easy to find in the docs when you start looking for information about `index.html`

**Review by Rich-Harris — APPROVED** [review]

**Comment by isapir** [comment]
Is `kit.prerender.subfolders: false` still a thing?  

I get an error:
> Error: Unexpected option config.kit.prerender.subfolders

I have this in `svelte.config.js`: 

```
/**
 * from https://kit.svelte.dev/docs/adapter-static
 */
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown. On some platforms
			// these options are set automatically — see below
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false,
			strict: true
		}),
		prerender: {
			subfolders: false,
		},
	}
};
```

**Comment by bfanger** [comment]
```ts
// src/routes/+layout.js
export const trailingSlash = 'always';
```


https://kit.svelte.dev/docs/page-options#trailingslash

**Pull request merged**
