### PR TITLE
reorganise codebase a bit

### PR DESCRIPTION
**Pull request by Rich-Harris**
This started out with me working on #4051 and immediately wanting to move `packages/kit/src/hooks.js` to `packages/kit/src/hooks/sequence.js` so that we could have a `sequence.spec.js` alongside it, but not wanting to do that because it would make `src` even more raggedy than it currently is.

As of this PR, the contents of `src` look like this...

```bash
src/
├ core/     # the dev/build logic
├ exports/  # stuff exposed as the `@sveltejs/kit` package
├ runtime/  # code that runs when people use a SvelteKit app
├ utils/    # self-explanatory
└ cli.js    # self-explanatory
```

...which I think makes more sense than `src/vite`, `src/node` etc. There's definitely more that could be done here (the `runtime` directory in particular has become a bit chaotic), but sorting out the top level feels like a good start, and would make me feel calmer when I'm working in the codebase.

No changeset because this change should be invisible to users. I used `git mv` to preserve history and minimise the chance of merge conflicts.

### CODE REVIEW

**Comment by benmccann** [comment]
This seems pretty good overall.

The contributing guide would need to be updated. 

It feels a little weird to me that `core` doesn't contain the most important code paths. Should it be called `build` or something?

(the directory tree in the description gave me a chuckle. I think someone's been typing `src/routes` a few too many times :smile:)

**Review by dummdidumm — APPROVED** [review]
Test failures seem unrelated/due to flakyness. Will do one rerun to be sure.

**Comment by Rich-Harris** [comment]
The `$env` thing is a red herring. We should probably make it less noisy. It's actually #6306

**Comment by Rich-Harris** [comment]
The distinction between `core` and `runtime` is roughly this: `runtime` is the stuff that runs through Vite during `dev` and is included in the app once it's built, `core` is the stuff that runs in Node and only during dev/build time. It definitely wouldn't make sense for `sync` to be in `runtime`, for example.

**Pull request merged**
