### PR TITLE
Update .gitignore files in create-svelte package to ignore all dotfiles with a prefix of .env

### LINKED ISSUE #2904: Ignore all dotfiles with a .env prefix by default for new projects
### Describe the problem

When a developer runs `npm init svelte@next` to create a new app and selects either the demo or skeleton project, the codebase generated for them contains a `.gitignore` file that will ignore a file that is named `.env`, but will not ignore env files with other names, such as the commonly used `.env.local`.

This makes it easy for developers to add their environment variables in a `.env.local` file, work on their project, then accidentally commit all the files for their project to git without realizing that their `.env.local` (and the potentially sensitive API keys therein) was included in the commit.

### Describe the proposed solution

Add a `.env.*` line to the `.gitignore` files of the create-svelte package templates. This way, all files with a ".env." prefix will be git ignored by default, including `.env.local`.

### Alternatives considered

n/a

### Importance

nice to have

### Additional Information

n/a

### PR DESCRIPTION
**Pull request by kellenmace**
Fixes #2904.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Conduitry** [comment]
IMO this should only add `.env.*`, if anything, and not `.env*`.

**Comment by bjon** [comment]
Shouldn't only env files ending with _.local_ be ignored?
We're using vite's support for modes, e.g. `.env.[stage|prod]`

**Comment by Rich-Harris** [comment]
Thank you! Aside from the feedback above, can you reinstate the [deleted checklist](https://github.com/sveltejs/kit/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and add a changeset?

**Comment by kellenmace** [comment]
Thanks for the feedback, all! 🙌

@Conduitry - Sounds good. I updated the PR so that `.env` and `.env.*` files are git ignored. This way, on the off chance that the dev has some other file that begins with ".env" in their project, like ".envision", it won't be affected.

@bjon - Files like `.env.local`, `.env.stage` and `.env.prod` should generally not be added to version control. They often contain sensitive data like API keys. Devs should set their environment variables in their hosting provider's UI for their staging and prod sites. If a developer has a reason to want those included in git (which I wouldn't recommend), they can just tweak the `.gitignore` file to accomplish that. Next.js, for example, excludes those files in their `.gitignore` file for new projects, as well: https://github.com/vercel/next.js/blob/canary/examples/active-class-name/.gitignore#L27-L31

@Rich-Harris - Yes, checklist reinstated and changeset added. Please let me know if anything else is needed. 👍🏼

**Review by antony — APPROVED** [review]

**Pull request merged**
