### PR TITLE
Add note to install test dependencies

### PR DESCRIPTION
**Pull request by mohe2015**
### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by benmccann** [comment]
I run on Ubuntu and don't remember having to do this. What happened before you ran this? Did you get a message telling you to run this command?

**Comment by Conduitry** [comment]
For me, on WSL (which is effectively headless), there are a ton of dependencies that need to be installed for the Chromium binaries to be able to run. For me, this manifested as a series of `lib[whatever].so not found` errors, and for each one I had to search online for what apt package I had to install to satisfy it, and then try again to see what the new error was. Rather than install these on WSL just for SvelteKit/Playwright, I ended up using a weird Docker solution that I wouldn't actually wish on anyone.

If you're using Linux as your desktop OS, and you are able to run Chrome/Chromium, you probably have all of these dependencies installed anyway, and so wouldn't have faced this.

The problem that this PR is attempting to address is real, but there could probably be some adjustment to the exact message we're adding to the readme.

**Comment by mohe2015** [comment]
Also got the `lib[whatever].so not found` errors in a clean ubuntu docker container. I think I also installed just chromium-browser and firefox and they where still there. Probably some additional packages that are usually present on desktop systems are needed.

**Comment by mohe2015** [comment]
```
docker run -it ubuntu
apt update
apt install git curl sudo
curl -fsSL https://deb.nodesource.com/setup_16.x | bash 
apt-get install -y nodejs
git clone https://github.com/sveltejs/kit.git
npm i -g pnpm
pnpm i
pnpm test
apt install -y chromium-browser libnss3
# more missing .so libs
npx playwright install-deps # magic
# this would've been the command lol
apt-get install -y --no-install-recommends fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 ffmpeg libcairo-gobject2 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgdk-pixbuf2.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libx11-xcb1 libxcb-shm0 libxcursor1 libxi6 libxrender1 libxt6 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good libegl1 libenchant1c2a libepoxy0 libgl1 libgles2 libgstreamer-gl1.0-0 libgstreamer1.0-0 libharfbuzz-icu0 libharfbuzz0b libhyphen0 libicu66 libjpeg-turbo8 libnotify4 libopenjp2-7 libopus0 libpng16-16 libsecret-1-0 libsoup2.4-1 libvpx6 libwayland-client0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 libwoff1 libxkbcommon0 libxml2 libxslt1.1 xvfb
```

**Comment by mohe2015** [comment]
Maybe adding that apt-install command somewhere or a reference to upstream would make sense. Although I would not want to install and search these manually on another distro (That's the reason I used a docker container)

**Comment by benmccann** [comment]
Yeah, I'd be much more comfortable adding to the playwright docs for anything more complicated and then linking to https://playwright.dev/docs/cli/#install-system-dependencies

**Review by benmccann — APPROVED** [review]

**Pull request merged**
