### PR TITLE
[chore] refactor `is_rel_external` regex

### PR DESCRIPTION
**Pull request by si3nloong**
- ✅ add test cases for `clean_html`, `get_src`, `is_rel_external` and `get_srcset_urls`
- ✅ export function `clean_html`, `get_src` and `get_srcset_urls` for testing purpose
- 🐛 fix `get_srcset_urls` bug
- 🐛 fix `is_rel_external` bug when value is not an URI

### CODE REVIEW

**Comment by si3nloong** [comment]
@benmccann can you review and merge it

**Comment by benmccann** [comment]
There's a related PR where it looks like we might have to do HTML parsing to fix the bug: https://github.com/sveltejs/kit/pull/2713#issuecomment-959088636. I'd like to get Rich to weigh in before we move forward with either

**Comment by benmccann** [comment]
Would you be able to file an issue for the bugs you found so that we don't lose track of them? There's not enough detail from the PR description to really understand what they are

**Comment by si3nloong** [comment]
Hi @benmccann, I actually refactoring the pre-render function using `parse5` (https://github.com/si3nloong/kit/tree/prerender), it will cover the bug fixes I mentioned earlier as well as #2742 , #2105 and #1567 

It still WIP, will definitely update here once I done

**Pull request closed without merging**
