### PR TITLE
Include `charset=utf-8` by default in `application/json` endpoints.

### PR DESCRIPTION
**Pull request by coreh**
Hey there 👋 

I was getting [Mojibake](https://en.wikipedia.org/wiki/Mojibake) when returning unicode data from my endpoints, so I checked the headers and noticed the `charset=utf-8` option was missing from `Content-Type`. This in turn was causing the response to incorrectly be interpreted as Windows-1252.

This PR changes `src/runtime/server/endpoint.js` to include that by default for `typeof body === 'object'`.

I couldn't find any tickets about this, believe this change is simple enough that it's okay for me to open a PR without filing a ticket first.

### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like there are some CI failures

**Comment by Conduitry** [comment]
Yep, this seems reasonable to do for responses that SvelteKit is automatically serializing.

The test failures look like just some `content-type` values in other tests that need to be updated to include the `charset`.

**Comment by coreh** [comment]
Sorry, it was quite late and my brain was foggy, I think I ran tests locally on the wrong directory. 🥶

I'll fix these after work, later today

**Comment by coreh** [comment]
@benmccann @Conduitry Fixed linting and the broken test.

I also removed the value check for the response body in c8cced1b0f8beda571a5a9632b10fed927a7a825, since upon further digging it looks like the tests don't actually encode/decode the strings as byte buffers like a real HTTP implementation would.

**Comment by coreh** [comment]
Hey 👋

Let me know if you need me to make any additional changes or add more tests.

I can add back the test for UTF-8 encoding/decoding if there's a sanctioned way to make the HTTP response binary during the tests (or I can also try to figure out a mechanism for this if not present)

**Pull request merged**
