### PR TITLE
fix: try to address an issue with client-side routing due to regex changes

### PR DESCRIPTION
**Pull request by andyburke**
I've been seeing issues with client-side routing, where it would not match paths. It looks like there have been some recent changes in this area, and if I make the leading `/` in this regex optional, things start working again.

I can't claim to totally understand what's going on here, but this seems to fix the weird issues I was seeing.

### CODE REVIEW

**Comment by benmccann** [comment]
The tests seem to be failing with this PR

**Comment by rmunn** [comment]
The failing tests (at least the ones I've looked at) are failing on a test that compares the route output to an expected value. The route output contains, among other things, the pattern used to match the route. So if you change the pattern from `'\\/'` to `'\\/?'`, the tests are going to fail because the expected value of the route pattern still contains `'\\/'`. You'll need to adjust the relevant tests to expect a pattern containing `'\\/?'` before the unit tests will pass.

Also, it would help if you included, either in #1454 or better yer in this PR (written as a set of tests), a list of routes that fail with the code as-is, but pass with your suggested change.

**Comment by rmunn** [comment]
See also #918 and #1049 for some previous routing issues that were fixed by changing the route-matching regex pattern. Please make sure that your change doesn't cause those issues to come back.

**Comment by andyburke** [comment]
@rmunn can you offer any guidance? For me, *every* route client-side is broken without this fix. I can get to the first page through SSR, but then all subsequent links are broken.

I'm not sure how this is working for other people. Maybe I have something screwed up in my setup.

I assume there are regression tests for the other issues mentioned? If I get the tests passing, would that tend to indicate that everything is working as expected?

**Comment by andyburke** [comment]
For clarity: before the change to this line, my setup was working flawlessly. Updating svelte broke things for me. Maybe there was some change in a changelog that I missed that outlined what I needed to do to keep things working with a new version?

**Comment by rmunn** [comment]
@andyburke - Everything's working for me, so I can't really help you without specific examples. Can you create a reproduction with specific examples, please? I'm not going to be able to help unless you show me something that used to work and doesn't, and preferably make it a GitHub repo so I can clone it and reproduce it.

As I said last week:

> Also, it would help if you included, either in #1454 or better yer in this PR (written as a set of tests), a list of routes that fail with the code as-is, but pass with your suggested change.

**Comment by andyburke** [comment]
See https://github.com/sveltejs/kit/issues/1454#issuecomment-847542444

**Pull request closed without merging**
