### PR TITLE
fix: add `node:` prefix and import instead of using globals

### PR DESCRIPTION
**Pull request by eltigerchino**
see https://github.com/denoland/deno/issues/17248#issuecomment-2325128835

Specifically imports `node:process` instead of relying on the `process` global.

TODO:
- [x] add `node:` prefix to polka imports
- [x] add imports to polka instead of relying on globals
- [x] add eslint rule to explicitly import node globals

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by benmccann** [comment]
We've got an eslint rule to enforce `node:` prefix on imports: https://github.com/sveltejs/eslint-config/blob/c91e102547e2c05e05e6927c9a4b16314bdf2dbd/index.js#L60

I wonder if there's also one to ensure globals like that are imported. It could be worth requesting with eslint-plugin-n if it doesn't already exist

**Comment by benmccann** [comment]
Here it is: https://github.com/eslint-community/eslint-plugin-n/blob/HEAD/docs/rules/prefer-global/process.md

We could turn it on in the common eslint config

**Comment by eltigerchino** [comment]
Ben has opened a PR with the node prefix changes for Polka https://github.com/lukeed/polka/pull/212

**Comment by benmccann** [comment]
I think we could merge this without the polka piece. Assuming the polka part is in a patch release then users can get it without any need for us to bump the version here. It'd be nice to do the eslint part though

**Comment by eltigerchino** [comment]
Not sure if I made the right changes here in regards to the extent of the eslint rule.

**Pull request merged**
