### PR TITLE
fix: upgrade mrmime and sirv to modernize javascript mime type

### PR DESCRIPTION
**Pull request by benmccann**
closes https://github.com/sveltejs/kit/issues/11393

### CODE REVIEW

**Comment by Conduitry** [comment]
There are a bunch of lockfile changes here that don't look right. Why are there two versions of esbuild now?

**Comment by Conduitry** [comment]
I've gone ahead an regenerated the lockfile and pushed 548340c32ccdbb157918c5308feacc426d832726. This looks good to me now. We still have mrmime@1 in the tree, but it looks like that's unavoidable until worktop upgrades.

**Comment by benmccann** [comment]
I just pushed the same change because I saw your first comment and not your second yet. I don't know why pnpm does screwy things when you run `pnpm update`...

**Comment by benmccann** [comment]
> This looks good to me now.

Ok, I'll go ahead and merge then

**Pull request merged**
