### PR TITLE
opt into `strict: true` in `tsconfig.json` by default

### LINKED ISSUE #4395: Make strict mode the default when choosing Typescript
### Describe the problem

From a recent conversation I learned that nowadays almost every Typescript starter template of other frameworks (example: the vite templates) and the typescript cli itself default to turning on strict mode. This issue is intended to discuss turning strict mode on for create-svelte, too, and after that I'm happy to open PRs for the vite/rollup template doing the same.

Arguments in favor of strict mode:
- way easier to have it turned on from the start than turning it on later and converting an existing code base
- the TS ecosystem as a whole recommends turning it on by default
- the strict null checks are very nice for catching nullpointer errors early
- if it's off by default, people might be surprised about nullpointers not getting caught because they thought TS should catch these things, too

Arguments against it:
- Potentially steeper learning curve for those new to it

### Describe the proposed solution

Turn on strict mode in the starter templates 

### Alternatives considered

Only turn on a subset of it, for example only the strict null checks option which is arguably the most important one

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #4395. This is a breaking change

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dummdidumm** [comment]
This is closely related to #4495, we should at least release them together to give non-TS users a way to opt out.

The alternative would be to not add `strict` to the generated tsconfig, and remove `checkJs` as well. This means we would need to adjust #4495 to add `strict` accordingly.

**Comment by Rich-Harris** [comment]
Thinking further on this, it feels like `strict` probably belongs in the user-editable `tsconfig`/`jsconfig`, rather than the one we extend from. There's a few other compiler options I'd put in the same category

**Comment by dummdidumm** [comment]
Agree. I'd move the following to the user config:
skipLibCheck, esModuleInterop (honestly not even sure if it works for Svelte files since TS can't see the other files during transpiration)

The following I'm not sure about:
resolveJsonModule (if user doesn't have a `declare module "*.json"` somewhere they would get errors)

**Comment by Rich-Harris** [comment]
I don't think Kit or the default apps rely on `resolveJsonModule` though? Feels like that belongs to user config too

**Comment by Rich-Harris** [comment]
Closing this in favour of #4633, which documents the generated tsconfig and moves non-essential stuff into user config, where it can be changed freely

**Pull request closed without merging**
