### PR TITLE
Use a proxy to intercept responses, rather than a clone

### PR DESCRIPTION
**Pull request by Rich-Harris**
This bypasses the buffering issues encountered in #591

### CODE REVIEW

**Comment by benmccann** [comment]
@stalkerg could you look at this and try testing it?

**Comment by benmccann** [comment]
Ah, so if I'm understanding this correctly, if the user calls `await response.text()` then that call is now made only a single time and we're not making our own call? If so, then I think that will work for the common case of getting the whole response body

I do think that this approach will not be compatible with streaming however. Are we comfortable with shutting off approaches that will let us do streaming in the future? Or should we also try to solve for the streaming use case now while we're working on this?

**Comment by Rich-Harris** [comment]
Correct, `text()` only gets called once. (Calling it a second time would be an error regardless of the proxy.) 

> I do not think that this approach will be compatible with streaming however

Why? All it means is that the streamed response doesn't get inlined. Think of the inlining as a progressive enhancement

**Comment by benmccann** [comment]
I guess you can skip the serialized data with the way hydration works today. I was thinking you wouldn't be able to do that longer-term. E.g. if we have a mode where you trust the contents of the page instead of reconciling every element that might not work. But maybe that's too far away or too speculative to worry about right now

**Comment by stalkerg** [comment]
@benmccann yes, this fix is working for me, thanks!

**Comment by Rich-Harris** [comment]
excellent, will get this merged and released. thanks for verifying

**Pull request merged**
