### PR TITLE
feat: upgrade eslint to v9

### PR DESCRIPTION
**Pull request by benmccann**
We tried before and had to rollback because `typescript-eslint` v7 was not compatible. Try again this time with a pre-release version, which seems to be quite stable. Otherwise we'd have to make all users wait another 2-4 months

Ref https://github.com/typescript-eslint/typescript-eslint/issues/9141

### CODE REVIEW

**Comment by hyunbinseo** [comment]
I have read the `typescript-eslint` issue and understand that the beta release is 'behaviorally stable'.

- https://github.com/typescript-eslint/typescript-eslint/issues/9141

but it still feels weird to have an alpha dependency in the official template.

Would `pnpm update` upgrade `8.0.0-alpha.20` to `8.0.0` once it is officially released?

**Comment by benmccann** [comment]
Yeah, it is a bit weird. But it's much easier for users to just upgrade that one package than to do the whole migration from eslint v8

**Comment by hyunbinseo** [comment]
## Migration Guide

For Prettier users, you can reference this [diff](https://github.com/hyunbinseo/svelte-kit-templates/commit/d6141be07e3766d94b0f129a4bc346f5dadfeb4f).

1. ESLint v9's default config is flat config, and this is used. [Release Note](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#flat-config-is-now-the-default-and-has-some-changes)
2. (Optional) `typescript-eslint` package that uses the flat config has a different package name. [Release Note](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta/#as-an-existing-user)

```diff
- "@typescript-eslint/eslint-plugin": "^7.10.0",
- "@typescript-eslint/parser": "^7.10.0",
+ "typescript-eslint": "8.0.0-alpha.20",
```

```shell
# JavaScript
pnpm i eslint@9

# TypeScript
pnpm i eslint@9 typescript-eslint@rc-v8
pnpm rm @typescript-eslint/eslint-plugin @typescript-eslint/parser
```

3. Legacy ESLint config should be removed, and a new flat config should be added.

```diff
+ eslint.config.js
- .eslintrc.cjs
- .eslintignore # The ignore file should be removed!
```

The content of the config files differs based on (TypeScript, Prettier) installation.

Reference the `Files changed` tab in this PR.

**Comment by niemyjski** [comment]
I upgraded my ts app following these changes and now I'm seeing lots of errors around generics

  7:29  error  'T' is not defined  no-undef
  8:16  error  'T' is not defined  no-undef
  
  ```
  <script lang="ts" generics="T">
    import type { Snippet } from 'svelte';
    import type { HTMLAttributes } from 'svelte/elements';
    import { cn } from '$lib/utils';

    type Props = HTMLAttributes<Element> & {
        children?: Snippet<[T]>;
        items: T[];
    };
```

  
   8:18  error  '$$Generic' is not defined  no-undef
   
   ```
   <script lang="ts">
    import IconViewColumn from '~icons/mdi/view-column';
    import { Button } from '$comp/ui/button';
    import * as DropdownMenu from '$comp/ui/dropdown-menu';

    import type { Table } from '@tanstack/svelte-table';

    type TData = $$Generic;
    export let table: Table<TData>;
</script>
```

**Pull request merged**
