### PR TITLE
Undici

### PR DESCRIPTION
**Pull request by Rich-Harris**
#5113. This replaces `node-fetch` with `undici`, which is more standards-compliant and is built in to Node 18. This will unlock using web streams for request and response bodies, on platforms that support them. 

TODO:

* [x] get remaining tests passing
* [x] replace `git` dependency with `undici@latest` when https://github.com/nodejs/undici/pull/1469 is released
* [x] only apply polyfills where necessary
* [x] document addition of web streams in https://kit.svelte.dev/docs/web-standards

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
The `handles large response` test is failing for reasons I have been unable to figure out

**Comment by Rich-Harris** [comment]
oh and a bunch of packaging tests have started failing for absolutely no good reason whatsoever. jfc software is awful

**Comment by Rich-Harris** [comment]
ok i think the unrelated packaging tests are failing because this PR installs `undici` from git, which means it's pulling in dev dependencies that mess up some stuff. programming is super fun

**Comment by pixelmund** [comment]
Seems like undici had a new release, so we can remove the git dependency now.

**Comment by half-metal** [comment]
Is this PR on the backburner for now, or waiting for something else from undici? Currently using another solution for streaming req/resp, but hoping to only use Sveltekit.

**Comment by benmccann** [comment]
I fixed the merge conflict against `master`. The `Load › handles large responses` test is still failing though

**Comment by benmccann** [comment]
I don't really understand why `handles large responses` is starting a second server. I guess it's to calculate `times_responded`? But could we simplify by having a single server with a `large-response.json` endpoint that increments a global `times_responded`?

**Comment by Rich-Harris** [comment]
> I don't really understand why `handles large responses` is starting a second server

Because before undici it wasn't possible to generate a chunked response from a SvelteKit app. That's no longer the case, so I've updated the test — instead of generating the response in a second server, it does it in an endpoint

**Review by benmccann — APPROVED** [review]

**Pull request merged**
