### PR TITLE
fix: ignore 'content-type' header capitalization (#1463)

### LINKED ISSUE #1463: SSR is case sensitive for headers (content-type)
**Describe the bug**
The content-type header field is case-sensitive, adding graphql to a clean project will cause it to error with Cannot read property 'split' of undefined but making it fully lower case manually allows it to function as expected

Graphql adds a fetch in load with the content type header named as Content-Type making it lower case makes it work

**Logs**
<details>
<summary>Log</summary>
> svelte-kit dev

Debugger listening on ws://127.0.0.1:57865/df48eb33-d329-4a79-983a-6807c41c0db1
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

  SvelteKit v1.0.0-next.107

  network: not exposed
  network: not exposed
  network: not exposed
  local:   http://localhost:3000
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network

A component can only have one <script context="module"> element
ParseError: A component can only have one <script context="module"> element
    at error (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\svelte@3.38.2\node_modules\svelte\compiler.js:16752:20)
    at Parser$1.error (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\svelte@3.38.2\node_modules\svelte\compiler.js:16828:10)
    at parse$3 (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\svelte@3.38.2\node_modules\svelte\compiler.js:16937:17)
    at compile (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\svelte@3.38.2\node_modules\svelte\compiler.js:30012:18)
    at compileSvelte (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\@sveltejs+vite-plugin-svelte@1.0.0-next.10_svelte@3.38.2+vite@2.3.2\node_modules\@sveltejs\vite-plugin-svelte\dist\index.js:244:48)
    at async TransformContext.transform (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\@sveltejs+vite-plugin-svelte@1.0.0-next.10_svelte@3.38.2+vite@2.3.2\node_modules\@sveltejs\vite-plugin-svelte\dist\index.js:837:27)
    at async Object.transform (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\vite@2.3.2\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:44155:30)
    at async transformRequest (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\vite@2.3.2\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:58421:29)
    at async instantiateModule (E:\dev\rafael\IOT\webobtron\node_modules\.pnpm\vite@2.3.2\node_modules\vite\dist\node\chunks\dep-efbff8d5.js:68026:10)
12:38:32 [vite] page reload src/routes/index.svelte
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at parse_body (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1383:60)
    at respond (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1514:11)
    at fetch (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:731:30)
    at load (index.svelte:13:30)
    at load_node (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:818:30)
    at respond$1 (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1039:21)
    at async render_page (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1186:20)
    at async render (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1537:10)
    at async Object.handle (e:/dev/webobtron/src/hooks.ts:14:24)
    at async respond (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1510:10)
Unexpected token T in JSON at position 0
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:790:22)
    at async load (index.svelte:22:33)
    at async load_node (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:818:12)
    at async respond$1 (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1039:15)
    at async render_page (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1186:20)
    at async render (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1537:10)
    at async Object.handle (e:/dev/webobtron/src/hooks.ts:14:24)
    at async respond (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1510:10)
    at async Immediate.<anonymous> (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index.js:3305:23)
</details>

**To Reproduce**
npm init svelte@next
npx svelte-add graphql
npm run dev
open http://localhost:3000

**Expected behavior**
It to parse content-type header correctly

**Stacktraces**
<details>
  <summary>Stack trace</summary>

Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at parse_body (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1383:60)
    at respond (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1514:11)
    at fetch (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:731:30)
    at load (index.svelte:13:30)
    at load_node (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:818:30)
    at respond$1 (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1039:21)
    at async render_page (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1186:20)
    at async render (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1537:10)
    at async Object.handle (e:/dev/webobtron/src/hooks.ts:14:24)
    at async respond (file:///E:/dev/webobtron/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.107_svelte@3.38.2/node_modules/@sveltejs/kit/dist/ssr.js:1510:10)

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 37.30 GB / 63.68 GB
  Binaries:
    Node: 15.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.12.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - E:\dev\tools\watchman\bin\watchman.EXE
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.62)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107
    svelte: ^3.38.2 => 3.38.2

- Your browser
Firefox nightly

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
The default?
</details>

**Severity**
Annoying

### PR DESCRIPTION
**Pull request by thislooksfun**
Fixes #1463

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by thislooksfun** [comment]
Um... no idea why the tests all failed now. I'm pretty sure that's not my fault.

**Comment by Rich-Harris** [comment]
Thank you. I made a small change — the headers are already getting lowercased, there's no need to do it again. We can just pass the lowercased headers through to `parse_body` https://github.com/sveltejs/kit/commit/babe515f9f5c816fd507920f1f16012263e7a71f

**Comment by Rich-Harris** [comment]
Thank you. I made a small change — the headers are already getting lowercased, there's no need to do it again. We can just pass the lowercased headers through to `parse_body` https://github.com/sveltejs/kit/commit/babe515f9f5c816fd507920f1f16012263e7a71f

**Comment by thislooksfun** [comment]
Yeah I thought of that but it's way harder to add a test that way. Ah well, balancing these things is hard. Either way I'm glad it's fixed!

**Pull request merged**
