### PR TITLE
chore: improve error reporting for tests

### PR DESCRIPTION
**Pull request by gtm-nayan**
- replace inverted `assert.ok`s with `assert.not` to make failure messages less confusing
- replace `assert.ok(string.includes` 
- add helper for getComputedStyle that fails with selector not found instead of just: expected some string got null

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

**Review by benmccann — APPROVED** [review]
only reason I don't go ahead and merge this is because it's marked as draft. feel free to merge yourself or let us know if you'd like us to merge it

**Comment by gtm-nayan** [comment]
Had some changes I forgot to push yesterday, might need another review, sorry.

**Comment by dummdidumm** [comment]
Why is this only showing "3 successful checks"? What's going on Github?

**Comment by gtm-nayan** [comment]
I skipped CI for the last commit since it was just moving a comment down and the previous one passed. Apparently that doesn't show the runs from the previous commit.

**Comment by dummdidumm** [comment]
interesting, I didn't know you can do `[no ci]` to skip it 😄 will merge this then 👍

**Comment by gtm-nayan** [comment]
https://github.com/sveltejs/kit/pull/9730#issuecomment-1517203762

Have that question still, might be able to shave off quite a few minutes if running cross-platform tests on the first two checks is not necessary.

**Comment by dummdidumm** [comment]
I think we should keep that, they test different environments

**Pull request merged**
