### PR TITLE
chore: remove top level promise await behavior

### PR DESCRIPTION
**Pull request by gtm-nayan**
Closes https://github.com/sveltejs/kit/issues/10106

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like maybe the generated types don't allow `void` as a return type for `load`. Not sure what we think about whether that should be allowed or not. @dummdidumm?

**Comment by Rich-Harris** [comment]
the site deploy failure looks like a real bug, though i'm a bit confused by it

**Comment by Rich-Harris** [comment]
oh it's because the site has a `load` that returns top-level promises 🤦 fixed

**Comment by Rich-Harris** [comment]
this LGTM — should it still be draft, or can we merge?

**Comment by dummdidumm** [comment]
I think we can merge, AFAIK it was in draft Mode because of type failures which I fixed

**Review by benmccann — APPROVED** [review]

**Review by benmccann — CHANGES_REQUESTED** [review]
oh wait. this one needs a changeset still

**Pull request merged**
