### PR TITLE
avoid double import of `$env/dynamic/[mode]` modules

### LINKED ISSUE #5941: Dynamic Public Environment Variables are undefined in +server.ts endpoints
### Describe the bug

Hello, I want to start off by thanking everyone involved for their hard work and clever ideas that have brought Svelte and Sveltekit to the points that the projects are at now 🥰

I updated to the latest version of Sveltekit today, and after going through all the migrations and fixing everything, I have one remaining problem in my project, that dynamic public environment variables are not available in +server.ts endpoints.

I made a simple example repository showing the issue. After you install and build it, you can see that the public dynamic is rendered correctly when you navigate to /

If you navigate to /static, the endpoint will return a public and a private static environment variable and display 'working foo'.

If you navigate to /dynamic, the endpoint will return a public and private dynamic environment variable, and should display 'working bar'. However, the public dynamic variable is undefined, so it displays 'undefined bar'.

### Reproduction

https://github.com/ssbm-oro/sveltekit-dynamic-public-bug

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 78.63 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    npm: 8.13.2 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Attempt to fix #5941. No test because the bug doesn't happen inside the workspace

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by benmccann** [comment]
Will this prevent the user from being able to change the env files after server startup?

**Comment by Rich-Harris** [comment]
Changing `.env` will cause the dev server to be restarted

**Review by benmccann — APPROVED** [review]
lgtm. although I haven't fully followed what's happening and why this fixes things. @bluwy and @dominikg might be understanding the situation more closely

**Review by bluwy — APPROVED** [review]
@benmccann it looks like the issue is that we're slightly tapping into Vite's internals to load `env-private.js` and `env-public.js`, where if Vite controls the entire import analysis flow, it would usually load them as `/node_modules/@sveltejs/kit/src/runtime/env-private.js`. Only imports outside of root would (usually?) use `/@fs`, which this PR changes to emulate this.

Ideally we would put these runtime files in `pkg.exports`, so we can `ssrLoadModule` them directly without resolving the path ourselves, but @Rich-Harris brought up that we want to keep this private API and intellisense-wise.

I think the solution now is fine, but if more issues appear later, it could be worth investigating a safer way.

**Pull request merged**
