### PR TITLE
update prerender error message as per #1176

### LINKED ISSUE #1176: 'linked from null'
**Describe the bug**
The parenthesized text should be omitted if `parent` is `null`: https://github.com/sveltejs/kit/blob/53521dbb7fa43789cb8c86ca5c4cd220d2d349ed/packages/kit/src/core/adapt/prerender.js#L75-L81

**To Reproduce**
Throw an error in `/` (in `load`), and prerender.

**Expected behavior**
> 500 /

rather than

> 500 / (linked from null)

**Severity**
low

### PR DESCRIPTION
**Pull request by borntofrappe**
Closes #1176

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by borntofrappe** [comment]
I'm unsure as to the option connected to the changesets

> If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

Apologies for my ignorance

**Comment by dummdidumm** [comment]
Run `pnpx changeset` . It will ask you which of the packages were changed and most of the time correctly identifies the ones that actually were. Select the one (in this case Kit) by using the up/down arrows and pressing space, then press enter to go to the next prompt. It should be a patch release so just press enter to continue without marking anything as a major/minor release up until the patch prompt, where you enter the text that will appear in the changelog later on. Confirm by pressing Y and you're done.

**Comment by borntofrappe** [comment]
Understood, and thanks for the quick response @dummdidumm 

The only question remained is whether a changeset is warranted for the specific pull request. I considered a few _closed_ pull requests and it seems almost excessive to include one in this instance. 

Sorry for being annoying, but I don't want to overstep my boundaries.

**Comment by dummdidumm** [comment]
Technically, at least one changset for a package is needed for it to be deployable (a bot opens PRs which upon being merged result in deployments). In the case of Kit that happens often enough though. So what's left is personal judgement. Personally I would almost always add a changeset even for such small changes, like "Better prerender error message". Adding a changeset is not overstepping boundaries in any way I'd say.

**Comment by borntofrappe** [comment]
Thank you for the patience @dummdidumm, I'll commit a changeset to be on the safe side

**Comment by Rich-Harris** [comment]
thank you!

**Pull request merged**
