### PR TITLE
provide access to request context via `event.platform`

### LINKED ISSUE #8706: Include FetchEvent (waitUntil) in platform data for Vercel edge adapter
### Describe the problem

No access to `event.waitUntil` when deploying to vercel edge.

I'm using the vercel adapter (edge mode) and trying to send trace data from `hooks.server.ts` without blocking the response. With the cloudflare adapter I can use `platform.context.waitUntil(sendTraceData)` to keep the process alive until the trace data is sent. 

### Describe the proposed solution

Have the FetchEvent (waitUntil) exposed in vercel adapter (in edge mode) to match capabilities of cloudflare adapters.

### Alternatives considered

- block the user response
- fetch and hope the runtime doesn't exit prematurely
- use cloudflare instead

### Importance

would make my life easier

### Additional Information

Vercel Build Output API (V3) has a link to an example function with an event argument. So I'm guessing it should be possible for svelte kit to expose it. Also Nextjs has it I think

https://github.com/vercel/examples/blob/f52a98fb2065e2ee75ae9cc59c9c2d3a612e6c07/build-output-api/edge-functions/.vercel/output/functions/index.func/index.js#L1

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #8706. If you have `adapter-vercel` installed, you'll get correct typings for `event.platform` automatically.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Lint is failing because `@vercel/edge` and `@types/node` both define a global `process` var, but differently. Not sure how to fix

**Review by dummdidumm — DISMISSED** [review]

**Comment by dummdidumm** [comment]
Ugh, that lint is from the `@vercel/edge` package, type checking fails in on of the `d.ts` files.

**Comment by dummdidumm** [comment]
My quick-fix-solution would be to copy over the needed type and remove the dependency on `@vercel/edge`

**Review by tcc-sejohnson — APPROVED** [review]
LGTM, this is awesome. I didn't know we could do this with Kit + Vercel.

**Pull request merged**
