### PR TITLE
chore: remove external option

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #8756, though we should probably leave the discussion open in case anyone objects

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by gtm-nayan** [comment]
I was recently trying to deploy a site that used PDF.JS, in attempts to make rendering work on node it depends on some packages with native bindings. I know those code paths wouldn't be reached, but it'd make the builds fail cause esbuild couldn't bundle those.

I should note that this was with next.50-ish of adapter-vercel, not sure if anything's changed since then but it might not be completely useless.

**Comment by Rich-Harris** [comment]
Presumably you were using serverless functions rather than edge? In newer versions, esbuild is only used for edge functions

**Comment by gtm-nayan** [comment]
That's correct, but wouldn't a similar thing apply to edge builds as well?

For example [this repl](https://hyrious.me/esbuild-repl/?version=0.17.5&mode=build&modules=%5B%5B%22main.js%22%2C%22export+let+a+%3D+1%3B%5Cn%5Cnexport+const+abc+%3D+unknown+%3F+%28await+import%28%5C%22.%2Fmodule_1.js%5C%22%29%29.foo+%3A+%7B%7D%3B%22%2C1%5D%2C%5B%22module_1.js%22%2C%22import+canvas+from+%5C%22cairo%5C%22%3B%5Cn%5Cnexport+const+foo%3D+canvas.foo%3B%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%2C%22platform%22%3A%22browser%22%2C%22treeShaking%22%3Atrue%2C%22minify%22%3Atrue%7D), 

If I know the dynamic import for `module_1.js` would not be reached, then even if the dep `smth-native` didn't work on the edge, the edge function would be fine without it. Otherwise without externalizing, it won't get past the build stage.

**Comment by Rich-Harris** [comment]
How would you find yourself in that situation in a real project? (Genuine question)

**Comment by gtm-nayan** [comment]
I can only speak from my own experience,

The pdf package renders to a canvas element on the browser, but it used the "canvas" package (has native bindings) to render to PNGs in Node. Its environment checks couldn't be statically analyzed so the imports to canvas weren't treeshaken and esbuild refused to go through with the build.

Eventually I resorted to removing all references to the package on the server cause I only cared about rendering in the browser, but I reckon someone might want to only use the text or metadata side of the library on the server and wouldn't want their builds to fail because of the unused rendering side.

**Comment by Rich-Harris** [comment]
Gah. That's probably reason enough to keep it for now. Hopefully one day people will correctly use `pkg.exports` everywhere and we can avoid this nonsense.

**Pull request closed without merging**
