### PR TITLE
fix: use internal alias that won't collide with user aliases

### PR DESCRIPTION
**Pull request by benmccann**
closes https://github.com/sveltejs/kit/issues/9009

### CODE REVIEW

**Review by Rich-Harris — APPROVED** [review]

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
Just noticed lint is failing - rescinding my approval!

**Comment by Rich-Harris** [comment]
The obvious solution would be to `declare module '@sveltejs/kit/paths'` but that would mean users see it. I don't think I see an alternative to adding `// @ts-expect-error` to every import

**Comment by Conduitry** [comment]
Can we switch to something like `$$internal` instead?

**Comment by Rich-Harris** [comment]
It occurs to me that we're currently exposing `$internal/paths` along with `0SERVER` and `MANIFEST` and various other things that shouldn't be exposed:

image

It would be nice to not do that. If that means a few `// @ts-expect-error` comments and a smidge less type safety I think it's a price worth paying

**Comment by benmccann** [comment]
I finally figured out how to make this work without exposing it or using ts-ignore

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
nice!

**Pull request merged**
