### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Comment by benmccann** [comment]
@oscard0m thanks for this. It looks like it's not currently working with pnpm. The build is giving the error:

> Error: Dependencies lock file is not found in /home/runner/work/kit/kit. Supported file patterns: package-lock.json,yarn.lock

**Comment by oscard0m** [comment]
> @oscard0m thanks for this. It looks like it's not currently working with pnpm. The build is giving the error:
> 
> > Error: Dependencies lock file is not found in /home/runner/work/kit/kit. Supported file patterns: package-lock.json,yarn.lock

Ok I just noticed you aren not using a `package-lock` file for `pnpm` installation so I guess this cache has not sense. 
Curiosity here, because I have never used `pnpm` before, what's the benefit of using it instead of `yarn` or `npm`? @benmccann

**Comment by benmccann** [comment]
We're using pnpm because we have a monorepo. It can manage building multiple different packages in the same repo

**Comment by oscard0m** [comment]
> We're using pnpm because we have a monorepo. It can manage building multiple different packages in the same repo

I like the benchmarks also! https://pnpm.io/benchmarks

**Pull request closed without merging**
