### PR TITLE
Remove session

### LINKED ISSUE #4426: Navigating from prerendered page to non-prerendered page does not trigger hooks
### Describe the bug

When a site has a mix of prerendered and non-prerendered pages, if the first page a client lands on is a prerendered page, `getSession` will not be called when the client navigates to a non-prerendered page.

This means that if you have a site with a landing page (which is the same for all users) and personalized content (log in to save your todo lists), prerendering becomes a trap. Because if you use `getSession` to look up the users' data in the database and load their todo lists, that will break as soon as you decide to prerender your landing page.

### Reproduction

https://github.com/rmunn/prerender-and-hooks-repro

Run `pnpm run dev`, then go to `/` first, which is prerendered. Then click on the navigation link to `/userpage`, and notice that `getSession` is *not* called, so the user page would not be able to present its personalized content.

Navigating directly to `/userpage` works.

### Logs

```shell
Actual:
  Handle hook ran for URL /
  getSession was called for URL /

Expected:
  Handle hook ran for URL /
  getSession was called for URL /
  Handle hook ran for URL /userpage
  getSession was called for URL /userpage
```

### System Info

```shell
System:
    OS: Linux 5.4 Linux Mint 19.1 (Tessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 6.51 GB / 62.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 7.23.0 - ~/.local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 96.0.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/kit: next => 1.0.0-next.302 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

I can work around this by adding `router = false` to the landing page which I've marked as `prerender = true`. But the current behavior, where prerendering one page changes the behavior of a *different* page (whose `handle` and `getSession` hooks no longer run) seems wrong to me. The https://kit.svelte.dev/docs/hooks documentation is quite clear that hooks for prerendered pages run at build time, but I expected that that meant that `handle` and `getSession` hooks would only run for non-prerendered pages, not that they would never run at all if a prerendered page was the first page visited on the site.

So either this is a bug, or it's a case of unclear documentation.

### PR DESCRIPTION
**Pull request by Rich-Harris**
Implements #5883. This removes `event.session` from `load`, the `session` store, and `getSession`. It's easy to use `event.locals` in `handle` along with `+layout.server.js`/`+page.server.js` to provide equivalent functionality.

Closes #4426.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by benmccann — APPROVED** [review]

**Comment by rmunn** [comment]
I've closed two issues as moot now that `session` is gone:

* #5176 
* #1726

A quick issue search on the word "session" turned up a lot of issues that mention that word, but only those two seemed to be specifically about the special `session` store that has just been removed. If this PR is reverted in the near future, we can reopen those issues.

**Comment by MathiasWP** [comment]
> What about SPA? This was a really bad move

If you application is SPA only, then you should be able to achieve the same behaviour by creating your own store and calling it "session" 👍

**Comment by Rich-Harris** [comment]
If you have access to a server, then you can return the equivalent of session data from a `+layout.server.js`. If you don't, then you couldn't return `session` anyway.

**Comment by bjon** [comment]
@Rich-Harris How do I get the data from `+layout.server.js`, in `+layout.js`? `await parent()` is empty in `+layout.js`.

**Comment by dummdidumm** [comment]
https://kit.svelte.dev/docs/load#input-properties-data

**Comment by bjon** [comment]
@dummdidumm Thanks a lot! Didn't even know that data prop existed. 👍🏻

**Pull request merged**
