### PR TITLE
typecheck in CI

### PR DESCRIPTION
**Pull request by Rich-Harris**
this will fail, but at least it gives us a list of things we need to fix. #441

### CODE REVIEW

**Comment by benmccann** [comment]
We might want `RequestHandler.headers` to be of type `Headers`

**Comment by benmccann** [comment]
It might be useful to add a TODO above the `Headers` definition to update it after https://github.com/microsoft/TypeScript/pull/26797 is released hopefully in TypeScript 4.3 to update the definition to something like:
```
{
  [key: string]: string;
  'set-cookie': string | string[]
}
```

**Comment by Conduitry** [comment]
Would shipping types that require a newer version of TS be considered a breaking change? How do projects under semver generally handle the implied TS peerdep that goes along with their published types?

**Comment by benmccann** [comment]
I suppose it might be. Probably still worth making a note of it even if we want to hold it for a major release

**Comment by dummdidumm** [comment]
I would consider that a breaking change. But it's possible to specify type definitions for certain TS version ranges, which could work if the type is not completely changed, just better typed in a more recent version.

**Comment by Rich-Harris** [comment]
If we change the type from

```
Record<string, string>
```

to

```
Record<string, string> & { 'set-cookie': string | string[] }
```

then it wouldn't break anyone's app, even if they do typechecking, because they would only have been able to return a single `set-cookie` header as a string anyway. So I'm personally not concerned

**Comment by Rich-Harris** [comment]
ah ok i just reread and you're talking about requiring a new TS version, not changing the types. yeah i guess that is a breaking change. still not concerned though because of what @dummdidumm said

**Pull request merged**
