### PR TITLE
feat: `resolveRoute` function

### PR DESCRIPTION
**Pull request by Rich-Harris**
#10282. after this is merged into `master`, and `master` is merged into `version-2`, we can open another PR that removes `resolvePath`

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
We could do this - though it will probably mean that people end up migrating it manually as opposed to via the migration tool and I'm not sure if we have a preference there

**Comment by Rich-Harris** [comment]
I trust deprecation warnings more than I trust automated migrations. I definitely don't think the existence of a migration tool should prevent us from providing useful feedback — there will be plenty of people who want to address deprecation warnings (possibly over a period of time) who aren't ready to bump majors

**Review by benmccann — APPROVED** [review]
I guess in this case it'd be hard to automigrate anyway since this one includes the base. I forgot for a moment that we're doing more than moving the package and renaming the function.

I didn't check if this is in the migration guide already. If it's not, we might want to include that update as part of this PR

**Comment by Rich-Harris** [comment]
> If it's not, we might want to include that update as part of this PR

this is the deprecation PR. the migration instructions will be part of the removal PR

**Pull request merged**
