### PR TITLE
use es2022 instead of es2020

### LINKED ISSUE #8980: [feature] adapter-cloudflare: make build target configurable
### Describe the problem

I would like the build target to be configurable for the `adapter-cloudflare` package. I want to use `es2022` to get `top level await` but `es2020` is hardcoded: https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare/index.js#L49

### Describe the proposed solution

I'd like the build target to be configurable by the user.

### Alternatives considered

I've considered:
- making my code conform to es2020 using the `vite-plugin-top-level-await` plugin
- patching adapter-cloudflare using https://www.npmjs.com/package/patch-package

Right now I'm using a patch, as I run into problems with the `vite-plugin-top-level-await` plugin and requiring `es2022` is fine for my use-case.

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #8980

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Conduitry** [comment]
We don't need to worry about this being breaking for anyone? All Cloudflare projects are continuously updated to the latest version of their JS engine? There's no setting in their dashboard for this, and projects don't default to staying on the then-latest version when they were originally created?

**Comment by Rich-Harris** [comment]
Am basing this on https://github.com/cloudflare/workers-sdk/pull/2720. The runtime is [kept up to date](https://developers.cloudflare.com/workers/platform/compatibility-dates/) for all workers. If somehow this _did_ cause a problem for somewhere (and I'm not sure how it could, given what we know) the worker would fail to deploy — it wouldn't cause failures in production

**Comment by dummdidumm** [comment]
I read that doc as "set a compatibility date in your config and workers will not upgrade beyond that", which means changing the build target likely affects some people.

**Comment by Rich-Harris** [comment]
> Cloudflare regularly updates the Workers runtime. These updates apply to all Workers globally

They update the runtime, but they preserve old bugs

**Comment by dummdidumm** [comment]
Mhm ok I read it as "runtime is part of the thing you pin", not "code on top of the runtime is what you pin", but maybe that's just me.

**Comment by Rich-Harris** [comment]
When it comes to syntax, it's the _engine_ that matters, rather than the _runtime_, and IIUC workers always run on a recent version of V8 (because of security, and because of the economies of scale from being able to run many workers in a single process regardless of when they were first created). I'm pretty confident this change is safe. If not, we'll find out very soon!

**Review by dummdidumm — APPROVED** [review]

**Pull request merged**
