### PR TITLE
`@sveltejs/package` Allow disabling the default behavior of copying package.json to the output directory when packaging a Svelte library

### LINKED ISSUE #6824: `@sveltejs/package` Allow disabling the default behavior of copying `package.json` to the output directory when packaging a Svelte library
### Describe the problem

For context, I'm building a cross-framework component library so I've set up a standard package structure for each framework in my monorepo with npm workspaces.

I'm using Vite with `@sveltejs/package` to develop and build my components. However, `@sveltejs/package` breaks my toolchain because it creates a copy of `package.json` in my `dist` folder.

npm workspaces picks up both the original `package.json` and `dist/package.json`, causing other dependent packages to break due to the duplication.

### Describe the proposed solution

I rather keep my project structure and manage a single copy of `package.json` manually, so I'd like an option to disable the copy behavior.

This should ideally be added to `svelte.config.js` as a `copyPackageJson` option.

### Alternatives considered

I've tried running a script to delete `dist/package.json` manually after each build, but this frequently breaks when Nx builds multiple packages concurrently due to the race condition.

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bryanmylee**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

This resolves #6824.

For context, I'm building a cross-framework component library so I've set up a standard package structure for each framework in my monorepo with npm workspaces.

I'm using Vite with `@sveltejs/package` to develop and build my components. However, `@sveltejs/package` breaks my toolchain because it creates a copy of `package.json` in my `dist` folder.

npm workspaces picks up both the original `package.json` and `dist/package.json`, causing other dependent packages to break due to the duplication.

This PR adds a `copyPackageJson` option to allow disabling the copy feature.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

All existing tests for `@sveltejs/package` pass and I added a test for the new config option.

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by david-plugge** [comment]
The package command also copied the readme and changelog. What about a more general solution like an array of files and folders to copy or a filter function?

**Comment by dummdidumm** [comment]
Yes that could be a more general solution. I'm tempted to put this into `files` but that's currently used for project files only, not sure if that breaking change is worth it (especially since it's not easy to detect) and if that's even a good API.

**Comment by bryanmylee** [comment]
I didn't notice the README or changelog because it wasn't affecting the monorepo, but perhaps a more general `metadata` field would be better?

We can make its API similar to `files`, except we make the distinction that `files` only relates to project code, while `metadata` refers to the extra things like `README`, `package.json`, and the changelog.

**Comment by bryanmylee** [comment]
Closed this in favor of #6864.

**Pull request closed without merging**
