### PR TITLE
[fix] break out of 404 SPA loop

### LINKED ISSUE #6854: ssr false with +layout.server file cause loop page refresh on 404
### Describe the bug

Create a `+layout.server.js` file when SSR is `false` cause loop refresh of the page.

### Reproduction

```
npm create svelte
npm i
```

Create the following files:
```
/src/routes/+layout.js

export const ssr = false;
```

```
/src/routes/+layout.server.js (empty)
```

```
npm run dev
```

Now when navigating on a non-existent URL the page keeps refreshing indefinitely.

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 11.75 GB / 31.42 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.75
    @sveltejs/kit: next => 1.0.0-next.483
    svelte: ^3.46.0 => 3.50.1
    vite: ^3.1.0 => 3.1.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #6854, but not other cases - when the root +layout(.server).js fails, we also go back to the server for a reload, which would also result in a loop. This could be handled maybe through storing some state in session storage and checking that upon entering an error state again.

Opening this PR regardless to get some discussion going - if we want to explictitly only handle this case for now, or go with a more general solution.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I remember this being finicky when I last looked into it, but: could we handle the SPA initialisation case differently to how we handle hydration and navigation, and never fall back to the server in that case? That way we don't need to worry about infinite loops, or keeping track in `localStorage` or whatever (which has caveats, e.g. if you have the right privacy settings in Firefox you can't use it).

**Comment by dummdidumm** [comment]
That could be another possible solution. We would need to make sure it works for cases where only part of your app is an SPA, too, not sure how that would look like - possibly something like checking that when doing a root layout reload in the error case that the root layout tells you this is csr only.

**Comment by dummdidumm** [comment]
Good point. Hydrate is false, and the router running means SPA mode. So therefore before falling back to the page we would check if we reload the url we are already on, and if so, prevent that. Essentially the existing SPA check but in a different place.

**Comment by dummdidumm** [comment]
pushed up a WIP, code is more convoluted than I'd like and the error is incorrect in case of a root error (404 instead of whatever it should be instead), will look at this again tomorrow

**Comment by dummdidumm** [comment]
Turns out the code was correct already, but I got confused by wrong error messages - turns out, it was/is buggy both on the client and the server:
- on the client it always returned "Internal Error" -> I fixed that here
- on the server, failing data requests (`__data.js?..`) are treated as "Not Found" because `event.routeId` is `null` in this case. Not sure what the right fix is here. Should we add the routeId of the page you're on, and if yes, can we find that out? Else we would need a status code handed to `handleError` after all.

**Comment by dummdidumm** [comment]
Should be good to go now. Besides handling the SPA loop this also fixed some bugs around error handling.

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
