### PR TITLE
feat: support specifying the tsconfig in svelte-package

### LINKED ISSUE #9373: option to specify the `tsconfig.json` in `svelte-package`
### Describe the problem

i like to have a seperate tsconfig file for my svelte code to isolate it from the rest of the project, however `svelte-package` does not seem to have an option to specify the path to the tsconfig.json

### Describe the proposed solution

a `--tsconfig` option like in `svelte-check`

### Alternatives considered

_No response_

### Importance

would make my life easier

### Additional Information

i think it currently gets confused when there are multiple tsconfigs in the project. see #9372

### PR DESCRIPTION
**Pull request by quentinderoubaix**
closes #9373

Adds the option `tsconfig` to svelte-package, allowing to specify which tsconfig / jsconfig to use during the packaging.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by benmccann** [comment]
I don't understand why this is necessary or why it would apply only to svelte package

**Comment by quentinderoubaix** [comment]
hi @benmccann @dummdidumm, a little reminder on this

**Comment by quentinderoubaix** [comment]
hi @benmccann @dummdidumm

sorry to chase again, is there anything I need to update / clarify for this ?
the linked issue #9373 was tagged as ```ready to implement```, but maybe it needs to be re-discussed ?

**Comment by quentinderoubaix** [comment]
image

**Comment by dummdidumm** [comment]
Sorry for being silent for so long - I'm currently focused on Svelte 5. I'll look into this soon, I promise!

**Review by dummdidumm — APPROVED** [review]
Thank you!

**Pull request merged**
