### PR TITLE
fix: respect trailing slash option when navigating from the root page of the basepath

### PR DESCRIPTION
**Pull request by eltigerchino**
fixes https://github.com/sveltejs/kit/issues/11382

The implementation for ensuring the basepath root page always ends with a trailing slash in https://github.com/sveltejs/kit/pull/10763 is wrong because it was implemented in the `load_node` method, causing the `always` trailing slash option to be set on all nodes the root page uses (such as the root layout node), and affecting pages other than the root page. This PR moves the logic closer to where we normalize the URL based on the trailing slash option so we only evaluate the correct trailing slash option after loading the nodes.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like the tests are failing

A note that it looks like https://github.com/sveltejs/kit/pull/11357 fixed the server-side and this is fixing the client side

**Comment by eltigerchino** [comment]
Tests are fixed now. Targeting the link by its href was a bad idea when there's the base path variable involved

**Comment by Nikhil-Software-Cartel** [comment]
hi sir, im facing issues with nginx related to this issue, 
lets say im at website.com/demos/app/login , when i use sveltkit goto function it goes at website.com/demos/app and all static files are broken... let me know if you need more info, im using 
`export const trailingSlash = 'always';
`
hope it will work, but looking for something like, fallback if 404 for asset, like nginx try files, the basepat, asset path etc in svelte config was very confusing.

**Comment by eltigerchino** [comment]
> hi sir, im facing issues with nginx related to this issue, lets say im at website.com/demos/app/login , when i use sveltkit goto function it goes at website.com/demos/app and all static files are broken... let me know if you need more info, im using `export const trailingSlash = 'always'; ` hope it will work, but looking for something like, fallback if 404 for asset, like nginx try files, the basepat, asset path etc in svelte config was very confusing.

@Nikhil-Software-Cartel please provide a reproduction in a new issue or discussion. The svelte discord is a great place to start as well.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Coronon** [comment]
I just spent 1.5 hours debugging this and was about to submit my own PR when I saw this - thank you for all your work everyone!

**Pull request merged**
