### PR TITLE
chore: use satisfies keyword in jsdocs, in create-svelte default template

### PR DESCRIPTION
**Pull request by plbstl**
A small change to make the JavaScript and TypeScript demo apps in create-svelte a bit more similar

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by ghostdevv** [comment]
IMO It would probably be best to just remove those comments since it now automatically types things like load functions

**Comment by dummdidumm** [comment]
We discussed removal previously and decided against it because not all IDEs fully support it and because it's easier for a beginner to understand what the types are

**Review by dummdidumm — APPROVED** [review]
Thank you! Could you add a changeset? Then we're good to merge

**Comment by plbstl** [comment]
Okay done

**Pull request merged**
