### PR TITLE
fix: remove unused SSR CSS files

### PR DESCRIPTION
**Pull request by s3812497**
fixes https://github.com/sveltejs/kit/issues/9161

This PR prevents copying the unused(?) CSS files that are generated from vite's `build.ssrEmitAssets` option. Kit seemingly only uses the client optimised CSS files in the .svelte-kit client bundle, so these server bundle css files shouldn't be copied over.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
This doesn't seem safe to me. I'm not sure that we can know that the CSS is unused on the server. I think if it gets imported from a server file then this will break (https://github.com/sveltejs/kit/issues/5240).

I had an earlier PR to fix the paths when you don't set `paths.relative: true` and I believe it got reverted. We could try to get that PR back in without whatever issue it was causing, which would solve this in most cases by avoiding the creation of duplicate CSS files (as long as you don't set `paths.relative` - maybe we could also fix that one by using relative paths on the server, but I'm not sure)

**Comment by s3812497** [comment]
> This doesn't seem safe to me. I'm not sure that we can know that the CSS is unused on the server. I think if it gets imported from a server file then this will break (#5240).

I don't think they're used anywhere because:
1. `import './styles.css'` the server asset is never referenced in the built output.
2. `import style from './styles.css?inline` is always stored as a variable in the built js file.

> I had an earlier PR to fix the paths when you don't set `paths.relative: true` and I believe it got reverted. We could try to get that PR back in without whatever issue it was causing, which would solve this in most cases by avoiding the creation of duplicate CSS files (as long as you don't set `paths.relative` - maybe we could also fix that one by using relative paths on the server, but I'm not sure)

The problem now also lies in the difference of filenames as well. I'm not sure what changed but the client css assets are now always named after the nodes such as `0.abs34af.css` instead of `_page.sd12sd.css`.

**Comment by benmccann** [comment]
The case I was thinking of would be if you had a `+server.js` file with something like:
```
import css from './example.css';

export function GET() {
    return new Response(css + '\n\np { color: red }');
}
```

I don't know how likely that is, but it'd also be pretty weird that you can import anything you want into a `+server.js` file except for `.css` files which would magically break.

**Comment by s3812497** [comment]
> ```
> import css from './example.css';
> ```
I’ve tested this and the CSS gets inlined as well. Furthermore, this syntax is deprecated by Vite and is equivalent to `import css from './example.css?inline'`. Although, I’m not sure what that would mean once Vite officially stops supporting it.

**Comment by benmccann** [comment]
It looks like Svelte 5 will stop outputting CSS in SSR mode. I wonder if we should just wait until then to avoid the extra code complication here

**Comment by s3812497** [comment]
I agree. I think it's alright to wait until Svelte 5 releases.

**Pull request closed without merging**
