### PR TITLE
Use rendered CSS for AMP pages, rather than emitted CSS

### LINKED ISSUE #808: Use rendered rather than emitted CSS in AMP mode
**Is your feature request related to a problem? Please describe.**
AMP pages have a strict (and somewhat arbitrary) limit on the amount of CSS a page can include. They also provide a guarantee that doesn't exist in non-AMP mode, namely that if `condition` is `false` at SSR time...

```svelte
<script>
  import Foo from '$lib/components/Foo.svelte';

  export let condition;
</script>

{#if condition}
  <Foo/>
{/if}
```

...we can safely omit the styles emitted by `Foo.svelte`.

It would be nice if we could take advantage of that and only include styles for components that were rendered, to increase the likelihood of staying beneath the 75kb ceiling.

**Describe the solution you'd like**
* Configure the Svelte plugin to not emit CSS in AMP mode
* Use `rendered.css` instead of inspecting the module graph

**How important is this feature to you?**
It depends on the outcome of the research we plan to conduct on how much traffic our app would lose if we told AMP to bugger off once and for all.

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #808. Will need a release of `vite-plugin-svelte` with [this change](https://github.com/sveltejs/vite-plugin-svelte/pull/41) before the tests will pass.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by Rich-Harris** [comment]
excellent, thanks so much!

**Comment by Rich-Harris** [comment]
That wasn't intentional — reverted. The basic thinking is that if something is bundleable, it gets bundled, since that way Kit is faster to install. But I'm not sure if it's been applied particularly rigorously or if we should even be thinking that way

**Comment by benmccann** [comment]
I don't suppose it's possible that AMP support will no longer be needed now that Google is showing non-AMP pages in the search carousel? :grin: https://www.lafoo.com/the-end-of-amp/

**Comment by Rich-Harris** [comment]
maybe for SvelteKit 2. time will tell

**Pull request merged**
