### PR TITLE
fix: send validation errors as props when rendering page in the client 

### LINKED ISSUE #5906: `errors` exported by `+page.svelte` is only available on the server and not on the client
### Describe the bug

Cannot access the `errors` object in the client returned by actions (`+page.server.js`). 

### Reproduction

https://github.com/pilcrowOnPaper/sveltekit-action-issue

Description and steps are described in the repo README

### Logs

 (Browser console)
```shell
<Root> was created without expected prop 'errors'
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Memory: 870.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
Browsers:
    Chrome: 98.0.4758.102
    Firefox: 103.0.2
    Safari: 15.6
npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/kit: next => 1.0.0-next.408
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.7
```

Tested with: Safari, Firefox, Chrome

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by pilcrowOnPaper**
Fixes #5906 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dummdidumm** [comment]
Thank you, but this doesn't actually fix the bug, therefore closing.

**Comment by pilcrowOnPaper** [comment]
Huh, thought it did. Sorry about that!

**Comment by pilcrowOnPaper** [comment]
@dummdidumm 

How will I go testing the package? I edited the node module package directly (in the issue reproduction app) and it seemed to fix the problem.

**Comment by pilcrowOnPaper** [comment]
Actually tested the new package (ran it inside test/apps) and it seems to work fine.
Can you elaborate on "doesn't actually fix the bug"? Does it mean the PR doesn't do anything at all, or does it mean it doesn't fix the root problem?

**Comment by dummdidumm** [comment]
I added a test to check the behavior, and the test failed with and without the fix - so did your minimum reproducible on the issue. Furthermore the `props` property isn't read anywhere on the client AFAIK, so I'm not sure why it fixed things for you.

**Comment by pilcrowOnPaper** [comment]
Found my mistake (I mean looking back at the code, it doesn't make sense). SvelteKit was throwing an error, causing the hydration to not occur. I see an error in the browser console but I don't remember seeing it yesterday. Sorry about that!

**Pull request closed without merging**
