### PR TITLE
Add zerops node and static adapter (wip)

### PR DESCRIPTION
**Pull request by nermalcat69**
---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [ ] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by nermalcat69** [comment]
I need to write the md files as well 👍🏼

**Comment by Rich-Harris** [comment]
preview: https://svelte-dev-git-preview-kit-13209-svelte.vercel.app/

_this is an automated message_

**Comment by eltigerchino** [comment]
I'm going to close this because I don't think we're going to officially support more adapters in this repository. It's still possible to publish a community adapter on your own. For example, see:
- https://github.com/geoffrich/svelte-adapter-azure-swa
- https://github.com/sst/v2/tree/master/packages/svelte-kit-sst

**Comment by nermalcat69** [comment]
Oh wow! @eltigerchino thanks that's a nice idea :)

**Pull request closed without merging**
