### PR TITLE
Prerender routes json

### PR DESCRIPTION
**Pull request by Mexican-Man**
### Problem

Prerendered pages on `adapter-cloudflare` should not require a worker request. See issue for more info #7298 

### Solution

Prerender pages as `/foo/index.html` instead of `/foo.html`, then exclude `/foo` in `_routes.json`. This will bypass the worker entirely, and still serve the prerendered page.

I ran the test suite, and tested it on my site with `vite dev` and deployed to Cloudflare Pages. I got the feeling that the change to `packages/kit/src/core/prerender/prerender.js` would cause more friction that it seemed to.

### CODE REVIEW

**Comment by Mexican-Man** [comment]
Y'know, I suppose it would break the prerender tests, wouldn't it? haha

**Comment by Mexican-Man** [comment]
Not sure about that last test. I can't seem to get `goto()` to react to anything.

**Comment by Rich-Harris** [comment]
Thanks you but we can't just change `about.html` to `about/index.html` willy-nilly. One means `/about`, the other means `/about/`.

I'm also not sure this approach scales very far. There's quote a low limit to the number of entries you can have in your `_routes.json` (100 for `include` and `exclude` combined, IIUC) which many sites would immediately exceed.

**Comment by Mexican-Man** [comment]
> Thanks you but we can't just change `about.html` to `about/index.html` willy-nilly. One means `/about`, the other means `/about/`.

That's what I've been alluding to in #7298 . I've got it working to Cloudflare's spec using wrangler, and `vite dev` the behavior *seems* to function identically, but I *don't* know what the exact expected behavior to start with (if different). `/about` still resolves correctly, and `/about/index.html` still 404s (when I was testing). Although I can't speak to `/about` vs `/about/`, Chrome usually changes that automatically 😅

The one failed test says something is wrong, but I can't seem to get it to work no matter what I do (I'm not too familiar with playwright, unfortunately). Aside from that, it seems to work fine for me "in practice".

> I'm also not sure this approach scales very far. There's quote a low limit to the number of entries you can have in your `_routes.json`

~100 prerendered pages? How about adding a cap, or a switch + warning if over 100 entries. Then the worst case would be what's currently happening.

**Comment by Rich-Harris** [comment]
I merged #8422, which adds all assets and prerendered pages (up to the 100-rule limit), so I'll close this — thanks.

In general I think the automated approach is preferable to manually specifying exclusions, though in the rare cases that it _is_ necessary it could be done by modifying the `_routes.json` after it's been created.

**Comment by Mexican-Man** [comment]
Bit late, but just wanted to say thanks. I just took a look at last month's bill, and we're down 85% on billed requests 😊(just from prerendered pages, alone). HUGE; thanks Rich!

**Pull request closed without merging**
