### PR TITLE
Clarified file name in error message as per #7029

### PR DESCRIPTION
**Pull request by jacoblukewood**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

As per #7029 the displayed error message suggesting the user enable prerendering in the +layout.js/+layout.ts file should include the plus symbol and let the user know that if they are using TS, they should make the change in the .ts file.

### CODE REVIEW

**Comment by Conduitry** [comment]
I'm in favor of adding the `+` because what's there now is wrong. I'm hesitant about adding `(+layout.ts if your project is using TypeScript)` because a) this error message is already pretty long and b) mentioning this sort of thing everywhere we mention a JS file is a slippery slope that will start to bog down all of our documentation and messages.

As a compromise, I could probably live with `+layout.js/+layout.ts` or `+layout.js/.ts` - but I think we can expect TypeScript users to mostly internally automatically translate references to `.js` into `.ts` without us needing to call it out as a possibility every time.

**Comment by dummdidumm** [comment]
+1 on just adding the +

**Comment by jacoblukewood** [comment]
> I'm in favor of adding the `+` because what's there now is wrong. I'm hesitant about adding `(+layout.ts if your project is using TypeScript)` because a) this error message is already pretty long and b) mentioning this sort of thing everywhere we mention a JS file is a slippery slope that will start to bog down all of our documentation and messages.
> 
> As a compromise, I could probably live with `+layout.js/+layout.ts` or `+layout.js/.ts` - but I think we can expect TypeScript users to mostly internally automatically translate references to `.js` into `.ts` without us needing to call it out as a possibility every time.

I agree that it does make the message quite long. I think `+layout.js/.ts` is a suitable replacement. I have made the suggested changed to the PR.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you

**Pull request merged**
