### PR TITLE
Use pre to prevent wrong prism/shiki rendering

### PR DESCRIPTION
**Pull request by abbychau**
allocate https://github.com/sveltejs/kit/issues/10559

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
I ran tests, but my current PC is on Windows, so some of the commands are incompatible. I think this PR is straight-forward enough though.

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.
no need

### CODE REVIEW

**Review by benmccann — CHANGES_REQUESTED** [review]
this doesn't look right to me: https://kit-svelte-dev-git-fork-abbychau-master-svelte.vercel.app/docs/adapter-static#github-pages

**Comment by abbychau** [comment]
> https://kit-svelte-dev-git-fork-abbychau-master-svelte.vercel.app/docs/adapter-static#github-pages

I am unable to open this link (wrong address). how does it work? the doc in ths PC is rendered correctly on my PC though.

**Comment by Conduitry** [comment]
The link opens for me.

The YAML file code block isn't rendering the filename correctly.

Compare:

image

with

image

**Comment by abbychau** [comment]
It is on purpose. This PR is to prevent the code renderer to parse this yaml, as a result, filename will not be rendered like other code blocks.

**Comment by gtm-nayan** [comment]
The accompanying issue will be fixed by https://github.com/sveltejs/site-kit/pull/199

I'll close this one.

**Pull request closed without merging**
