### PR TITLE
fix: anchor link issue with hash navigation

### LINKED ISSUE #10234: Same route anchor links only fire once when a hash link is preloaded with `data-sveltekit-preload-data`
### Describe the bug

Clicking a link that goes to an anchor on the page works but after you remove the anchor via the page store the link no longer works.

The use case i had was using anchors for modals, modal opens on anchor link and anchor link is removed on modal close.

### Reproduction

Here's my original repro

https://stackblitz.com/edit/sveltejs-kit-template-default-qwsbag?file=src%2Froutes%2F%2Bpage.svelte

and here is a different approach that highlights the same issue made by a friend

https://stackblitz.com/edit/sveltejs-kit-template-default-fnttrd?file=src%2Froutes%2F%2Bpage.svelte

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 900.20 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Firefox: 114.0.1
    Safari: 16.5.1
```

### Severity

serious, but I can work around it

### Additional Information

The only work around atm is to force a page reload on modal close, which is not ideal

### PR DESCRIPTION
**Pull request by geodask**
closes #10234

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [X] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by geodask** [comment]
I think the issue was caused by `load_cache`. Inside the `click` listener there is check:
```js
if (current.url.hash === url.hash) {
	event.preventDefault();
	a.ownerDocument.getElementById(hash)?.scrollIntoView();
	return;
}
```
 which was true and the function returned so no navigation occured. The current.url contained the url with the hash while we are on the `'/'` route probably because `load_route` returns the previously set promise.  I am not 100% sure if setting `load_cache = null` after hash navigation and `update_url` is the best solution (trying to get familiar with the codebase).

If it's ok, let me know if I need to add a changeset. Thanks!

**Comment by s3812497** [comment]
Hi @geodask , thanks for submitting a PR for this. I've added some additional findings here https://github.com/sveltejs/kit/issues/10234#issuecomment-1752044976 I think we may have to do more than clear the `load_cache` at the point in time of clicking the hash link. Ideally, we would have a changeset and test for the solution too.

**Comment by geodask** [comment]
Hi @s3812497, thanks for your feedback! Due to some commitments during this period of time, I won't be able to tackle the additional work required here. If anyone's up for it, please feel free to take over this PR.

**Comment by dummdidumm** [comment]
Closing due to inactivity and because it seems the issue is stemming from a different source.

**Pull request closed without merging**
