### PR TITLE
expose more types, tidy up others

### LINKED ISSUE #547: Expose more types
Included in #521 — this...

```ts
type Request = {
	host: string;
	method: 'GET';
	headers: Record<string, string>;
	path: string;
	params: Record<string, string | string[]>;
	query: URLSearchParams;
	body: string | Buffer | ReadOnlyFormData;
};

type Response = {
	status?: number;
	headers?: Record<string, string>;
	body?: any;
};
```

```js
import db from '$lib/database';

/**
 * @param {import('@sveltejs/kit').Request} request
 * @param {any} context
 * @returns {import('@sveltejs/kit').Response}
 */
export async function get(request, context) {
	// the `slug` parameter is available because this file
	// is called [slug].json.js
	const { slug } = request.params;

	const article = await db.get(slug);

	if (article !== null) {
		return {
			body: {
				article
			}
		};
	} else {
		return {
			status: 404,
			body: {
				error: 'Not found'
			}
		};
	}
}
```

...and this:

```ts
type LoadOptions = {
	page: {
		host: string;
		path: string;
		params: Record<string, string | string[]>;
		query: URLSearchParams;
	};
	fetch: (url: string, opts?: {...}) => Promise<Response>
	session: any;
	context: Record<string, any>;
};

type Loaded = {
	status?: number;
	error?: Error | string;
	redirect?: string;
	maxage?: number;
	props?: Record<string, any>;
	context?: Record<string, any>;
};
```

```html
<script context="module">
	/**
	 * @param {import('@sveltejs/kit).LoadOptions} options
	 * @returns {import('@sveltejs/kit').Loaded}
	 */
	export async function load({ page, fetch, session, context }) {
		const url = `/blog/${page.params.slug}.json`;
		const res = await fetch(url);

		if (res.ok) {
			return {
				props: {
					article: await res.json()
				}
			};
		}

		return {
			status: res.status,
			error: new Error(`Could not load ${url}`)
		};
	}
</script>
```

We need to expose `Request` and `Response` types for endpoints, and also `LoadOptions` and `Loaded` types for pages (please, someone come up with better names than `LoadOptions` and `Loaded`).

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #547 and #556

### CODE REVIEW

**Comment by benmccann** [comment]
What happens if a query parameter is specified twice? It's annoying to encounter and this API seems simpler, so I'm somewhat okay with saying we don't want to support that - although I suppose there could be rare cases where the user doesn't have control over it. E.g. if you were interfacing with an external API that asked you to create a web hook for them to call and they specified the query parameter twice then we might be stuck between a rock and a hard place

We have the same issue with headers being specified both ways (https://github.com/sveltejs/kit/issues/534). Though there I think we have even less control over it since `fetch` can easily call external APIs I think there's a much stronger argument we must support the repeated headers via `string | string[]`

**Comment by Rich-Harris** [comment]
You can't. `src/routes/[foo]/[foo].svelte` is an error

**Comment by Conduitry** [comment]
I believe Ben's talking about query/search parameters, not slug params. You can absolutely do `.../file?foo=bar1&foo=bar2`.

**Comment by benmccann** [comment]
Ah, yeah. I just saw `params` and guess I didn't look that closely. If this only applies to path params and not query params then please ignore me

**Comment by Rich-Harris** [comment]
yeah, `page.query` is an instance of `URLSearchParams` for that reason — you have `get` and `getAll`

**Comment by Conduitry** [comment]
Oh! Nice. Good call on changing from the POJO that Sapper used.

**Pull request merged**
