### PR TITLE
[feat] warn if svelte not found in dependencies or peerDependencies

### PR DESCRIPTION
**Pull request by benmccann**
This allows `vite-plugin-svelte` to detect which libraries are Svelte libraries

### CODE REVIEW

**Review by Conduitry — CHANGES_REQUESTED** [review]
We should be able to just do `!pkg.dependencies?.svelte && !pkg.peerDependencies?.svelte`, right? We don't need to iterate through all of the keys in the objects.

**Comment by benmccann** [comment]
duh. thank you!

**Comment by dummdidumm** [comment]
wow Github playing tough, @Conduitry you need to approve as well since you requested changes, else we can't merge 😅

**Comment by benmccann** [comment]
doesn't stop you if you're an admin I guess :laughing:

**Pull request merged**
