### PR TITLE
clarify merging semantics

### LINKED ISSUE #7677: Clarify 'last one wins' in load section of the documentation
### Describe the problem

In the load section of the [documentation](https://kit.svelte.dev/docs/load#layout-data) in the appendix it is stated that
> If multiple load functions return data with the same key, the last one 'wins'.

Please clarify what does that mean. It can either be the deepest load function in routing hierarchy or the last load function to resolve (Promises). This phrasing creates unnecessary ambiguity and it can be crucial for some use cases to know this clarification.

### Describe the proposed solution

Include clarification in the documentation.

### Alternatives considered

None

### Importance

would make my life easier

### Additional Information

None

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #7677

### CODE REVIEW

**Comment by Conduitry** [comment]
Do we want to talk about how multiple nested layouts inherit/override in this same way?

**Comment by Rich-Harris** [comment]
I feel like it's pretty obvious once you have one example, no?

**Comment by Conduitry** [comment]
I'll defer to you on that. I thought what we had before this PR was fine too.

**Comment by Rich-Harris** [comment]
So did I

**Comment by benmccann** [comment]
we don't necessarily need an example we could just replace "last" with something more specific like:

> the child overrides the parent (e.g. a page would override a layout)

**Comment by Rich-Harris** [comment]
An example makes it concrete (for example what is meant by 'key'? with the example it's very obvious)

**Review by dummdidumm — APPROVED** [review]

**Pull request merged**
