### PR TITLE
feat: add `bundleStrategy: 'inline'

### LINKED ISSUE #907: Build an output that is usable from local disk (file:// URL)
**Is your feature request related to a problem? Please describe.**
Quite often i code tools which take some input (like a JSON file) and generate a HTML report out of it. This HTML report might be served by a server (e.g. Github Pages) but often just sits somewhere on the disk and should be openable/consumable from there (e.g. `open file:///Users/x/projects/y/build/test/index.html`).

**Describe the solution you'd like**
From initial experiments (with `adapter-static`) I found 2 things I would need for the above to work which I failed to accomplish with `svelte-kit` so far:
- Links/Includes (from `index.html`) need to be relative instead of absolute
  - `paths/assets||base` were quite resistant setting up anything relative 
- The JS field need to be in `IIFE` format (since [module script imports will raise CORS issues](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts))
  - `vite.build: { lib: { name: "my-app", entry: "src/main.ts", formats: ["iife"] }}` produced `UMD and IIFE output formats are not supported for code-splitting builds`

A solution would be to make the 2 things possible.
Perfect would be a simple way to achieve that. Like an specialized adapter.

**Describe alternatives you've considered**
Maybe what I'm trying to achieve is dump and using svelte-kit for such a thing doesn't make much sense? Just stick to `Svelte Classic` ?

With `Svelte Classic` and Vite I can accomplish the above by tweaking `vite.config.js` in the following way:
- Set `base` to `''` (makes the links relative)
- Configure `IIEF` format:
```
build: {
  lib: { name: "my-app", entry: "src/main.ts", formats: ["iife"] },
}
```
- Move the `index.html` to `public/` and add appropriate script and css includes

**How important is this feature to you?**
This is the first thing I usually set up for the majority of apps I'm crafting.

### PR DESCRIPTION
**Pull request by Rich-Harris**
This is something of an experiment. The idea is that, building on top of #13173, it _should_ be possible to bundle a SvelteKit app right into the HTML, so that you can literally just double-click an `app.html` file.

Most apps shouldn't be built this way! But there are certain use cases where it's kinda fun — imagine being able to build a game and literally email it to your friends, without needing to host it somewhere.

This PR has no tests yet and there are probably some things that don't work correctly. It may turn out that there are insurmountable technical challenges, I don't know yet. 

If this works, it should basically close #907, though there may be some wrinkles around `.html` extensions depending on how the app is consumed.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by tizu69** [comment]
what is the play for routes? Does each route get its own bundled code, or is there one bundled codebase that is then just put into all pages? I was gonna ask about dynamic routes, but I'm assuming they aren't possible with this either way I'm assuming.

**Comment by Rich-Harris** [comment]
One bundle. It doesn't impose any restrictions on what kind of app you can build, just means that the bundle size is correlated to app size

**Comment by dummdidumm** [comment]
This doesn't seem to work for me at all. It may work by chance if you prerender the entry point, but if you don't, or navigate anywhere in the app, then everything breaks:
- protocol is `file:`, so `pathname` contains the whole path to the file on disk (e.g. on windows something like `/C:/foo/bar/index.html`. That breaks all matching logic
- it's not self-contained yet: it contains `__vitePreload` entries, one for each node (page/layout/etc), which all try to load a JS bundle. That fails completely
- when something fails it tries to request `version.json` to see if a new version is available, this fails

**Comment by Rich-Harris** [comment]
It doesn't work after merging the hash based routing PR — I have some changes locally, and a test app that works perfectly

**Pull request merged**
