### PR TITLE
remove examples

### PR DESCRIPTION
**Pull request by Rich-Harris**
I think the `examples` folder has probably outlived its usefulness, and the one example left in there (the HN clone) should be moved to sveltejs/sites: https://github.com/sveltejs/sites/pull/272

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by benmccann** [comment]
Hmm. My initial reaction is that this would cause quite a bit of headache for me. I use the `hn.svelte.dev` example all the time when developing against Kit since it lives in the same repo. Perhaps I could use the `basics` app, but it lives a bit deeply nested within the repository and it doesn't really have an easily navigable homepage showing the various pieces of functionality that exist

**Comment by Rich-Harris** [comment]
The way I solve this problem is that I have a `sandbox` app next to the `kit` repo, with the following in its package.json:

```json
"scripts": {
  "dev": "node ../kit/packages/kit/src/cli.js dev",
  "build": "node ../kit/packages/kit/src/cli.js build",
  "package": "node ../kit/packages/kit/src/cli.js package",
  "preview": "node ../kit/packages/kit/src/cli.js preview",
  "lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. .",
  "format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
},
"pnpm": {
  "overrides": {
    "@sveltejs/kit": "../kit/packages/kit",
    "@sveltejs/adapter-auto": "../kit/packages/adapter-auto"
  }
}
```

This is better, because I don't need to worry about git

**Comment by Rich-Harris** [comment]
Created https://github.com/sveltejs/kit-sandbox, which makes local testing and development easier

**Comment by nhe23** [comment]
I think the contribution guide should probably also be updated. As this PR is already merged I'll create a new one for this.

**Comment by benmccann** [comment]
@nhe23 I sent a PR for that last night https://github.com/sveltejs/kit/pull/3425

**Comment by benmccann** [comment]
updated. thanks for the reminder!

**Pull request merged**
