### PR TITLE
breaking: use tsconfig for jsdoc projects, adjust svelte-check command

### PR DESCRIPTION
**Pull request by dummdidumm**
tsc will only recognize tsconfig files, so it's better to use that for projects where we want type-checking, be that through ts or jsdoc

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
Hmm. I swore I left a comment on this one yesterday, but I don't see it, so here I go again...

This will break `npx storybook@next init`. It needs to know whether it should add `.js` or `.ts` files to a project when setting up storybook. Right now it sets up the TypeScript version if `typescript` is in the `dependencies`/`devDependencies` and there's no `jsconfig.json` file. If you remove the `jsconfig.json` file then it will choose the TypeScript version even for JSDoc projects. Is there another way that Storybook should be choosing which project type to create?

**Comment by dummdidumm** [comment]
Mhm that's unfortunate - and reminds me, that in language tools we do something similar to know whether or not we should create TS or JS files for the route creation context menu. Damn ...

Could we check the number of JS vs TS files in the src directory and use TS if there are more TS files? Though if there are only Svelte files then we would need to look into the contents and see if there's a `lang="ts"` tag. And all this is probably not very performant - gah.

**Comment by benmccann** [comment]
Also, in Storybook they decide JS vs TS upfront in a generic way for all projects. It's not special logic for Svelte projects. Doing it generically makes the challenge a little harder

**Comment by benmccann** [comment]
Yes, they use the same logic for all projects

It looks like the TypeScript team thinks there's no reason you'd use tsc with a JS project: https://github.com/microsoft/TypeScript/issues/6671#issuecomment-176419305. I'm not sure exactly what the motivation here would be, so I don't know if that's right or there's just something they overlooked

**Comment by dummdidumm** [comment]
Yeah this, and the fact that VS Code first looks for any tsconfig before looking for a jsconfig (so a tsconfig higher up the tree would take precedence over a jsconfig) is the motivation for this PR.

Gah, this is stupid. Maybe it's worth reasking that question in the TS github issue tracker because JSDoc becomes more popular now.

**Comment by benmccann** [comment]
Ah, that sounds like a VS Code bug to me. I just filed a bug, so we'll see what they say: https://github.com/microsoft/vscode/issues/174492

**Pull request closed without merging**
