### PR TITLE
Serialize responses after body has been rendered

### LINKED ISSUE #591: Cloning of response leads to issues
This line:

https://github.com/sveltejs/kit/blob/8805c6daa6b11a46d2d373c3db890227b27e660d/packages/kit/src/runtime/server/page.js#L128

Causes issues in Node where it dies unexpectedly without any message on server. The Node high water mark limit is much smaller than browser. Can increase high water mark as workaround

There's multiple issues talking about this in `node-fetch` (e.g. [671](https://github.com/node-fetch/node-fetch/pull/671) and [151](https://github.com/node-fetch/node-fetch/issues/151)). Their recommendation is to stream and provide back pressure: https://github.com/node-fetch/node-fetch/issues/151#issuecomment-482777213

### PR DESCRIPTION
**Pull request by Rich-Harris**
I don't know if this fixes #591 because I still don't have a repro. Probably not. But I thought it might be worth a try

### CODE REVIEW

**Comment by Rich-Harris** [comment]
In fact, re-reading some of the linked issues i'm fairly certain this won't change anything. Given that we don't have any control over how the original response is consumed I'm not sure what we can really do here. Maybe instead of cloning the response, we return a proxy that lets us intercept the buffered value? This would also have the nice consequence that we'd know whether it was being consumed as text/json or as an arrayBuffer (which affects how/if we serialize it)

**Comment by benmccann** [comment]
It took me quite awhile to wrap my head around the problem (probably a couple hours to be honest). I did a write up over on the issue: https://github.com/sveltejs/kit/issues/591#issuecomment-805528014

I agree that I don't think this PR will help unfortunately. I don't think a proxy would work either because it's fundamentally the same as what we're doing now. In either case we'd be trying to read the stream into a buffer. If we reach the limit of that buffer then we're out of luck, so the approach is fundamentally incompatible with streaming. I believe the only way to do make it work is to process the response for rendering and serialize for hydration in parallel.

**Comment by stalkerg** [comment]
> serialize for hydration in parallel

It's not "parallel" but yes, if we will wait for our `await result.json()` and event loop switch execution to working with `await clone.text()` it will be solved but we lose stream anyway. 
In that case, much easier to do https://github.com/node-fetch/node-fetch/issues/533#issuecomment-429291408

**Comment by Rich-Harris** [comment]
closing in favour of #635

**Pull request closed without merging**
