### PR TITLE
Add link to http-status-codes

### LINKED ISSUE #1439: Add HTTP Status Codes ENUM
**Is your feature request related to a problem? Please describe.**
When giving proper error codes in response of endpoints/loads sometimes I have to google for the correct code, like PAYMENT_REQUIRED, BAD_REQUEST and some other things. Most Codes are well known, others not. To make it easier implementing a ENUM is a good solution.

**Describe the solution you'd like**
I'd like to get the Status Code ENUMs integrated in svelte kit. 

**Describe alternatives you've considered**
I started using https://www.npmjs.com/package/http-status-codes package.
```javascript
export async function post(request) {
    let ct = request.headers['content-type'] ?? '';
    if(ct !== 'application/json') {
        return {
            status: StatusCodes.BAD_REQUEST,
            body: ReasonPhrases.BAD_REQUEST
        };
    }
    let data = request.body;
    return {
        body: data
    }
}
```

A decision has to be made. 
1)
I can create a PR and add it to svelte kit. 
2)
A already written npm package could be put into the package.json.
3)
Leave it to the user like current state.

### PR DESCRIPTION
**Pull request by dummdidumm**
Closes #1439

Not all people might be familiar with status codes. Add a hint for them that they can use a library for that if they want to.

### CODE REVIEW

**Comment by Conduitry** [comment]
How treeshakable is this library? Do we want to just link people to MDN instead? Or Wikipedia even?

**Comment by dummdidumm** [comment]
I don't know. I had this in the back of my head, too. The idea of referencing a library was that in the referenced issue the problem was precisely that "I have to google this all the time", and using a library which provides autocompletion and meaningful constants would help. If we don't want to endorse a specific library or are too concerned with the additional kilobytes then I would just not merge this and close the issue. The docs already link to a list of status codes.

**Comment by benmccann** [comment]
It looks like tree shaking is a work-in-progress. There's an issue tracking it https://github.com/prettymuchbryce/http-status-codes/issues/55 and a PR that's been open since November https://github.com/prettymuchbryce/http-status-codes/pull/64 to further improve it. Version 2.1.5-beta.1 is a lot better than the latest stable version 2.1.4. No idea when 2.1.5 might be released though

**Comment by benmccann** [comment]
@Conduitry @dummdidumm any thoughts about whether we want to move forward with this PR?

**Comment by Conduitry** [comment]
I still don't think we want to be even semi-blessing a random third-party library for something like this, even a popular one - especially if we have doubts about the treeshakability of the library or about what direction it might be going in.

We're already linking to an MDN page on this in the docs. If someone wants more than that, they can get it themselves, along with whatever extra bytes it comes with, which would then be their responsibility.

**Comment by dummdidumm** [comment]
I'm indifferent. Feel free to close (and also the related issue with a short explanation why we won't do it).

**Pull request closed without merging**
