### PR TITLE
fix: outdated endpoint in todo example app

### LINKED ISSUE #1341: userid no longer available in request.context
**Describe the bug**
When creating a fresh new svelte kit app, following https://kit.svelte.dev/docs#introduction-getting-started, the TODO page is not working in the newly generated app. 

**Logs**

<details>
  <summary>stack trace (In page)</summary>
```ts
SyntaxError: Unexpected token T in JSON at position 0
```
</details>

<details>
  <summary>stack trace (terminal)</summary>
```shell
Cannot read property 'userid' of undefined
TypeError: Cannot read property 'userid' of undefined
    at get (/Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/src/routes/todos/index.json.ts:4:86)
    at render_route (file:///Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1220:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async render (file:///Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1476:10)
    at async Object.handle (/Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/src/hooks.ts:14:24)
    at async respond (file:///Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1450:10)
    at async fetch (file:///Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/node_modules/@sveltejs/kit/dist/ssr.js:703:24)
Unexpected token T in JSON at position 0
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///Users/I303733/Documents/GitHub/sandbox/sveltekit/my-app/node_modules/@sveltejs/kit/dist/ssr.js:762:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
</details>

**To Reproduce**
- svelte kit version: `next`
- svelte version: `^3.34.0`
- app template: SvelteKit demo app
- TypeScript: Yes
- ESLint: Yes
- Prettier: Yes

**Expected behavior**
A working TODO page.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```shell
  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.46 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.6.3 - ~/.npm/bin/npm
  Browsers:
    Brave Browser: 89.1.22.71
    Chrome: 90.0.4430.93
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.99 
    svelte: ^3.34.0 => 3.38.2 
    vite: ^2.1.0 => 2.2.4 
```

- Your browser: chrome/macos
- Your adapter: n/a
</details>

**Severity**
Just anonying for starters, easy to fix.

**Additional context**
- The typescript code seems outdated, using the `request.context.userid` in a few places. This seems to be renamed to `request.locals.userid`.
- the inline comment `// request.context.userid comes from src/hooks.js` could also be reworded as it's a typescript file in this context

### PR DESCRIPTION
**Pull request by ignatiusmb**
Fixes #1341 

Also add global interface to be passed in `RequestHandler` and fix lint errors.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thank you. I'm in two minds about the global `Locals` interface — people will certainly need to change it, but right now it's a little undiscoverable. I wander if we should instead export it from `src/lib/types.d.ts` and do

```ts
import type { Locals } from '$lib/types';
```

or something instead?

**Comment by Rich-Harris** [comment]
(The flip side of course is that you might well prefer to make it global in your app. Tough one.)

**Comment by ignatiusmb** [comment]
I was thinking the same, some of the considerations for making it global was (as mentioned) convenience and for an example on the possibility of adding global types/interfaces (since `import type { } from 'module'` is already demonstrated by `RequestHandler`).

Then again, having it exported from `src/lib/types.d.ts` is definitely more explicit and discoverable.

**Comment by Rich-Harris** [comment]
Perhaps the best-of-both-worlds solution is to use `$lib/types` but have a comment in there above the interface describing how to make it globally available if that's what the developer prefers?

**Comment by ignatiusmb** [comment]
I love it, that's genius. Done!

**Comment by Rich-Harris** [comment]
Perfect, thank you! One last thing I forgot to mention before — could you run `pnpx changeset` so that we can release a new version of `create-svelte`? (Would do it myself but I've had bad results editing PRs by working on branches of forks)

**Comment by Conduitry** [comment]
@Rich-Harris I've added a changeset.

**Pull request merged**
