### PR TITLE
[fix] make errors in Action less restrictive

### PR DESCRIPTION
**Pull request by dummdidumm**
Part of #6015

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by benmccann** [comment]
I think we added some type tests somewhere? Should we try to cover this with them?

**Comment by dummdidumm** [comment]
@Rich-Harris removed them 😄 they were related to the `JSONObject` thing which we removed entirely. Such a simple change doesn't warrant a type test IMO.

**Comment by benmccann** [comment]
Ah, that's why I didn't know where they were anymore :smile: All types are conceptually simple, but we're always making small mistakes where we get things wrong

Can the type really be `any`? I'd think it'd have to be something JSON serializable at least?

**Comment by dummdidumm** [comment]
It has to be, yes, but it's impossible to type "this expects a JSON type", see #5974 for more info

**Comment by benmccann** [comment]
I wonder if we should at least do something like:
```
export type JSONSerializable = any

...

errors: Record<string, JSONSerializable>
```

It doesn't change what's allowed but may help to document what's expected to clarify things for users

**Comment by Rich-Harris** [comment]
Tried it just now, it doesn't work. TypeScript replaces it with the underlying value

image

Screenshot 2022-08-18 at 12 34 54 PM

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
