### PR TITLE
Add depends to ServerLoadEvent

### LINKED ISSUE #6929: Type definition: `depends` missing in `Kit.ServerLoadEvent`
### Describe the bug

 `Kit.ServerLoadEvent` does not delare the `depends` function even though it exists on the option (and works)

See

https://github.com/sveltejs/kit/blob/7a7f84659013d9ad86e3f5d4a2ffe91a3354c55e/packages/kit/types/index.d.ts#L366-L371

https://github.com/sveltejs/kit/blob/7a7f84659013d9ad86e3f5d4a2ffe91a3354c55e/packages/kit/types/index.d.ts#L296-L308

It should declare depends just like `LoadEvent` does
https://github.com/sveltejs/kit/blob/7a7f84659013d9ad86e3f5d4a2ffe91a3354c55e/packages/kit/types/index.d.ts#L257

### Reproduction

https://stackblitz.com/edit/sveltekit-depends?file=src%2Froutes%2F%2Bpage.server.ts&terminal=dev

This example tries to use depends in a `PageServerLoad` function. Typescript shows an error:

image

However, the code works (click the "Reload data" button) - it's only a type error.

### Logs

_No response_

### System Info

```shell
(Stackblitz)


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.76 
    @sveltejs/kit: next => 1.0.0-next.490 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.0.4 => 3.1.3
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aloker**
Fixes #6929

I added a test route to apps/basics (/invalidate) that uses depends in the server side load function. Without the change `pnpm check` fails, with it it succeeds. There are automatic tests for this PR as I'm not sure how to test types.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by aloker** [comment]
Dang, that 's a duplicate of #6934 
Oh well, pick the one you like :D

**Comment by dummdidumm** [comment]
Thank you! Regarding tests, could you move the test to `load/invalidation/depends`? That way the related features are grouped better (`load/invalidation` should already exist). The test goes into `test/apps/basics/client.test.js`, search for `test.describe.serial('Invalidation'` and add your test to the end of it.

**Comment by aloker** [comment]
I added a couple of tests and moved the test route. Let me know if you need more from me.

**Review by dummdidumm — APPROVED** [review]
Awesome, thank you!
I tweaked the tests further, this is good to merge from my side now.

**Pull request merged**
