### PR TITLE
chore: fix path to app script on windows

### PR DESCRIPTION
**Pull request by gtm-nayan**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

As noted on discord, in dev mode the hydration script inserted into pages is rendered as
`import("./D:\\some\\path\\kit\\sites\\kit.svelte.dev\\.svelte-kit/generated/client/app.js")`

which works for our current intents and purposes, hence why this is marked as a chore instead of a fix, but it just looks plain weird and might confuse users.

This PR makes it so that these paths have correct facing slashes and the /@fs/ prefix on both Linux and Windows.

### CODE REVIEW

**Comment by gtm-nayan** [comment]
oops forgot to take this out of draft

**Comment by Conduitry** [comment]
What effect does this have on end-users? I'd argue that, in general, `chore:` PRs shouldn't have changesets. Either it's a fix for a user-visible bug, or it's an internal refactoring that we don't need to tell users about and that we don't want Changesets to prompt us to cut a release for.

**Comment by gtm-nayan** [comment]
It was bordering between a fix and a chore for me. Both chrome and firefox find the file somehow even with the dot and the slashes so marked it as a chore instead. Should I remove the changeset then?

**Comment by Rich-Harris** [comment]
i think it's okay to err on the side of too many changesets — for stuff like this which _does_ have user-observable changes (albeit changes they hopefully won't notice) there's no harm in being able to pin down the version where it changed in the unlikely eventuality that it causes problems for someone

also i'm about to cut a release so it doesn't matter too much

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
