### PR TITLE
feat: add `cookies.getAll`

### LINKED ISSUE #9263: `cookies.getAll()`
### Describe the problem

The supabase auth helpers store the session inside cookies to be able to authenticate on the server.
This session can get pretty big and therefore exceeds the cookies size limit.
To overcome this problem we are going to implement cookie chunking.

If you want to store data inside a cookie that exceeds the cookie size limit you have to either implement session id´s or cookie chunking ([next auth](https://next-auth.js.org/configuration/options#cookies) does this).

### Describe the proposed solution

add `cookies.getAll()`
the return type could be an iterator so something like this is possible:

```ts
for (const { name, value } of cookies.getAll()) {
  if (name.startsWith(cookieName)) {
     ...
   }
}
```

### Alternatives considered

Use a "workaround" like this:

```ts
export function getChunkedCookie(cookies: Cookies, name: string, opts?: CookieParseOptions) {
	const value = cookies.get(name);
	if (value) {
		return value;
	}

	const chunks: string[] = [];

	for (let i = 0; ; i++) {
		const cookieName = `${name}.${i}`;
		const chunk = cookies.get(cookieName, opts);

		if (chunk) {
			chunks.push(chunk);
		} else {
			break;
		}
	}
	return chunks.length ? chunks.join('') : undefined;
}
```

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by msonnberger**
closes #9263 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
Thank you! Couple of changes I think we need — this logic needs to be reflected (i.e. we only want to include cookies with a valid `path` etc — if `cookies.get('foo')` wouldn't return a value, then it shouldn't be included in `getAll`):

https://github.com/sveltejs/kit/blob/90fdfdb89263c6938b774478a741a51bdf41e0a3/packages/kit/src/runtime/server/cookie.js#L75-L76

Also, we need to consider existing cookies, not just new ones:

https://github.com/sveltejs/kit/blob/90fdfdb89263c6938b774478a741a51bdf41e0a3/packages/kit/src/runtime/server/cookie.js#L82-L83

New cookies should take priority though, if `cookies.set('foo', ...)` was called and there was already a `foo` cookie in the request header.

**Comment by msonnberger** [comment]
> Thank you! Couple of changes I think we need — this logic needs to be reflected (i.e. we only want to include cookies with a valid `path` etc — if `cookies.get('foo')` wouldn't return a value, then it shouldn't be included in `getAll`):

sure, added the checks for domain and path 👍 
> Also, we need to consider existing cookies, not just new ones:
> New cookies should take priority though, if `cookies.set('foo', ...)` was called and there was already a `foo` cookie in the request header.

should already work, no? at first first we get all existing cookies with `parse`, then add all new ones and (potentially) override existing keys.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Ah whoops, I missed that line at the beginning! Thank you

**Comment by david-plugge** [comment]
Thanks alot!

**Pull request merged**
