### PR TITLE
feat: add `OPTIONS` server method

### LINKED ISSUE #5193: Method Options - HTTP
### Describe the problem

I didn't see the Options method for building APIs. Is it possible to have it?

### Describe the proposed solution

It is important to query the server capacity and the Options method, it provides for us

### Alternatives considered

_No response_

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by s3812497**
closes #5193

Continues from the work of #6030

* Adds the `OPTIONS` method as valid `+server.js` export.
* ~Disables Vite config options [`preview.cors`](https://vitejs.dev/config/preview-options.html#preview-cors) and [`server.cors`](https://vitejs.dev/config/server-options.html#server-cors) which were intercepting all `OPTIONS` http requests.~
* Passes through Vite's CORS middleware during `dev` and `preview`

This delegates the responsibility of turning off Vite's CORS middleware to the user when vite's injected headers interfere with development of OPTIONS endpoints.
```js
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  server: {
    cors: false // disable cors for vite dev
  },
  preview: {
    cors: false // disable cors for vite preview
  }
});
```

#### TODO
- [ ] docs

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I sorta feel like `RequestHandler` is the wrong API for `OPTIONS` — it feels like something that should mostly be handled by the framework, which already knows which methods are allowed for which route.

Perhaps the default behaviour should be to return a 204 response with `allow` and (if `access-control-request-method` is sent, `access-control-allow-methods`), and we expose some way to control `access-control-allow-origin` and `access-control-max-age`? (There's also `access-control-allow-headers` but I don't really understand what it's for.)

I'm not 100% sure what that looks like but it feels like exporting `export const OPTIONS` from every API route is a lot of unnecessary manual work.

**Comment by Conduitry** [comment]
`access-control-allow-headers` specifies which headers the sender is allowed to send. (It corresponds with the `access-control-request-headers` header in the `OPTIONS` call.) If the browser deems that this CORS request requires a preflight request (whether it's because it's not a `GET`, or it include authentication, or it includes custom headers), it will include `access-control-request-headers` in the request with all of the headers that would be sent in the real request (including default things like `content-type`) and it expects the response to include them in the `access-control-allow-headers` if they are to be allowed in the actual request.

**Comment by Rich-Harris** [comment]
but why? why wouldn't the server just disregard any headers it wasn't interested in?

**Comment by Conduitry** [comment]
I think it's not just 'would the server be generally interested in these headers?', it's also 'would the server want to trust these headers from this origin?'. CORS wants everything that could potentially be abused to be explicitly opt-in by every server, and not assume that it will filter out things that might be harmful.

I've long since stopped trying to second guess the CORS design. But if we want to support it beyond 'idk, you need to respond to the requests in your `handle` hook' then we'll have to just deal with the spec as it was written. and it was written to ask 'can this origin send a request with this method including these headers to you?' and the server can say what it wants to allow and how long the client is allowed to cache this information.

For this reason, I'd be wary about doing anything fancier than saying the app needs to handle this in its `handle` hook, and very wary about doing anything fancier than saying the app needs an `OPTIONS` export from a particular `+server.js` file.

**Comment by s3812497** [comment]
Would a combination of CORS helper methods inside an `OPTIONS` export be preferable to using `setHeaders`?

Perhaps there can also be a simpler method of setting CORS options across the board in addition to the manual control of an `OPTIONS` export.

Or would adding a recipe to the docs for setting CORS in `+hooks.server.js` be sufficient?
Something like the answer from https://github.com/sveltejs/kit/issues/5193#issuecomment-1383161029 ?

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
> For this reason, I'd be wary about doing anything fancier than saying the app needs to handle this in its `handle` hook, and very wary about doing anything fancier than saying the app needs an `OPTIONS` export from a particular `+server.js` file.

Fair enough — that's certainly the path of least resistance.

> Would a combination of CORS helper methods inside an `OPTIONS` export be preferable to using `setHeaders`?

Very possibly. Though I think it'd be worth shipping this and seeing if people ask for those helpers, rather than blocking on it. I've approved this PR, though since it was marked 'draft' I haven't merged it yet in case there was anything else we wanted to do here first

**Comment by s3812497** [comment]
Is this CORS fix https://github.com/sveltejs/kit/pull/7688 still needed for static assets during `dev` and `preview`?
I'm wondering if automatically appending this header during dev would be misleading for those developing their own OPTIONS endpoint.

Would it be better to delegate the responsibility to vite's `--cors` CLI option?

**Comment by s3812497** [comment]
Would it be beneficial to make a note in the docs about sveltekit's CORS behaviour during `vite dev` and `vite preview`?

For example a blockquote that mentions vite automatically appending the `access-control-allow-origin` and `access-control-allow-methods` headers during these modes?

I ask because I wonder if this default behaviour could be misleading for developers creating their own OPTIONS endpoints

**Pull request merged**
