### PR TITLE
use import-meta-resolve to resolve vite-imagetools

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes resolution of `vite-imagetools` — see https://github.com/sveltejs/kit/pull/9787/files#r1183860328

### CODE REVIEW

**Comment by Rich-Harris** [comment]
ugh, typechecking failures due to incompatible configs. not sure how to resolve beyond forking `import-meta-resolve`

**Comment by dummdidumm** [comment]
Can't we also use the built-in `createRequire` for this?

**Comment by Rich-Harris** [comment]
No, `vite-imagetools` doesn't expose CommonJS

**Comment by dummdidumm** [comment]
We could also see if version 2 doesn't have this problem, or do a hack `try{ createRequire(..).resolve() } catch (e) { infer path from error message because it's in there } `

**Pull request closed without merging**
