### PR TITLE
chore: improve playwright test reporting on github ci

### PR DESCRIPTION
**Pull request by dominikg**
let's see if we can get some useful information on ci flakiness and test results into github ui

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dominikg** [comment]
damnit, there is a prefix interfering with the message format that gh parses https://github.com/sveltejs/kit/actions/runs/3465238448/jobs/5787732669#step:8:324

**Comment by benmccann** [comment]
how do you envision this being used? it doesn't give us anything we can use to debug. we've already got traces and screenshots for the ones that fail repeatedly, which is a lot more actionable and are the ones that are most annoying anyway

**Comment by benmccann** [comment]
oh, cool. I didn't realize this will show up in the github UI. I thought it'd get buried in a log somewhere. do you have an example of how this will be displayed?

**Comment by dominikg** [comment]
apologies for the screenshot from google image search but wasn't able to find a run that has one quickly 
image

regarding the prefix: it seems to be originating from turbo and even with `process.stdout.write` you can't avoid it.

**Comment by dominikg** [comment]
https://github.com/vercel/turbo/issues/1363

**Comment by dominikg** [comment]
marking as draft, using test in packages/kit directly to see the potential output without turbo interfering

**Comment by dominikg** [comment]
https://github.com/sveltejs/kit/actions/runs/3465678222

looks like playwrights `github` reporter is a bit noisy due to us running it for multiple apps multiple times, but the flaky reporting works :partying_face:

**Comment by dominikg** [comment]
and here's a run without the noise https://github.com/sveltejs/kit/actions/runs/3465862956

**Comment by benmccann** [comment]
wow, that's awesome!

**Review by benmccann — APPROVED** [review]

**Pull request merged**
