### PR TITLE
fix Counter.svelte location in create-svelte template

### PR DESCRIPTION
**Pull request by Conduitry**
This should have been moved along with the other `$lib` stuff in #511. Right now a fresh copy of the template fails because it tries to import from `$lib/Counter.svelte` but the component isn't there.

### CODE REVIEW

**Comment by Conduitry** [comment]
This will also be an opportunity to see whether the automated `create-svelte` publishes work now.

**Comment by melMass** [comment]
Shouldn't this be done for the Skeleton template as well?

**Comment by Conduitry** [comment]
> Shouldn't this be done for the Skeleton template as well?

There's no `Counter.svelte` in the skeleton template.

**Comment by melMass** [comment]
> There's no `Counter.svelte` in the skeleton template.

I was referring to using `$lib` but you are right there is no components at all

**Pull request merged**
