### PR TITLE
[fix] don't log warning if root is configured

### PR DESCRIPTION
**Pull request by benmccann**
`root` is no longer set since https://github.com/sveltejs/kit/pull/5303. This logs an unnecessary warning when using Storybook

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Can you elaborate? As far as I can tell, setting `root` just makes everything break. What are the situations in which it makes sense to be configured?

**Comment by benmccann** [comment]
Storybook sets root to the expected directory. SvelteKit doesn't check what the value of the setting is and just prints an error if it's configured at all eventhough there's no actual issue. And SvelteKit doesn't actually set the value so the error message is also incorrect in saying that SvelteKit is taking control of it.

**Comment by Rich-Harris** [comment]
What is 'the expected directory'? I'm just very unclear on how it could work. It feels like SvelteKit probably _should_ set the value to the project root and/or print an error if it's set to something else

**Comment by Rich-Harris** [comment]
Ah. So I think what we should do is error if `root` is explicitly set to something _other_ than the cwd

**Comment by benmccann** [comment]
Ok. Updated the PR to do that

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
