### PR TITLE
create-svelte: include globals.d.ts in tsconfig

### PR DESCRIPTION
**Pull request by GrygrFlzr**
Apparently `globals.d.ts` was being ignored entirely. Whoops.

### CODE REVIEW

**Comment by benmccann** [comment]
Perhaps we should put it in `src` for better organization and include `src/**/*.d.ts`?

**Comment by dummdidumm** [comment]
+1 on putting it inside src. +1 on adding `src/**/*.d.ts`. Name - I don't care 😄

**Comment by orta** [comment]
If I recall next js puts the d.ts in src, seems pretty reasonable to think of it as a source file to me

**Comment by GrygrFlzr** [comment]
Moved to `/src/global.d.ts` as recommended above.

**Pull request merged**
