### PR TITLE
only cache response if response has cache-control header

### PR DESCRIPTION
**Pull request by fjdumont**
This PR aims to implement more defensive caching behavior as proposed in #9884.

CC @0x221A

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thank you. I'm very surprised that the Cloudflare cache is storing responses without a `cache-control` header, since this seems like it would be a very frequent source of serious bugs. Have you observed responses being incorrectly cached, or is this more of a just-in-case thing?

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Yikes, that's... scary. Thank you for the fix!

**Comment by 0x221A** [comment]
I don't know how Cloudflare cache responses, but the problem appears in a previous PR by @fjdumont, the code let worktop `Cache.save` function decide whether to cache the responses or not. Everything work just fine except that the "is this cacheable" logic failed to validate empty string of `cache-control` header and let it cache by default. See here https://github.com/lukeed/worktop/blob/master/src/cache.ts#L37-L38

**Comment by 0x221A** [comment]
If you are wondering why this problem never happened before. It is because before this there is an if condition to check the empty cc header.

**Comment by happysalada** [comment]
hey I just ran into this problem with this PR, cloudflare caching pages that have been updated.
How do you bust cloudflare's cache ?

**Comment by figuerom16** [comment]
> hey I just ran into this problem with this PR, cloudflare caching pages that have been updated. How do you bust cloudflare's cache ?

The newest cloudflare adapter 2.2.4 fixed this, but before I was setting my Response with:
`setHeaders({ 'cache-control':'no-store', 'vary':'cookie' })`

**Comment by happysalada** [comment]
Hey thanks a lot !

Actually it turns out it was a workers outage that cause the files to not he updated for a couple of hours.
 Thanks again though !

**Pull request merged**
