### PR TITLE
fix(template): typehint default config file

### PR DESCRIPTION
**Pull request by lukeed**
### Before submitting the PR, please make sure you do the following
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by benmccann** [comment]
Is this for VS Code support? Seems like a bug there if this is required, but I'm fine with changing it here to workaround it anyway. It looks like we already do this in [the default template](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/svelte.config.cjs)

**Comment by lukeed** [comment]
Yeah, it's the only correct way to actually apply JSDoc typehints – has to be applied to a variable/function

**Review by benmccann — APPROVED** [review]
You'll have to add a changeset with `pnpx changeset`

**Comment by Rich-Harris** [comment]
Does this become a non-issue when we switch to ESM configs? Can you type an `export default`?

**Comment by lukeed** [comment]
Nope, still variables and functions only

**Comment by lukeed** [comment]
There is an `@exports` directive but I've never got that to work. Even then, due to the age, it was probably CommonJS-specific

**Comment by Rich-Harris** [comment]
actually just realised that this PR won't change anything, the edited file gets replaced by either [this one](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/shared/-typescript/svelte.config.cjs) or [this one](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/shared/%2Btypescript/svelte.config.cjs). 

But now that I look at those files, I see this —

image

— in other words I'm pretty sure this only applies to ESM? Annoying that it fails with `export default` but works fine with `export const`, feels like something that could be fixed in TS. (Better still, let us type modules!)

**Pull request merged**
