### PR TITLE
Fix $error in examples

### PR DESCRIPTION
**Pull request by snird**
This PR: https://github.com/sveltejs/kit/pull/1021 but applied to the examples, to make them functional again.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thank you, but it looks like this completely changes the design and functionality of these error pages rather than just fixing the props. Mind reverting these changes and just adding the necessary `load` function?

**Comment by snird** [comment]
Done @Rich-Harris

**Comment by Rich-Harris** [comment]
Thank you, can you reinstate the deleted newlines?

**Comment by snird** [comment]
finally, really done.

**Comment by Rich-Harris** [comment]
thank you!

**Pull request merged**
