### PR TITLE
fix: correct images cache key to avoid collisions when images have same name

### LINKED ISSUE #11561: @sveltejs/enhanced-img shows the same image if file name is the same
### Describe the bug

If we place two images in two different routes and name the files the same, `<enhanced:img src="./image.png" />` on every page will show us the same image.

### Reproduction

Assume structure:
```
/routes/dir/one/+page.svelte
/routes/dir/one/image.png
/routes/dir/two/+page.svelte
/routes/dir/two/image.png
```

**one/image.png** and **two/image.png** are two different images, different files.
In every +page.svelte we place:
`<enhanced:img src="./image.png" />`

Of course, every enhanced:img has its own image file, but something goes wrong and both pages show the same image  The links are the same ( /@imagetools/080965fcd54cbb8c8fbb15c51a124bb77af1bad3 ). I suppose it generates hash from raw `src` and does not take into account real image path.

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 33.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.1.2
  npmPackages:
    @sveltejs/adapter-node: ^2.0.2 => 2.0.2 
    @sveltejs/enhanced-img: ^0.1.7 => 0.1.7 
    @sveltejs/kit: ^2.1.0 => 2.1.0 
    @sveltejs/vite-plugin-svelte: ^3.0.1 => 3.0.1 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^5.0.11 => 5.0.11
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by IAkumaI**
Fixes https://github.com/sveltejs/kit/issues/11561
Images cache keys are wrong for relative paths

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [ x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by benmccann** [comment]
As a heads up, I've updated the PR description to say "Fixes https://github.com/sveltejs/kit/issues/11561", which links the PR and issue together in GitHub

**Comment by benmccann** [comment]
I noticed you sent this PR from your `main` branch. That's fine for a single PR, but makes it difficult to send additional PRs in the future. You're usually best off making a new branch when you want to send a PR

**Review by benmccann — APPROVED** [review]
thank you!!

**Comment by IAkumaI** [comment]
> I noticed you sent this PR from your `main` branch. That's fine for a single PR, but makes it difficult to send additional PRs in the future. You're usually best off making a new branch when you want to send a PR

Got it, thanks!

**Pull request merged**
