### PR TITLE
chore: bump vite and devalue

### LINKED ISSUE #6910: Double execution of the page on the server side, at server startup, when the page is open in a web browser
### Describe the bug

Double execution of the page on the server side, at server startup, when the page is open in a web browser.

### Reproduction

1. use the repo https://github.com/lukaszpolowczyk/podwojnelogi
2. install
3. fire up the server
4. open the page in a web browser
5. stop the server
6. clean the terminal
7. fire up the server again

You will see a double log from `src/routes/+page.svelte` in the terminal:

```
test page.svelte
test page.svelte
```

When the page is not open in the browser, the log is only one, when firing up the server

Why does it work this way? Is this how it should work?

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 6.52 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.109
    Firefox: 102.2.0esr
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.76 
    @sveltejs/kit: next => 1.0.0-next.489 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

annoyance

### Additional Information

_No response_

### LINKED ISSUE #7218: "Not found: /" error in dev mode when you have no root route
### Describe the bug

This is pretty minor, but if you're using adapter-static and building a subtree that you'll be shoehorning into some other legacy app, you might not need the root route `/`. If you don't have one, you get this error every time you restart the dev server and you have a browser window open:

```
jpsimons@Johns-iMac sveltekit_no_root_path % npm run dev

> sveltekit-no-root-path@0.0.1 dev
> vite dev


  VITE v3.1.7  ready in 242 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
Not found: /
Error: Not found: /
    at resolve (file:///Users/jpsimons/dev/sveltekit_no_root_path/node_modules/@sveltejs/kit/src/runtime/server/index.js:259:13)
    at resolve (file:///Users/jpsimons/dev/sveltekit_no_root_path/node_modules/@sveltejs/kit/src/runtime/server/index.js:290:5)
    at Object.handle (file:///Users/jpsimons/dev/sveltekit_no_root_path/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)
    at respond (file:///Users/jpsimons/dev/sveltekit_no_root_path/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:40)
    at async file:///Users/jpsimons/dev/sveltekit_no_root_path/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
^C
```

Not sure why anything would be trying to load /, my browser is sitting on the route that exists, i.e. `http://localhost:5173/blah`

### Reproduction

Repro example at https://github.com/johnnysprinkles/sveltekit_no_root_path/commits/main It's just the stock skeleton app with the only route moved down a folder.

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 78.38 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Firefox: 105.0.1
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.81
    @sveltejs/kit: next => 1.0.0-next.512
    svelte: ^3.44.0 => 3.51.0
    vite: ^3.1.0 => 3.1.7
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
Renovate wants to bump playwright so creating a separate PR

fixes #6910
fixes #7218 

cc @tcc-sejohnson tests for #9911 will have to be updated, devalue doesn't escape forward slashes and `>` from 4.3.1

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by benmccann — COMMENTED** [review]
I think we probably need a changelog for kit bumping the prod dependency on devalue

**Comment by Rich-Harris** [comment]
why? it shouldn't affect users, it's just a speed boost, no?

**Comment by benmccann** [comment]
> why? it shouldn't affect users, it's just a speed boost, no?

ok, yeah, fair enough. I'm fine to skip it

**Comment by Rich-Harris** [comment]
no idea why seemingly unrelated tests started failing on this PR the moment i touched it

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
