### PR TITLE
format with spaces

### PR DESCRIPTION
**Pull request by vhscom**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

This is a very small opinionated change which will save a lot of developer time and improve display and readability of code when diffing with graphical display tools such as github and gitea. Will there be bikeshedding? Perhaps. Are spaces overwhelmingly the norm for web projects? Yes, unless you're working on Golang.

### CODE REVIEW

**Comment by Conduitry** [comment]
Absolutely not.

**Comment by vhscom** [comment]
Fair enough.

**Comment by vhscom** [comment]
TIL digging into this more I learned `.editorconfig` files are picked up by GitHub and Gitea (and others, I presume) and [may be used](https://github.com/go-gitea/gitea/issues/9071) to address the readability concerns in online compare/diff views.

**Comment by vhscom** [comment]
Digging into this more I learned `.editorconfig` files are picked up by GitHub and Gitea (and others, I presume) and [may be used](https://github.com/go-gitea/gitea/issues/9071) to address the readability concerns in online compare/diff views. Thanks for the nudge @Conduitry.

**Comment by vhscom** [comment]
Digging into this more I learned `.editorconfig` files are picked up by GitHub and Gitea (and others, I presume) and [may be used](https://github.com/go-gitea/gitea/issues/9071#issuecomment-1016028160) to address the readability concerns in online compare/diff views. Thanks for the nudge @Conduitry.

**Pull request closed without merging**
