### PR TITLE
[fix] handle missing server file for an action request

### LINKED ISSUE #7957: form `enhance` incorrectly parses response text as JSON
### Describe the bug

The form `enhance` returns an unhelpful error message whenever the server returns an error response. This is because it tries to parse the response as JSON while SvelteKit's error responses are text only. As a result, the original error message is obscured behind the failed JSON parsing.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-qg7vng?file=src%2Froutes%2F%2Bpage.svelte&terminal=dev

### Logs

```Shell
500
Unexpected token 'C', "Cross-site"... is not valid JSON
SyntaxError: Unexpected token 'C', "Cross-site"... is not valid JSON
    at JSON.parse (<anonymous>)
    at deserialize (https://sveltejskittemplatedefaultqg7vng-gfaq--5173.local-credentialless.webcontainer.io/node_modules/@sveltejs/kit/src/runtime/app/forms.js?v=32fe10c2:21:22)
    at HTMLFormElement.handle_submit (https://sveltejskittemplatedefaultqg7vng-gfaq--5173.local-credentialless.webcontainer.io/node_modules/@sveltejs/kit/src/runtime/app/forms.js?v=32fe10c2:106:13)
untitled page
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.571 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

### Additional Information

_No response_

### LINKED ISSUE #7965: Unhandled form action when `+page.server` does not exist
### Describe the bug

> The offending code is inside `actions.js` and `runtime/server/page/index.js` (line 41, the "is action request but no `+page.server.js` exists" case is unhandled).

_Originally posted by @dummdidumm in https://github.com/sveltejs/kit/issues/7958#issuecomment-1339110939_

A fetch request to a form action is being handled incorrectly when the server file does not exist . This returns a `200` response with the HTML of the page itself. Ideally, a `405` no action exists error would be returned.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-bk2z1s?file=svelte.config.js,src%2Froutes%2F%2Bpage.svelte

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.571 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by s3812497**
fixes #7965 
fixes #7957 

* Returns a `405` response for an action request when no server file exists for a page.
* Adds a JSON body for the "cross-origin POST" and "no actions exist" error responses.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dummdidumm** [comment]
Thank you - I'm not sure if this is the right fix though. Looking at the linked issue, that error response should have been JSON instead - the "Accept" header clearly states that. So we should fix this on the server instead. Are there other situations besides the reproducible in the issue where you experienced this bug?

**Comment by dummdidumm** [comment]
Interesting - thanks for investigating! The Accept header should be honored in these cases, so in the progressive enhancement case where JSON is expected for the response, it should be sent as such.
The offending code is inside `actions.js` and `runtime/server/page/index.js` (line 41, the "is action request but no `+page.server.js` exists" case is unhandled).

**Comment by s3812497** [comment]
Thanks for the guidance @dummdidumm ! I've added handling for a missing server file using the same "405 POST method not allowed. No actions exist for this page" response. Hopefully I've implemented this correctly.

**Comment by dummdidumm** [comment]
Thank you! Ok so this brings up another design question: Right now the response is still not JSONified, which it should be, but if we do that, it ideally should honor the `App.Error` interface. So this should probably use `handle_error_and_jsonify` and return a JSON response from that (similar to what's happeneing further below in that method).

**Comment by s3812497** [comment]
Yup, looks much better now. What about the plain text response from the CSRF check?
Should a JSON response also be made available to prevent the parsing error?
```js
	if (options.csrf.check_origin) {
		const forbidden =
			request.method === 'POST' &&
			request.headers.get('origin') !== url.origin &&
			is_form_content_type(request);

		if (forbidden) {
			const csrf_error = error(403, `Cross-site ${request.method} form submissions are forbidden`);
			// respond with json
			if (request.headers.get('accept') === 'application/json') {
				return json(csrf_error.body, { status: csrf_error.status });
			}
			return new Response(csrf_error.body.message, { status: csrf_error.status });
		}
	}
```

**Comment by dummdidumm** [comment]
yeah that makes sense 👍

**Review by dummdidumm — APPROVED** [review]
Thank you!

**Pull request merged**
