### PR TITLE
chore: generate types postinstall

### PR DESCRIPTION
**Pull request by geoffrich**
~The contributing docs left out the steps needed to generate the types needed by the doc site, see https://github.com/sveltejs/kit/discussions/10298. Failing to run `pnpm check` meant that `pnpm prepare` failed when setting up kit.svelte.dev locally.~

edit: instead of instructing the user to run `pnpm check`, this PR now generates types automatically after running `pnpm install`

### CODE REVIEW

**Comment by benmccann** [comment]
yeah, this has been a bit annoying. I wonder if there are some setup changes we could make to make this easier. e.g. it looks like it's setup on `postInstall`, but I'm not sure it's always running. maybe the root project needs `"postInstall": "pnpm -r postInstall"` or something to make sure it's running. it seems like it'd be nice to run it in some manner other than `pnpm check` in either case to make it complete more quickly as we really just want to generate the types and not invoke type checking

**Comment by dummdidumm** [comment]
Instead of polluting the package's `package.json`s with such scripts I would be in favor of adding a `postinstall` script to the root `package.json`.

**Comment by geoffrich** [comment]
The postinstall was running, it just wasn't generated the types. I added a postinstall to the root package.json to run the `generate:types` script inside the `kit` package. Reverting the doc changes since those shouldn't be necessary anymore.

Though now it seems those have broken the Windows tests - any ideas? Is it a file path issue?

>  . postinstall: packages/kit generate:types: Error: ENOENT: no such file or directory, open 'D:\a\kit\kit\packages\kit\src\runtime\control.d.ts'

**Comment by dummdidumm** [comment]
Seems like that for some reason `dts-buddy` thinks that there's a file `control.d.ts`, but there's only `control.js` - why this happens eludes me, but I bet it's something about path separators

**Review by benmccann — APPROVED** [review]

**Pull request merged**
