### PR TITLE
fix: update page store when URL hash is changed from the address bar

### LINKED ISSUE #9374: `$page.url.hash` is not updated.
### Describe the bug

When the URL hash value is changed using the address bar, the `$page` store is not updated.

### Reproduction

Checked on Chrome, Firefox, and Safari. Reference 'System Info' for version numbers.

```svelte
<script>
  import { page } from '$app/stores';
  
  $: console.log($page.url.hash);
</script>

<svelte:window
  on:hashchange={() => {
    console.log($page.url.hash, 'store');
    console.log(window.location.hash, 'location')
  }}
/>

<a href="#1">#1</a>
```

1. Load the page
2. Click the anchor element.
3. Replace `#1` with `#2` in the address bar.
4. Check the console.

```html
<!-- Anchor is clicked. Hash is now #1 -->
#1
#1 store
#1 location

<!-- URL is updated. Hash is now #2 -->
#1 store
#2 location
```

### Logs

_No response_

### System Info

```Shell
System:
  OS: macOS 13.2.1
  CPU: (8) arm64 Apple M1
  Memory: 78.86 MB / 8.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
  npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
Browsers:
  Chrome: 110.0.5481.177
  Firefox: 110.0
  Safari: 16.3
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
  @sveltejs/kit: ^1.5.0 => 1.11.0 
  svelte: ^3.54.0 => 3.55.1 
  vite: ^4.0.0 => 4.1.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by plbstl**
Fixes #9374
Closes #9548

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:

- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/pull/9548 looks to be addressing the same issue

**Comment by plbstl** [comment]
The draft went stale. I figured out how to resolve the issue and implement the necessary tests

**Comment by dummdidumm** [comment]
Reading [this section on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#the_history_stack) it says: "Browsers tend to handle the popstate event differently on page load. Chrome (prior to v34) and Safari always emit a popstate event on page load, but Firefox doesn't."

--> Could someone who has access to Safari check whether or not this change results in an unwanted update of the page store on initial page load? Because that shouldn't happen, and if it does, we need some additional boolean I guess to not fire on first page load.

As for the TODO in the code: I think it should stay as is.

**Comment by s3812497** [comment]
> Safari always emit a popstate event on page load

This doesn't happen for me on MacOS Safari 17.

**Comment by plbstl** [comment]
> Could someone who has access to Safari check whether or not this change results in an unwanted update of the page store on initial page load?

I just checked with Safari on iOS and MacOS, there is no unwanted update of the page store on initial page load.

> Safari always emit a popstate event on page load

This doesn't happen to me on Safari 16.5.1 (iOS and MacOS).

> As for the TODO in the code: I think doing it in the else block is correct, you can remove that comment.

Okay, thank you for the feedback.

**Review by dummdidumm — APPROVED** [review]
Thank you!

**Pull request merged**
