### PR TITLE
Revert "Use ESM eslint config files"

### PR DESCRIPTION
**Pull request by oekazuma**
Reverts sveltejs/kit#5263

Unfortunately, this does not seem to work.

Result of running `pnpm lint`

```shell
Oops! Something went wrong! :(

ESLint: 8.18.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Development/my-app/.eslintrc.js from /Users/Development/my-app/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of .eslintrc.js in /Users/Development/my-app/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
```

### CODE REVIEW

**Comment by Conduitry** [comment]
You'd need to create a new changeset, not delete the old one, in order for this to be released properly after it's merged.

That said, can you be more specific about "does not seem to work"?

**Comment by oekazuma** [comment]
I added a changeset.

The following is the result of creating a new app with `npm create svelte my-app` and running `pnpm lint`.

```shell
Oops! Something went wrong! :(

ESLint: 8.18.0

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Development/my-app/.eslintrc.js from /Users/Development/my-app/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of .eslintrc.js in /Users/Development/my-app/node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
```

**Comment by avarun42** [comment]
Can confirm and replicate. The docs also state:
>JavaScript (ESM) - use .eslintrc.cjs when running ESLint in JavaScript packages that specify "type":"module" in their package.json. Note that ESLint does not support ESM configuration at this time.

**Review by benmccann — APPROVED** [review]
oh goodness. I swear I tested this, but you're right and I'm seeing the same behavior. I'm not sure what happened

thanks for sending the fix

**Pull request merged**
