### PR TITLE
[chore] more packaging tests fortification

### PR DESCRIPTION
**Pull request by ignatiusmb**
In working towards packaging issues and preparing some more tests for the uncovered settings, I found (another) hidden regressions within the tests itself (most likely from one of my early PRs back then when setting up the infrastructure, oops). This PR will

- [x] refactor `walk` into `utils/filesystem`
- [x] ~~add files include/exclude test suite~~ delegated to another PR
- [x] fix regression of nested folders equality testing
- [x] rename test folders to describe better what is being tested
- [x] print out more descriptive assertion error messages
- [x] remove unnecessary individual suites that can be merged into one test (now lives under the "standard javascript package" test suite)

~~Hopefully I'll be able to finish the checklist in the next couple of hours. Although, there might be a bug for the files include/exclude as well, so I might probably open a separate PR to add the tests and fix it if that's the case.~~

Opening another PR for the files include/exclude after this one's merged.

### CODE REVIEW

**Comment by ignatiusmb** [comment]
Ugh, windows specific problem again, no wonder it keeps failing in my machine.

The new test fails on windows because globrex output for `**/exclude.js` is `/^.*\/exclude\.js$/`, but because windows separator uses backslash, it doesn't register properly. Expected files should be 5, and actual files are 7.

On the other hand, the other machines should've filter it properly. It did, but the generated `.d.ts` are still copied/generated across. Expected files should be 5, and actual files are 6.

**Comment by dummdidumm** [comment]
Sounds like #1923

**Comment by ignatiusmb** [comment]
Aha, exactly that!

**Comment by ignatiusmb** [comment]
I guess https://github.com/sveltejs/kit/pull/2236/commits/752d9a23a96d9db7479902683d01b18a20beb2e0 would've passed for the other machines if `emitTypes` was set to false

**Review by dummdidumm — COMMENTED** [review]
`emitTypes` should be renamed to `noEmitTypes` or `emitTypesFalse` because `emitTypes` sounds like the opposite of what it's testing. Other than that this looks good.

**Review by dummdidumm — APPROVED** [review]

**Comment by benmccann** [comment]
I'm not that familiar with the packaging stuff, so don't wait on me for a review. I'd say go ahead and merge this whenever you're ready since you got one approval - especially since this is mostly tests and not a big API change or anything

**Pull request merged**
