### PR TITLE
docs: add a note to add path aliases to tsconfig.json

### PR DESCRIPTION
**Pull request by shaunchander**
Adds a quick one-liner to add path aliases to tsconfig.json to include type resolution and inference (especially for typed component props).

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [  ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by dummdidumm** [comment]
This shouldn't be necessary if you use `kit.alias`, which auto generates them. In which situation did you find this necessary?

**Comment by shaunchander** [comment]
> This shouldn't be necessary if you use `kit.alias`, which auto generates them. In which situation did you find this necessary?

I'm using `kit.alias` and don't have type fully safety in my project 😅. VSCode is highlights the imports and notes that it cannot resolve the types from them.

Adding the aliases to my tsconfig fixed the issue.

**Comment by dummdidumm** [comment]
Could you post a reproducible so we can look into it?

**Comment by Rich-Harris** [comment]
Closing due to lack of response — feel free to open an issue with a repro if this persists

**Pull request closed without merging**
