### PR TITLE
docs: update recommended GitHub pages config

### PR DESCRIPTION
**Pull request by Jackesque**
You must add this so that the link in the src attribute of the image components don't break whenever a user refreshes the page in a site that is statically built (eg using Github Pages).

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by eltigerchino** [comment]
Hey there! There is a section dedicated to GitHub pages that mentions this just a little down below
https://kit.svelte.dev/docs/adapter-static#github-pages

**Comment by Jackesque** [comment]
Hi. I tinkered with the deployment of my app for a while and figured out, you have to specify your repo name in paths.kit.base so that src and href attributes work with base when I refresh the page. The document mentioned paths.base, which is different (and didn't work for me), as far as I'm concerned.

**Comment by eltigerchino** [comment]
Ah, you're right. It's supposed to be `config.kit.paths.base` instead of `config.paths.base`.

**Comment by eltigerchino** [comment]
@Jackesque thank you for pointing this out!

**Review by eltigerchino — APPROVED** [review]

**Pull request merged**
