### PR TITLE
fix: correctly map prerendered pages when base path is set

### PR DESCRIPTION
**Pull request by eltigerchino**
fixes https://github.com/sveltejs/kit/issues/11210

Previously, the prerendered manifest didn't set the base path so it looked like this:
```js
export const prerendered = {
  '/base/about': 'about.html'
}
```
However, this is incorrect because it is stored in the KV with the key `/base/about.1asdf34.html` (ignore the hash, cloudflare handles it). This is also because we upload the build output such that the public files live in the base folder `.cloudflare/public/base/about.html`.

Therefore, the new manifest when a base path is set should look like this:
```js
export const prerendered = {
  '/base/about': '/base/about.html'
}
```

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like the same change might be needed in other adapters. We should update any affected at the same time, so they don't get out of sync with each other

https://github.com/sveltejs/kit/blob/ded16305b4c180a697c457ca1b2bec249b4b38fb/packages/adapter-cloudflare/index.js#L31

**Comment by eltigerchino** [comment]
> It looks like the same change might be needed in other adapters. We should update any affected at the same time, so they don't get out of sync with each other
> 
> https://github.com/sveltejs/kit/blob/ded16305b4c180a697c457ca1b2bec249b4b38fb/packages/adapter-cloudflare/index.js#L31

I’m not sure if it affects `adapter-cloudflare` because it doesn’t use the same KV asset mapping handler to return static assets. The builder prerendered paths returned should already include the base path.

I still need to check the other adapters.

**Comment by eltigerchino** [comment]
I don't think the other adapters are affected because they serve the static files like other simple static hosting service (e.g., navigating to /base/about will always return the about.html file). It's only cloudflare workers that needs to be told specifically what pathname it needs to serve the correct file.

As an aside, here are how vercel, netlify, and cloudflare handle multiple projects with the same domain but different base paths.

* https://vercel.com/guides/how-can-i-serve-multiple-projects-under-a-single-domain#
* https://answers.netlify.com/t/support-guide-can-i-deploy-multiple-repositories-in-a-single-site/179
* https://developers.cloudflare.com/rules/transform/url-rewrite/

**Review by Rich-Harris — APPROVED** [review]

**Comment by elucidsoft** [comment]
This doesn't appear to be fixed. For example, if I set my base to /blog, and then upload to Cloudflare Pages, everything works except anything in the static folder. Everything in static folder is completely inaccessible. The structure of the contents in Cloudflare Pages appears to be correct, the files are there, they are under the subfolder blog, but when I attempt to navigate to them I get a 404.  In addition, if I attempt to navigate to them using root, it goes into an infinite refresh loop.

**Comment by eltigerchino** [comment]
> This doesn't appear to be fixed. For example, if I set my base to /blog, and then upload to Cloudflare Pages, everything works except anything in the static folder. Everything in static folder is completely inaccessible. The structure of the contents in Cloudflare Pages appears to be correct, the files are there, they are under the subfolder blog, but when I attempt to navigate to them I get a 404. In addition, if I attempt to navigate to them using root, it goes into an infinite refresh loop.

Just to clarify, are you using the cloudflare adapter or the cloudflare workers adapter? Can you provide a minimal reproduction in a new issue?

**Pull request merged**
