### PR TITLE
chore: cleanup #10979

### PR DESCRIPTION
**Pull request by eltigerchino**
cleans up #10979 by implementing the [feedback](https://github.com/sveltejs/kit/pull/10979#pullrequestreview-1821652070) from after the PR was merged for the issue https://github.com/sveltejs/kit/issues/10594 

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]
Looks good to me - @Rich-Harris maybe you want to give this another look since it's about enhancing the adapter API.

**Comment by Rich-Harris** [comment]
I left some comments on the other PR. I don't think we've got the right API yet. Unfortunately I'm off today so can't weigh in much more than that, so if we want to merge the release PR we should probably revert #10979 for now

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
leaving a 'request changes' making sure we don't merge this in the meantime

**Comment by eltigerchino** [comment]
I’ve created a PR to revert the changes here https://github.com/sveltejs/kit/pull/11644

**Pull request closed without merging**
