### PR TITLE
Allow typescript configuration files

### PR DESCRIPTION
**Pull request by Marr11317**
This PR adds the possibility to use typescript configuration files, and makes use of this in the docs website.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by bluwy** [comment]
We just had a similar PR https://github.com/sveltejs/kit/pull/4031 a while ago and got closed because we want to resort to https://github.com/sveltejs/rfcs/pull/59 moving forward. Further reasons are noted at https://github.com/sveltejs/kit/pull/4031#issuecomment-1047280533, so unfortunately this won't likely be merged.

**Comment by Marr11317** [comment]
ahh too bad.

**Comment by Marr11317** [comment]
I am reopening, because this PR introduces none of the problems in the discussion you linked above.

Except for using an external package. However, it works perfectly.

**Comment by bluwy** [comment]
It introduces compatibility issues with language tools and vite-plugin-svelte no? They can't load svelte config in typescript.

**Comment by Marr11317** [comment]
Not that I can see...

**Comment by Marr11317** [comment]
so vite plugins and aliases are not found.

**Comment by Marr11317** [comment]
I guess I just didn't look close enough.

**Comment by Marr11317** [comment]
Still I believe that updating accordingly the language tools shouldn't be that much of a deal

**Pull request closed without merging**
