### PR TITLE
Add `sveltekit` plugin to `worker.plugins` Vite config

### LINKED ISSUE #10370: Rollup failed to resolve import "$env/static/public" in web workers
### Describe the bug

When importing env variables from a web worker, the project fails to build (it works in dev mode).

```
error during build:
Error: [vite]: Rollup failed to resolve import "$env/static/public" from "~/my-app/src/lib/test.worker.ts".

```

### Reproduction

> src/lib/test.worker.ts

```javascript
import {} from '$env/static/public';
```

> src/routes/+page.svelte

```javascript
<script>
  import TestWorker from '$lib/test.worker?worker';
</script>
```

### Logs

```Shell
Error: [vite]: Rollup failed to resolve import "$env/static/public" from "~/my-app/src/lib/test.worker.ts".
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.14.2
    Yarn: 1.22.15
    npm: 9.5.0
    pnpm: 8.6.3
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.2
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.3
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by taj-p**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

## Intent

In order for web workers to import variables from files dynamically created by SvelteKit (e.g. `$env/...`, `$app/...`), we need to define the `sveltekit` plugin in our vite `worker.plugins` config.

Resolves #10370

### CODE REVIEW

**Comment by dbaynard** [comment]
Is it worth adding a line to documentation/docs/10-getting-started/30-project-structure.md to explain this?

**Comment by bluwy** [comment]
This isn't the right fix for the issue. Adding the entire `sveltekit()` plugin also kicks off it's sequential server/client/workers build step, and we don't need those for workers. What we need is a trimmed-down worker-specific plugin that supports the aliases and other core features. And perhaps `sveltekit()` can append that plugin to `worker.plugins` internally.

**Comment by taj-p** [comment]
> This isn't the right fix for the issue. Adding the entire `sveltekit()` plugin also kicks off it's sequential server/client/workers build step, and we don't need those for workers. What we need is a trimmed-down worker-specific plugin that supports the aliases and other core features. And perhaps `sveltekit()` can append that plugin to `worker.plugins` internally.

SGTM! Will close PR

**Comment by taj-p** [comment]
> Apologies for necro-ing the thread, but what **did** end up being the solution here? Was `sveltekit()` ever changed accordingly? Running into this trying to use `$app/paths` in a Web Worker...

I'm not sure if this has been fixed. Locally, I've overcome the issue by adding the below lines to my `vite.config.js`:

```js
const config = {
	...
	worker: {
		plugins: [sveltekit()],
		format: 'es',
	},
	...
};
```

**Comment by sjml** [comment]
Yeah, I had that going for a little while, but IIRC it also outputs some warnings that made me nervous (and the comment that it wasn't the best way to do it, too). 

I've got it working for my needs using a define in my `vite.config.ts` file: 

```typescript
import { defineConfig } from 'vite';

export default defineConfig({
    ...
    define: {
        '__APP_BASE_PATH__': process.argv.includes('dev') ? `''` : `'${deploymentPath}'`
    }
});
```

But turning Vite into a preprocessor feels like a bit of code smell. Would be nice if there was some clear supported way of accessing `$app/paths` but I get that it's complicated. 🫤

**Pull request closed without merging**
