### PR TITLE
create-svelte: allow importing JSON modules

### PR DESCRIPTION
**Pull request by GrygrFlzr**
Since Vite supports [directly importing JSON modules](https://vitejs.dev/guide/features.html#json) this should be enabled in `tsconfig.json` so that TypeScript or VS Code doesn't complain about it.

This doesn't need to be added to `jsconfig.json`.

### CODE REVIEW

**Comment by dummdidumm** [comment]
Question is, if we want that option or a `declare module "*.json";` in `global.d.ts`. Adding the tsconfig flag means JSON files will get scanned by TS to infer the type structur, which is very handy but can also be very slow for large JSON files. What's the 80% use case here?

**Comment by GrygrFlzr** [comment]
Oh, interesting. Considering this is a Vite feature I thought Vite might have already added that type definition, but it seems to be missing from `vite/client.d.ts`.

Does the flag make TS scan *all* JSON files, or only imported ones? It seems to make sense to me that if you're explicitly importing a JSON file that you probably want to manipulate it in some way instead of treating it as a black box, so the type information would be useful compared to just getting `Record<string, any>`. You're right about the size though, stuff like lists of countries which was the use case that prompted this PR can be quite large.

This raises the question if it should be enabled for `jsconfig.json` or not. It doesn't complain, but it also doesn't show any type information if the flag isn't enabled. I guess we don't enable `jsCheck` anyway, so maybe we're assuming people are picking JS to opt out of types?

**Comment by dummdidumm** [comment]
It only will scan the imported ones. Where the breaking point for large JSON files is, I don't know - but I guess we are talking megabytes here, not kilobytes. We had an issue over at language-tools once where intellisense was getting really slow because of it.

**Review by benmccann — APPROVED** [review]

**Review by dummdidumm — APPROVED** [review]
Let's just roll with it and maybe act once the sufficient people report slowness in the IDE

**Pull request merged**
