### PR TITLE
fix: correctly restore trailing slash in url pathname for data requests

### LINKED ISSUE #9595: `trailingSlash` `ignore` gives wrong URL pathname
### Describe the bug

Viewing a page with a trailing slash when rendered clientside will give an URL pathname without the trailing slash in `+page.server.js`. This is quite problematic for custom `trailingSlash` handling in the load function.

Example:
- `/myroute/` server load gives pathname: `/myroute/` (ok)
- `/myroute/` client load gives pathname: `/myroute` (not ok)

### Reproduction

Please note that `trailingSlash` is set to `ignore`. Click both links and see the problem when viewing a page with a trailing slash.

https://stackblitz.com/edit/sveltejs-kit-template-default-y3g4ee?file=src/routes/about/+page.svelte

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600U with Radeon Graphics
    Memory: 2.41 GB / 13.86 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-node: 1.2.3 => 1.2.3
    @sveltejs/kit: 1.15.0 => 1.15.0
    svelte: 3.58.0 => 3.58.0
    vite: 4.2.1 => 4.2.1
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by GingerAdonis**
Fixes #9595 and #10125.

Because `DATA_SUFFIX` is set to `/__data.json` an [existing trailing slash gets omitted](https://github.com/sveltejs/kit/blob/master/packages/kit/src/utils/url.js#L174) in a data request. This makes it impossible to know if the request URL pathname has a trailing slash. This issue normally applies only to routes with `trailingSlash` set to `ignore` in combination with a server load function.

This PR fixes this behaviour by adding a `x-sveltekit-trailing-slash` searchparam to data requests with a trailing slash so the server can restore the omitted trailing slash. This approach keeps the `DATA_SUFFIX` the same to ensure backwards compatibility. This was the least intrusive way I found to fix the issue.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [X] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [X] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [X] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by dummdidumm — COMMENTED** [review]
Thank you! I think the idea makes sense to signal the server that the trailing slash should be kept. I'm not 100% sure we need a query param for this, or if we could just do `.../data.json/` instead.

Could you also add a test for this?

**Comment by GingerAdonis** [comment]
I'd say that adding a trailing slash to the data request itself might unnecessarily complicate the structure of the data requests URLs. Another option would be to simply change `DATA_SUFFIX` from `/__data.json` to `__data.json`. Though I'm unsure if that affects compatibility in the various environments. What do you prefer?

I'll try to implement a test. :)

**Comment by GingerAdonis** [comment]
I'm unsure how to approach a test for this. Could anyone point me in the right direction?

**Comment by GingerAdonis** [comment]
Thank you  @s3812497 for the thorough explanation.

I've added tests for this PR. However, these tests will fail until #10531 is merged.

**Comment by GingerAdonis** [comment]
I've included the changes from #10531 as requested. @dummdidumm 

This should be good to go.

**Pull request merged**
