### PR TITLE
Can pass HTTPS key pair in Vite section of config

### PR DESCRIPTION
**Pull request by ryc76**
Can pass in Vite config via svelte.conf.js kit.vite key to specify a specific HTTPS certificate and associated private key paths. Falls back to self signed certificate if configuraton is not supplied but --https cli switch is passed.

For example

```
server: {
		https: {
			key: 'path\\privkey.pem',
			cert: 'path\\cert.pem'
		}
 }
```
Issue:  https://github.com/sveltejs/kit/issues/1445

### Before submitting the PR, please make sure you do the following
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs

- [X] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Review by benmccann — APPROVED** [review]

**Comment by benmccann** [comment]
lgtm once the tests are passing. was it marked as draft because of the failing tests?

**Comment by ryc76** [comment]
No was just being over cautious. :-) Have marked as Ready For Review now.

**Comment by s-sankar** [comment]
@ryc76 could you please let me know what should be the path for reading key files from svelte.config file?

**Comment by s-sankar** [comment]
> Can pass in Vite config via svelte.conf.js kit.vite key to specify a specific HTTPS certificate and associated private key paths. Falls back to self signed certificate if configuraton is not supplied but --https cli switch is passed.
> 
> For example
> 
> ```
> server: {
> 		https: {
> 			key: 'path\\privkey.pem',
> 			cert: 'path\\cert.pem'
> 		}
>  }
> ```
> 
> Issue: #1445
> 
> ### Before submitting the PR, please make sure you do the following
> * [x]  It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
> * [x]  This message body should clearly illustrate what problems it solves.
> * [ ]  Ideally, include a test that fails without this PR but passes with it.
> 
> ### Tests
> * [ ]  Run the tests with `pnpm test` and lint the project with `pnpm lint`
> 
> ### Changesets
> * [ ]  If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

could you please let me know what should be the path for reading key files from svelte.config file?

**Pull request merged**
