### PR TITLE
[fix] make HN example RSS feed work

### PR DESCRIPTION
**Pull request by benmccann**
no changeset since this is just an example

### CODE REVIEW

**Comment by Conduitry** [comment]
Out of curiosity, what did this fix? I'm having a hard time seeing what changed beyond rewriting this to use `await`.

**Comment by benmccann** [comment]
I don't fully know :man_shrugging:  But it seems to be cleaner code in any case in addition to working better

**Comment by ignatiusmb** [comment]
It's probably because the previous one isn't `return`-ing the `fetch`, causing the function to return `void` instead of the resolved `.then`

**Comment by Conduitry** [comment]
Oh whoops, duh, yeah I missed that.

**Pull request merged**
