### PR TITLE
fix manifest not updating on route creation

### LINKED ISSUE #5142: New pages redirect to index or throw a 500 error
### Describe the bug

When creating a fresh new SvelteKit project, creating a new page under `routes` and visiting that page's URL seems to redirect to the index page (`index.svelte`).
Also...
- when creating another new page and linking to that page's URL...
or
- visiting the index page after creating new pages...

...throws the following error:
```
500
components[nodes[i]] is not a function
TypeError: components[nodes[i]] is not a function
```

Although, restarting the dev server seems to fix the issue.
Experienced this on version `1.0.0-next.347`, but it seems that it also occurs from `next.345` since downgrading to `next.344` seems to make the issue not occur.

Also, creating a new page while the dev server isn't running seems to also resolve the issue.

### Reproduction

1. `npm init svelte app-name`
2. `cd app-name && npm i`
3. `npm run dev`
4. Create a new page under `routes`, say `about.svelte` then save the file.
5. Visit `/about` in a browser.
6. Create another new page, say `asdf.svelte`
7. Visit `/asdf`
8. Visit `/`

### Logs

_No response_

### System Info

```shell
System:
  OS: Linux 5.6 Ubuntu 20.04.4 LTS (Focal Fossa)
  CPU: (4) x64 AMD Ryzen 3 2200G with Radeon Vega Graphics
  Memory: 768.98 MB / 13.68 GB
  Container: Yes
  Shell: 5.0.17 - /bin/bash
Binaries:
  Node: 16.13.1 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/node
  Yarn: 1.22.17 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/yarn
  npm: 8.1.2 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/npm
Browsers:
  Firefox: 100.0.2
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.50 
  @sveltejs/kit: 1.0.0-next.344 => 1.0.0-next.344 
  svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

Here's a screen recording to help describe what's happening.

https://user-images.githubusercontent.com/18418806/171550032-ff7a8bae-2514-4922-b4ca-fcd7ad3a384a.mp4

Also upon checking Kit's source code, it seems that these lines might be relevant to the issue, since checking the diff in the latest commit in the tag of version `next.345`, a modification was done in these lines.
`packages/kit/src/runtime/client/client.js`
image

### PR DESCRIPTION
**Pull request by gtm-nayan**
~Just checking CI for now, hopefully won't break #4997 (merci Windows gods 🙏)~ Yayy

Fixes #5142

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by gtm-nayan** [comment]
Not sure what to do about tests, [this test](https://github.com/sveltejs/kit/blob/9da39e9031728b922812007aa6639e41d201889c/packages/kit/test/apps/basics/test/test.js#L2373) should've caught #5142, no?

**Comment by benmccann** [comment]
I ran `test/apps/basics` and created a new route as that test does. I didn't have any problem visiting the new route, but when I visited `/routing` again the page contents were totally different. Maybe we should update test to also visit `/routing` and check that "Great success!" is on the page or something along those lines

**Comment by gtm-nayan** [comment]
Still passes, it shows the correct text for a brief moment before it changes to the wrong one during hydration. Is there a way to wait for hydration to complete or should I just add a timeout?

**Comment by Rich-Harris** [comment]
`page.goto` already waits for hydration... https://github.com/sveltejs/kit/blob/588ea0faeac96b3f8c3b3f87a7b496409b9a2491/packages/kit/test/utils.js#L108-L121 ...which basically means you can only test non-hydrated content by checking `!javaScriptEnabled`

**Comment by benmccann** [comment]
It's weird the text is updating. The test only runs if JavaScript is not enabled

**Comment by gtm-nayan** [comment]
If it's not skipped when javascriptEnabled is true, then it errors with
`waiting for selector "body.started" to be visible`

This means it's failing the hydration right? Even before the assertion

**Comment by gtm-nayan** [comment]
Lol if I use something like `zzz.svelte` instead of bar it actually fails at the right point because it loads the wrong route when navigating to `zzz`,

no clue why it doesn't work with bar

**Comment by gtm-nayan** [comment]
Failing test is from adapter-static, it passed in the previous run

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
