### PR TITLE
adapter types

### PR DESCRIPTION
**Pull request by Rich-Harris**
In #5081, we ask people to manually update their `src/app.d.ts` to include the relevant platform types for their adapter. It's confusing and brittle (people who already have `adapter-cloudflare` installed won't see `env.caches` magically appear, even though it's now there).

In an ideal world we'd somehow magically inject these types, but failing that, asking people to add a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) is probably reasonable.

Marking as draft because we should do this for all adapters.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Netlify and Vercel are actually a little tricky, since you might use `edge: true` or `edge: false` and the `platform` object would differ. Not immediately sure of the best solution to that. No reason for it to hold this up though so I'm marking the PR ready

**Comment by dummdidumm** [comment]
Idea: have two ambient type definitions which are in separate files and importable through `@sveltejs/adapter-vercel/edge` and `@sveltejs/adapter-vercel/noedge` or sth like that (this means the ambient file import needs to be removed from the other files)

**Comment by Rich-Harris** [comment]
The challenge will be that one day we want to allow some endpoints (or even handlers) to run on the edge and others to run in a lambda, depending on their data requirements. Not sure how to reconcile that with a global `App.Platform` interface...

**Comment by dummdidumm** [comment]
Oh yeah that sounds impossible to solve correctly with one global type definition

**Review by benmccann — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Perhaps it's an argument for normalizing/abstracting `platform` in those environments. Anyway we can cross that bridge later

**Pull request merged**
