### PR TITLE
fix: prevent multiple pages and layouts in same directory

### LINKED ISSUE #9380: Multiple +layout/+page.svelte with layout reset should be forbidden
### Describe the problem

Because of the layout reset syntax, it is currently possible to create multiple +page.svelte (or +layout.svelte)

Exemple :
```
routes/path/page/
           +page.svelte
           +page@.svelte
           +page@path.svelte
```

Sveltekit seems to accept that, and choose the most complete file (`+page@my-path.svelte` in this example).

I think this should be incorrect and generate an error.

### Describe the proposed solution

Create a page with multiples +page.svelte file using layout-reset.

Example :
https://stackblitz.com/edit/sveltejs-kit-template-default-ro1dgr?file=README.md

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by geodask**
fixes #9380:

Prevent having multiple pages or layouts in the same directory. Currently sveltekit accepts having more than on page/layout files in a directory and it picks the one with the most characters. 

This issue is cause by the reset layout syntax. For example:  ` /routes/path/+page.svelte`, `/routes/path/+page@.svelte` etc.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by geodask** [comment]
This is my first issue for an open source project. Probably the solution is not optimal and the error messages need improvements. It seemed relatively easy and because I really like svelte and sveltekit I decided to give it a try.

**Comment by geodask** [comment]
This is my first issue for an open source project. Probably the solution is not optimal and the error messages need improvements. It seemed relatively easy and so I decided to give it a try.

**Review by dummdidumm — COMMENTED** [review]
Thank you for the PR!

Suggestion: Right now this tests for `.svelte` only, but through `config.extensions` the possible ending can be enhanced/changed. Furthermore, parts of this (like `project_relative`) are already done inside the `for` loop just below. I therefore suggest to move the validation inside the `for` loop, more precisely checking inside the `if (item.kind === 'component')` branch if `route.layout.component`/`route.leaf.component` already exist, and then throw the error (the error does not need to list all the conflicting files in my opinion, it's okay to note the directory)

**Comment by dummdidumm** [comment]
Closing in favor of #9590 where you're attributed as a co-author - thank you!

**Pull request closed without merging**
