### PR TITLE
Sequence

### PR DESCRIPTION
**Pull request by Rich-Harris**
Follow-up to #1951 — no need to create a separate app to test this, we can put it in `basics`. Also, I'm going to add some docs here

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Hmm — there isn't really a place to document this at the moment, without documenting all the other `@sveltejs/kit/*` modules, which is out of the immediate scope. Going to merge this in then raise an issue for those doc changes

**Comment by Rich-Harris** [comment]
whoops, i clean forgot to add a changeset for this. will add separately

**Comment by DhyeyMoliya** [comment]
Could there be a case when we skip following handlers from an earlier handler and directly send the response to client

**Comment by Rich-Harris** [comment]
Yes, absolutely — if an earlier handler doesn't call `resolve`, later handlers are not called

**Pull request merged**
