### PR TITLE
reenable more of the CI matrix

### PR DESCRIPTION
**Pull request by Conduitry**
Now that this is free, we can afford it. Rather than simply uncommenting the old lines, I've also enabled tests on Node 15. When 16 is released and 15 goes EOL, we can update this again.

### CODE REVIEW

**Comment by Conduitry** [comment]
I don't know why the heck Node 12 on Ubuntu is failing. That's one of the ones that was already running.

**Comment by GrygrFlzr** [comment]
Possibly #404 at play. Let me force re-run all jobs.

**Comment by Conduitry** [comment]
That's possible. I had tried running them twice already, and Node 12 Ubuntu failed both times, although I didn't look carefully to see whether it was the same failure message both times.

**Comment by GrygrFlzr** [comment]
Okay, it seems to be at least consistently erroring on:
```
dev:basics
2:54:59 AM [vite] Error when evaluating SSR module /home/runner/work/kit/kit/packages/kit/test/apps/basics/src/routes/errors/module-scope-server.svelte:
Error: Crashing now
    at /home/runner/work/kit/kit/packages/kit/test/apps/basics/src/routes/errors/module-scope-server.svelte:5:12
    at instantiateModule (/home/runner/work/kit/kit/node_modules/.pnpm/vite@2.0.5/node_modules/vite/dist/node/chunks/dep-e0f09032.js:68041:166)
2:54:59 AM [vite] Error when evaluating SSR module /home/runner/work/kit/kit/packages/kit/test/apps/basics/src/routes/errors/module-scope-server.svelte:
Error: Crashing now
    at /home/runner/work/kit/kit/packages/kit/test/apps/basics/src/routes/errors/module-scope-server.svelte:5:12
    at instantiateModule (/home/runner/work/kit/kit/node_modules/.pnpm/vite@2.0.5/node_modules/vite/dist/node/chunks/dep-e0f09032.js:68041:166) (x2)
```

I can also replicate that specific error locally, so I think there's an actual issue involved that was previously skipped in CI somehow.

**Comment by GrygrFlzr** [comment]
I debugged it a bit and it seems that the error page in that test case is correctly rendering, but `vite` is also re-throwing the SSR error and triggering `uvu`. Not sure why this wasn't an issue before, though.

**Comment by GrygrFlzr** [comment]
Nevermind - while the `vite` SSR error does appear, it doesn't actually fail the `uvu` test - the set of failing tests keep changing between runs, usually something related to clicking a link, regexp routes, or redirect loops.

I think it's just a case of more test runs = more chances of failure due to the tests themselves being flaky and timing-sensitive.

**Comment by GrygrFlzr** [comment]
Okay, I merged #501 into master which should have solved most of the test stability issues.

@Conduitry go ahead and pull master to re-test the full matrix.

**Comment by Conduitry** [comment]
Success! Just the Windows ones failing now. Thanks @GrygrFlzr !

**Comment by GrygrFlzr** [comment]
Huh, the failing Windows tests cancelled the still-running macOS test for Node 15. Should macOS be shifted earlier in the OS matrix so that it has a chance to complete the run before the Windows CIs fail?

**Comment by Conduitry** [comment]
That's probably a good idea. Updated.

**Pull request merged**
