### PR TITLE
Overhaul `site-kit`

### LINKED ISSUE #6677: Dark mode docs
### Describe the problem

The documentation website only offers docs in light mode. This is blinding when you are working late at night.

### Describe the proposed solution

Please implement a dark mode toggle for the svelte kit doc website.

### Alternatives considered

_No response_

### Importance

would make my life easier

### Additional Information

_No response_

### LINKED ISSUE #7544: More flexible adjustment of the width of the SvelteKit Documentation page - navigation columns
### Describe the problem

The SvelteKit documentation, with a 1216px wide viewport, does not contain the "ON THIS PAGE" column:

obraz

For comparison - MDN with a 1216px wide viewport is still displayed like this:

obraz

I wish the SvelteKit Documentation could shrink as much as MDN. Can I ask for it? :)

---

Additionally, MDN by vievport, 1148px wide, displays "In this article" at the top of the left column:
obraz

I think it's worth doing that in the SvelteKit Documentation as well. MDN is a good pattern. :)

### Describe the proposed solution

As above.

### Alternatives considered

_No response_

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
* Closes #6677
* Closes #7544 ('on this page' comes in at 1200px)

kit.svelte.dev uses `site-kit`, but overrides a lot of styles. In order to have maintainable, consistent styles and utilities between kit.svelte.dev and svelte.dev (and possibly others in future? who knows) we need to do some spring cleaning.

I figured the easiest way to do that would be to just copy `site-kit` into this repo for now, so that we don't need to muck around with linked packages etc. Once it's in a good enough place, we can move it back to the `sites` repo and apply it to svelte.dev.

I'd like to move as much of the docs handling logic etc to `site-kit` as possible (and I'd like to make the Svelte docs much more like the Kit docs).

The most obvious change here is that the docs CSS has been overhauled. I think it looks much nicer, particularly on large screens: https://kit-svelte-dev-git-site-kit-svelte.vercel.app/docs/introduction

Still more that can be done, though it doesn't all need to happen in this PR.

### CODE REVIEW

**Comment by inudge** [comment]
Screenshot 2022-11-30 at 20 22 58

I'm seeing 160px of left margin on a 27" iMac. 
I don't think it looks good, too unusual to my eyes, but of course that's totally subjective.

**Comment by lukaszpolowczyk** [comment]
I hope: https://github.com/sveltejs/kit/issues/7544

I'd like that too, but maybe it's too much: https://github.com/sveltejs/kit/issues/3948

**Comment by lukaszpolowczyk** [comment]
Little missing in dark mode:
"NO RESULTS" in the search engine is on a white background.
obraz

**Comment by AIS-Brandon** [comment]
Is there a way to toggle dark mode, or is it just up to system preferences?

**Comment by babichjacob** [comment]
Yes, system preferences are the dark mode toggle.

**Pull request merged**
