### PR TITLE
[fix]Continuous optionals should not throw conflict error

### PR DESCRIPTION
**Pull request by aolose**
fix issue [7925](https://github.com/sveltejs/kit/issues/7925)

folder structure [[a]]/[[b]]/+page will throw routes conflict error

the error from the function `prevent_conflicts`

here:
```
permutations = [
...permutations.map((x) => x + next),
...permutations.map((x) => x + `<${matcher}>${next}`)
];
```
will generate permutations [ '//', '/<*>/', '//<*>', '/<*>/<*>' ]
but  actually, it' impossible match route  /empty/[[b]] . so '//<*>' should be remove from result.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by dummdidumm — COMMENTED** [review]
Thank you! Could you add a changeset and add a test in the `index.spec.js` file next to the changed file?

**Comment by aolose** [comment]
> Thank you! Could you add a changeset and add a test in the `index.spec.js` file next to the changed file?

okay, done.

**Comment by dummdidumm** [comment]
thanks for the test, however for this it's sufficient to create a unit test - you would create another unit test similar to the existing one in `create_manifest_data/index.spec.js` at line 718.

**Comment by aolose** [comment]
> thanks for the test, however for this it's sufficient to create a unit test - you would create another unit test similar to the existing one in `create_manifest_data/index.spec.js` at line 718.

thank you, I'll try it.

**Review by dummdidumm — APPROVED** [review]
Thank you!

**Pull request merged**
