### PR TITLE
rename 'shared' and 'server-only' `load` functions to 'universal' and 'server'

### LINKED ISSUE #7952: Rename 'shared load functions' to 'universal load functions'
### Describe the problem

I'm working on some tutorial content, and finding the 'server-only `load` functions' and 'shared `load` functions' terminology a bit ugly and confusing.

### Describe the proposed solution

* Server `load` function — `+page.server.js`, `+layout.server.js`
* Universal `load` function — `+page.js`, `+layout.js`

### Alternatives considered

'Isomorphic' 🤮 

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #7952

### CODE REVIEW

**Comment by dummdidumm** [comment]
I'm ok with server, not sure about universal vs shared

**Comment by Rich-Harris** [comment]
'shared' makes me think 'between routes' rather than 'between environments'

**Comment by Theo-Steiner** [comment]
I find `universal` a bit confusing in referring to client + server.
What about `hybrid` or perhaps `transitional`?

**Comment by Rich-Harris** [comment]
It's fairly widely used in this context. If you [Google](https://www.google.com/search?client=firefox-b-1-d&q=universal+javascript) 'Universal JavaScript', all the top results refer to code that runs on server and client:

image

That's not true for 'hybrid' or 'transitional'. It _is_ true for 'isomorphic', but that word has its own problems.

**Comment by Rich-Harris** [comment]
it was close, but an exhaustive debate was had among the maintainers, and democracy must be respected — we chose to make this change

**Pull request merged**
