### PR TITLE
[fix] enable Vite's modulePreload.polyfill

### PR DESCRIPTION
**Pull request by benmccann**
fixes https://github.com/sveltejs/kit/issues/7557

no idea why lint is failing on this, but it seems unrelated

### CODE REVIEW

**Comment by Rich-Harris** [comment]
lint failure is caused by https://github.com/sveltejs/kit/pull/7771

**Comment by Rich-Harris** [comment]
this doesn't seem to have changed anything: 

image

**Comment by benmccann** [comment]
Hmm. This is what I see in Firefox with `adapter-static` (doing a `build` and then running the static site with `python -m http.server`)

Screenshot from 2022-11-22 13-20-20

It resolves the console warnings for me as well

**Comment by Rich-Harris** [comment]
Weird, I could have sworn I was looking at the preview deployment. Confirmed fixed with the most recent one

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
