### PR TITLE
shrink test matrix

### LINKED ISSUE #796: shrink test matrix?
We test node 12, 14 and 15 on linux, mac and windows — 9 separate runs. It would be quicker if we had fewer. Unless we're trying to identify e.g. a windows bug that only happens on node 12, would it be sufficient to test 12 and 14 on linux, and 15 on linux, mac and windows?

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #796

### CODE REVIEW

**Comment by Rich-Harris** [comment]
hmm. looks like i messed this up, it's only running tests on 14. anyone who isn't pathologically incapable of writing correct YAML able to point out my error?

**Comment by Conduitry** [comment]
I can't tell what's going on here. It certainly _looks_ like you're using this feature as intended https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations

**Comment by Rich-Harris** [comment]
when i am president YAML will be outlawed

**Comment by Conduitry** [comment]
I maintain that it's not especially worth it to be selectively dropping 15 because in one month we will be adding 16 everywhere (at which point we can also drop 15 everywhere).

**Comment by Rich-Harris** [comment]
i don't follow — we're going from a 3x3 matrix (linux, win, mac * 12, 14, 15) to 3 (linux, win, mac * 14) + 2 (12 + 15). whether the 2 is (12 + 15) or (12 + 16) doesn't make a difference, surely?

**Comment by Conduitry** [comment]
I was assuming that, once Node 16 is released, we'd want to be testing on 14 and 16 on all platforms. Does that seem wrong to you? I don't have especially strong opinions about which platforms we should be testing 12 on.

**Comment by Rich-Harris** [comment]
the premise of this PR is that we need to test all LTS versions (which would actually include 15 alongside 16 for a short while) _and_ we need to test all OSes, but we don't need to test all LTS versions on all OSes

**Comment by Conduitry** [comment]
I see. Maybe try taking things out of the matrix you don't want with https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-excluding-configurations-from-a-matrix rather than adding things to the matrix?

**Pull request merged**
