### PR TITLE
site: fix copy button alignment

### PR DESCRIPTION
**Pull request by gtm-nayan**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by PuruVJ** [comment]
Can u tell where this is causing the issue?

**Comment by PuruVJ** [comment]
I dont see anything 🤔

CleanShot 2023-08-14 at 15 43 14@2x

**Comment by gtm-nayan** [comment]
102c1a4311e25c8c7dbf8f664d32effc

**Comment by s3812497** [comment]
It's happening on Safari (Version 17.0 (19616.1.26.11.3)) as well.

**Review by s3812497 — APPROVED** [review]

**Pull request merged**
