### PR TITLE
Adding a Recipes section to the docs

### PR DESCRIPTION
**Pull request by danawoodman**
I'm not sure if this is the right place to put such content, but I feel it is useful to users to be able to refer to usage examples and since we don't have a REPL yet, maybe we could have a "recipes" section that we could place common solutions to issues users are facing?

Consider this a proposal; can move wherever it makes sense

Relates to #1008

### CODE REVIEW

**Comment by benmccann** [comment]
I wouldn't have thought of using the `Location` header as @Conduitry mentioned (maybe because I was in the mindset of having a `redirect` field since that's what pages do), so it might not be a bad idea to add something to https://kit.svelte.dev/docs#routing-endpoints

We've always had recipes live at https://sveltesociety.dev/recipes, so probably wouldn't want to add recipes to the main docs, but maybe add a SvelteKit section over there if there are more SvelteKit-specific recipes

**Comment by danawoodman** [comment]
Personally I feel having docs for Kit easily discoverable will reduce confusion. I've never looked at that other site despite spending a lot of time with Kit lately. 

I like how Svelte has the REPL section but since we can't do that yet, some "here is how to use Kit" content would likely reduce people's need to ask the same questions regularly on Discord. 

Do you think there is any major drawbacks/harm in having a section like this till a better solution is found?

**Comment by benmccann** [comment]
The tricky thing with recipes is that there's nearly an infinite number of things that people might think are worth of a recipe. It takes a lot of effort to figure out what to include vs not include, how to organize, etc. We've tended to focus on reference while leaving recipes, examples, etc. to the community. If the issue is about discovery we maybe could try to surface https://sveltesociety.dev/ as we do for https://github.com/sveltejs/integrations

**Comment by danawoodman** [comment]
I hear you, is can be a bit nebulous. I would imagine it would be primarily things that expand on usage of API and really common things people ask about in Discord etc

Is there a plan to include an examples section like Svelte? That was basically what I was envisioning and that section has lots of "recipes" for doing things in Svelte.

**Comment by benmccann** [comment]
We would like to have a REPL for SvelteKit, but it's not simple to implement. It's a bit hard to envision exactly what would go in SvelteKit examples. If we had a bigger list of examples it might be easier to consider. That's one reason why starting it off as a community effort might be helpful

Anyway, in this case it seems reasonable to me just to add the docs directly to the https://kit.svelte.dev/docs#routing-endpoints section

**Comment by benmccann** [comment]
We would like to have a REPL for SvelteKit, but it's not simple to implement. It's a bit hard to envision exactly what would go in SvelteKit examples. If we had a bigger list of examples it might be easier to consider. That's one reason why starting it off as a community effort might be helpful

Anyway, in this case it seems reasonable to me just to add the docs directly to the https://kit.svelte.dev/docs#routing-endpoints sectionor maybe we should add this to the FAQ instead. @Conduitry do you have thoughts on if / where we might want to document redirect in endpoints?

**Comment by Rich-Harris** [comment]
opened https://github.com/sveltejs/kit/pull/1055

**Comment by Rich-Harris** [comment]
closing now that #1055 is merged — thanks

**Comment by danawoodman** [comment]
Is there another issue I can track that relates to an "examples" section like Svelte?

**Pull request closed without merging**
