### PR TITLE
[fix] symlink routes

### LINKED ISSUE #6303: 🐛 Symlink routes no longer work (1.0.0-next.432 — PR #6174)
### Describe the bug

Symlink routes / Symbolic link routes are no longer working since Sveltekit version `1.0.0-next.432` [(PR #6174)](https://github.com/sveltejs/kit/pull/6174)

### Reproduction

**1.0.0-next.431** (working)
✅ https://github.com/oneezy/sveltekit-symlink-repro-next-431

**1.0.0-next.432** (broke)
❌ https://github.com/oneezy/sveltekit-symlink-repro-next-432

image

### Logs

```shell
Error: Not found: /symlink
    at resolve (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/runtime/server/index.js:430:14)
    at Object.handle (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/vite/dev/index.js:318:66)
    at respond (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/runtime/server/index.js:213:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/vite/dev/index.js:375:22
```

### System Info

```shell
System:
    OS: Windows 11
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 15.50 GB / 31.75 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: 1.0.0-next.406 => 1.0.0-next.406 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

We use a [monorepo](https://github.com/oneezy/monorepo) with multiple separate apps that we link together via symlink routes so this one's a showstopper for us.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #6303

No test because I don't know how to write one for this. @oneezy could you test out if this fixes the issue for you?

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Conduitry** [comment]
You _should_ be able to just create a relative symlink in some test's `routes` directory and then check it in with Git.

**Comment by oneezy** [comment]
Thanks @dummdidumm !
Just tested and LGTM!

Here's a quick video showing the fix in action

[symlink-routes-fix.webm](https://user-images.githubusercontent.com/7369575/190230929-3bd1d17b-bb5d-4394-977e-ce490570368d.webm)

**Review by oneezy — APPROVED** [review]
LGTM!

**Comment by benmccann** [comment]
I've rerun the tests a few times and they keep failing. I think this one is a real test failure

**Comment by dummdidumm** [comment]
Apparently I have a magic laptop, it passed now after rerunning again.

**Comment by oneezy** [comment]
OS issue maybe? Going back to the original [PR fix](https://github.com/sveltejs/kit/pull/4957#issuecomment-1130510455), here's a screenshot of the conversation had around tests

image

**Comment by Rich-Harris** [comment]
Added a test. Unfortunately it's failing for me when the app is built, even though it's fine in dev. Looking

**Review by dummdidumm — COMMENTED** [review]
I see `vite_manifest` being used in several other places. Do they need the same treatment?

**Comment by Rich-Harris** [comment]
good catch, applied the same logic to endpoints. i think that covers everything

**Review by oneezy — APPROVED** [review]

**Comment by Conduitry** [comment]
To report back here about the Windows stuff: I checked out this branch on Windows 10, manually created the symlink, and ran tests, and the new symlink test passed for me. So I think we're safe to skip that one on Windows (maybe just during CI?) if it's causing problems for us.

**Comment by Conduitry** [comment]
Do we want to just go back to directly checking the symlink into the repo if we're going to be skipping the test on Windows anyway?

**Comment by Rich-Harris** [comment]
Windows isn't failing that one test, it's failing to start the dev server altogether. https://github.com/sveltejs/kit/pull/6796/commits/7de8a8ae5bf20210f1ba5b2ba93beeeff34d2588 is to see if the problem was having/creating the symlink in the first place (though I don't know why the error would be so vague)

**Review by Rich-Harris — APPROVED** [review]

**Comment by oneezy** [comment]
:heart::heart::heart: 

Thanks a ton crew' `SveltaLowda`

**Pull request merged**
