### PR TITLE
scroll on browser back button click

### PR DESCRIPTION
**Pull request by vicky1999**
solves - #3621 and maybe #3636 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### Video Test: 

https://user-images.githubusercontent.com/24916780/152032395-44620051-5d47-4454-bf01-c33b2121278f.mov

### CODE REVIEW

**Comment by benmccann** [comment]
Can you explain how you came to this solution and why you are making this change?

**Comment by vicky1999** [comment]
When using `pushState`, the history is recorded twice while navigating through hashes ( #3636 ).  So, I tried `replaceState` to replace the history entry.

**Comment by vicky1999** [comment]
@benmccann I have tested the approach.  and it is working.  please let me know if there's any other way to solve this problem.

**Comment by bluwy** [comment]
I think there's a bigger issue with the behavour now, that somewhere in the code `pushState` is being called twice. With this PR, we're only making the first `pushState` a `replaceState` so we're pushing a new history entry once through the second `pushState`, and I dont think this is the right solution. We should find out where the second `pushState` happens and prevent that. Or maybe it's safe to remove the first `pushState`.

Maybe this was already discussed before and I missed it. But historically when we call the `setTimeout` `pushState` line, no other `pushState` is called later.

**Comment by benmccann** [comment]
Yes, I agree this is not the right solution, so I'm going to go ahead and close this. If you can point out on the issues where the two calls happen that may help us in designing a better solution

**Pull request closed without merging**
