### PR TITLE
[site] Remove pointer events none on search

### PR DESCRIPTION
**Pull request by ghostdevv**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

Currently if you use the search feature, you can't scroll - [reported here](https://discord.com/channels/457912077277855764/750401468569354431/958427659233288192)

### CODE REVIEW

**Comment by benmccann** [comment]
Motivation is to address user report from Discord:

> Noticing on https://kit.svelte.dev/ that the search bar from ctrl/cmd + k doesn't seem to allow mouse scrolling, though keyboard navigation is possible. Is that intentional or a bug?

**Review by bluwy — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Thanks — it looks like the flex changes cause the search input to change height almost randomly, any ideas?

https://user-images.githubusercontent.com/1162160/161143990-24fe1079-5897-412c-8391-41d001aac0a8.mov

**Comment by gtm-nayan** [comment]
`flex-shrink: 0` on the input seems to do the trick.

**Comment by ghostdevv** [comment]
Thanks @gtm-nayan - should be working now @Rich-Harris

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
