### PR TITLE
Prevent unsafe server-side store updates

### LINKED ISSUE #8614: SSR rendered page retains old store value in dev mode
### Describe the bug

Steps:

1. Start dev server
2. Initialize and export a store with value 0
3. Import the store in a page
4. Set store value in the page to 1
5. Open the page for the **first time**
6. As expected the page renders store value 1, not 0
7. Deactivate/remove code from step 4
8. Refresh the page
9. Page now renders store value 1 (shortly, SSR cached?) which is then hydrated/updated client side to value 0

Workaround:

Restart the dev server, the SSR rendered page no longer has value 1 but value 0

Question:

Is this intended/expected behavior, is it configurable or a bug in vite or svelte?

### Reproduction

https://github.com/konstantinblaesi/store-issue-repro

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 15.16 GB / 31.03 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 108.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/kit: ^1.0.0 => 1.1.4 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

[Original discord discussion](https://discord.com/channels/457912077277855764/1065627141548548137)

### PR DESCRIPTION
**Pull request by Rich-Harris**
* closes #8614 

This aliases `svelte/store` to a virtual module that intercepts calls to `writable` and overwrites the `set` and `update` methods to throw an error if you try to use them on the server. This means that something like this...

```js
// src/lib/stores.js
import { writable } from 'svelte/store';

export const user = writable(null);
```

```js
// src/routes/+layout.server.js
import { user } from '$lib/stores.js';

export async function load(event) {
  user.set(await get_user(event));
}
```

...would throw an error in development.

We _don't_ want this to apply for stores that were created during load or render, so we track whether that's currently happening and only apply the override when it's not. (Due to the async nature of data loading there's a very small chance of harmless false negatives.)

Needs tests

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by dummdidumm** [comment]
Damn, that's a smart way to implement this. I think it needs to be configurable/opt-in and/or a warning though.
1. Some existing apps might suddenly crash, leaving people scratching their heads what's going on
2. For _some_ apps this might be intentional. Imagine a Node environment where some persistent state across users (multiplayer game state for example) is handled through writables - something like that should still be possible

**Comment by Rich-Harris** [comment]
Downgrading it to a warning could work. 

There's a more immediate practical concern though — using `__sveltekit/store` makes a module impossible to unit test. Not sure how best to solve that without replacing uvu with vitest

**Comment by Rich-Harris** [comment]
Also, the virtual modules are getting out of hand, I'm going to add a dedent utility in a separate PR. We have `trim(...)` already but i think it can be improved

**Comment by Conduitry** [comment]
Doesn't `import-meta-resolve` need to be a _prod_ dependency of Kit? It's used in `packages/kit/src/exports/vite/index.js` which isn't getting bundled AFAIK.

**Comment by itssumitrai** [comment]
Hi, this would start breaking our production application. We have a custom wrapper on top of svelte store to make it not accidentally share state on server for different requests, but this change throwing out error is basically going to force us and probably others into looking at other state management libraries instead of using Svelte stores. I think a configurable warning is much better alternative.

**Comment by Rich-Harris** [comment]
In that case — and since this somewhat complex addition only prevents one specific kind of unwanted side-effect, namely those that happen to use `writable` instead of any other method of sharing state (including normal variables) — I'm inclined to close this, and rely on [the docs](https://kit.svelte.dev/docs/state-management) to help people avoid shooting themselves in the foot. Any objections?

**Comment by dummdidumm** [comment]
Sounds good to me 👍

**Comment by 205g0** [comment]
Would it be a good idea to put a `dev && console.log('writable <name> created')` after every Writable creation in my app? If one of these console.logs pops up in my server log, I'd know something is wrong. 

After reading all related threads, I found the hardest part, how to test / detect server-side store updates. There's somehow no feedback loop telling instantly, hey, this is wrong (or is there?). Hence, the aforementioned idea.

Moreover, Svelte stores are one of the best state management systems where you just code complex state without thinking too much, I just wonder if I can keep this flow also with `ssr = true`.

**Pull request closed without merging**
