### PR TITLE
Fix obscure characters in docs

### PR DESCRIPTION
**Pull request by danielzsh**
For whatever reason, the dashes render as obscure characters:
image
This pr aims to fix that :) (although I'm not sure how many more places this issue appears in)

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by Conduitry** [comment]
Hm. These _should_ work, and I'm pretty sure it used to. I think I'd prefer to figure out what's going wrong with character encoding than to hide it by changing the character we're using.

**Comment by danielzsh** [comment]
Hm, [this stackoverflow article](https://stackoverflow.com/questions/12039171/how-to-display-sign-in-chrome-and-opera) could be relevant?

**Comment by Rich-Harris** [comment]
I bet this is somehow related to https://github.com/sveltejs/kit/pull/11649 — we switched from using `node:fs` directly to using `import.meta.glob` and the new `read` function from `$app/server`

**Comment by danielzsh** [comment]
What's even weirder is that when the page is rendered locally via `pnpm dev`, the em dash renders fine; it just breaks in the actual build for some reason.

**Comment by tmarsik42** [comment]
Seems like an encoding issue on file read? I've found out that the em dash (—) char is represented as three characters (â), whose unicode codes correspond to the byte representation of the em dash, if it helps. I tried investigating the solution further but I still don't understand why it doesn't happen everytime (https://kit.svelte.dev/docs/routing is fine)

Snímek obrazovky 2024-01-19 v 9 33 30

**Comment by Rich-Harris** [comment]
It's a bug in `read`, it sounds like we need more robust base64 decoding

**Comment by Rich-Harris** [comment]
closing in favour of #11682 — thank you!

**Pull request closed without merging**
