### PR TITLE
replace %svelte.assets% with relative path

### LINKED ISSUE #2697: Generated URLs are inconsistent to the basepath with `adapter-static`
### Describe the bug

Sapper was gracefully handling non-root basepaths by injecting a `<base>` tag into `<head>` in place of `%sapper.base%`. SvelteKit doesn't have that, but it does have `kit.paths.base`. By changing it, the auto-generated URLs of SvelteKit are rebased, but if there were any previous static URLs, for example, a favicon in `app.html`, these URLs will be broken.

Due to the fact that there are now both rebased and non-rebased URLs on a page, this can no longer be remedied by injecting a `<base>` tag with a hook, as @benmccann suggested in https://github.com/illright/attractions/issues/311#issuecomment-950333419.

### Reproduction

https://github.com/illright/sveltekit-repro-basepath

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.14 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.16 GB / 7.62 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.11.0 - /usr/bin/node
    npm: 8.0.0 - /usr/bin/npm
  Browsers:
    Firefox: 93.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: next => 1.0.0-next.191 
    svelte: ^3.42.6 => 3.44.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This blocks reliable deployment of SvelteKit-generated websites to GitHub Pages.

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #2697, supersedes #3088. Replaces `%svelte.assets%` in `src/app.html` with a relative path to the root (or to `paths.assets` in production, if specified).

In other words this...

```html
<link rel="icon" type="image/png" href="%svelte.assets%/favicon.png" />
```

...will work regardless of whether `paths.assets` is set, and will also work if you've set `paths.base` (or, in future, if we implement dynamic basepaths somehow) because a page like `/custom-basepath/foo/bar/baz` will link to `../../favicon.png`, which resolves to `/custom-basepath/favicon.png`. It will still work if `trailingSlash` is  `"always"` .

(Note that there's currently a bug around `paths.base` — static assets aren't served from there in dev mode. Needs fixing separately.)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Conduitry** [comment]
Also adjacent: #3231 and #3232

**Comment by Rich-Harris** [comment]
The deployments are failing because they're trying to build with the most recent released version of Kit, which doesn't know how to handle `%svelte.assets%` and is therefore resulting in a malformed URI error when prerendering. We can safely ignore

**Comment by Conduitry** [comment]
Should this PR be marked as resolving #3231 now?

I didn't look closely at what was happening in #3232.

**Comment by Rich-Harris** [comment]
It should, yeah. I need to look into #3232

**Comment by dreitzner** [comment]
@Rich-Harris should I port the relevant docs over from #3088 ?

**Pull request merged**
