### PR TITLE
[chore] clean up playwright-chromium root dependency

### PR DESCRIPTION
**Pull request by Conduitry**
There was an unneeded (and outdated) version of `playwright-chromium` in the root `package.json` of this repo. This removes it.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Conduitry** [comment]
A bunch of tests are failing. What do they do that I wouldn't be testing with a `pnpm test` from the root of this repo?

**Comment by mrkishi** [comment]
It seems like that's due to `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD`. Tests probably assume the browser is in `PATH`, in this case through `node_modules`?

**Comment by Conduitry** [comment]
Oh, I see. Does it make sense then to have this _only_ at the root level (and not in `adapter-static`) - and to also bump it to the same version as is being used for `@playwright/test` elsewhere?

**Comment by mrkishi** [comment]
My mistake—`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` is `1` throughout the workflow _except_ when `pnpm install`ing, and I see  `playwright` did download the browsers. I don't know why it couldn't launch them, then.

@pngwn since you got caching working in the first place, do you have an opinion if it's worth migrating to `playwright install --with-deps chromium` these days?

**Comment by Rich-Harris** [comment]
what's the status of this?

**Comment by Conduitry** [comment]
The (probably) most pressing part was to stop having two different versions of playwright-chromium in the project, which was since addressed in another PR.

I've merged master back in and resolved the conflicts. CI is running now. If that fails, I'd be in favor of just closing this without spending more time investigating why that's happening when the tests work locally.

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
