### PR TITLE
Legacy builds

### PR DESCRIPTION
**Pull request by dishuostec**
This PR use [a monkey patched version of @vitejs/plugin-legacy](https://github.com/dishuostec/vite-plugin-legacy).

Here is [a forked hn.svelte.dev with legacy builds](https://github.com/dishuostec/kit/tree/test/feature/legacy/examples/hn.svelte.dev-legacy#build).

It works, but I don't know why the order of nodes are wrong.

Snipaste_2021-12-01_17-23-07

<details>
<summary>*Some tests*</summary>

Snipaste_2021-12-01_17-31-25
Snipaste_2021-12-01_17-32-34

</details>

TODO:

- [x] test in IE 11.
- [ ] test in Safari 10.1.
- [ ] resolve wrong order of DOM nodes.

### CODE REVIEW

**Comment by dominikg** [comment]
there are issues covering legacy builds already #12 and #2745  

Your PR adds an experimental monkey-patched version of vite-plugin-legacy as a dependency, which is not likely to get merged. 

I suggest you mark it as a draft and join us on discord to discuss how legacy support can be achieved as an optional addon instead of a hard dependency.

**Comment by benmccann** [comment]
I'd agree with Dominik that the best course of action would be to get any necessary improvements into `vite-plugin-legacy` as a first course of action

**Comment by dishuostec** [comment]
Ok, I will make a PR to `vite-plugin-legacy` to try to make it works with kit.

**Comment by benmccann** [comment]
I'm going to close this for the time being to keep the review queue clean. We can reopen after `vite-plugin-legacy` has been updated

**Pull request closed without merging**
