### PR TITLE
fix: don't retry failed implicit data preloads

### LINKED ISSUE #8301: Prefetch repeatedly refetching after a 40x from a route
### Describe the bug

SvelteKit repeatedly tries to prefetch a page that throws 40x http codes. 
Which should not be the case for 401 and 403, as they are typically used for restricting access to content.

This also adds the issue of `hooks.server.ts` being spammed with each request.

### Reproduction

https://github.com/Curstantine/sveltekit-prefetch-4xx-repeat

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 6.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 4.82 GB / 7.65 GB
    Container: Yes
    Shell: 3.5.1 - /bin/fish
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #8301

Not sure if this is the best approach, therefore no test yet

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
If we were to do this I think we'd want a `failed_preloads.clear()` somewhere, most likely after any successful navigation. I do somewhat lean towards arguing that this is the developer's responsibility to address with `data-sveltekit-preload-data="off"`, though I could probably be persuaded in the other direction.

**Comment by dummdidumm** [comment]
I didn't add a `clear` because if you have a layout with a link, that link would try to be prefetched again (and fail again) after each navigation. Under what circumstances could the approach of only deleting the id in question lead to something not getting prefetched again? (possible answer: with a redirect; that probably needs a check to delete this as well)

If we don't want to change this, then we should at least print a more helpful message to the console at dev time. Something like "if this is a link that is very likely to fail while prefetching, consider setting `data-sveltekit-preload-data="off"` on it".

**Comment by Rich-Harris** [comment]
> Under what circumstances could the approach of only deleting the id in question lead to something not getting prefetched again?

Say I fail to navigate to `/admin`, then navigate to `/login`, then attempt to navigate to `/admin` again. Following the successful navigation to `/login` I'd expect subsequent links to be preloaded

**Comment by dummdidumm** [comment]
Yeah that makes sense.

Since this is all highly app-specific, and hard to find a one-size-fits-all-solution (your case for example is more conservative, but the related issue would probably prefer my solution), I think a dev time warning is the better solution.

**Pull request closed without merging**
