### PR TITLE
fix: allow calling `fetch` with `data:` URL

### LINKED ISSUE #9160: Teleport data from server to client in universal `load` functions
### Describe the problem

One point of confusion with `load` functions is that universal loads run during SSR _and_ upon hydration (and then for subsequent client-side navigations). This is most visible if you return something non-deterministic:

```js
// src/routes/+page.js
export function load() {
  return {
    random: Math.random()
  };
}
```

The value of `data.random` inside `+page.svelte` will differ between the server-rendered HTML and the hydrated document. If it were a `+page.server.js` instead, the result of calling the `load` function would be serialized, and would therefore be consistent.

There are good reasons for re-running universal `load` functions upon hydration:

1. It allows you to return different data between server and browser, in cases where that's desirable
2. It means we don't need to serialize the output, which is often larger than the input (for example, on a project at the NYT we were doing statistical analysis of some JSON data. The input was large, in the 100s of kbs, but the output was _huge_ — megabytes of moving averages and so on) 
3. We can return non-serializable objects such as components and stores, enabling advanced whizzbangery

(Note that `event.fetch` calls are _not_ repeated — the responses are serialized into, and read from, the HTML.)

Despite that, it would be useful to have a mechanism to avoid re-running code in cases where you just want to use the same value between server and client, and are happy with the serialization constraints.

### Describe the proposed solution

I propose a new `event.teleport` helper:

```js
export function load({ teleport }) {
  const random = teleport(() => Math.random());
  return {
    random
  };
}
```

* During SSR, the result of calling the callback would be serialized (using the same mechanisms we use for server load functions) and assigned to an automatically-generated ID
* During hydration, `teleport(...)` would just return the data associated with the automatically-generated ID
* During client-side navigation, `teleport` would just be `fn => fn()`

Automatically generating IDs requires that `teleport` be called synchronously inside the `load` body (and not be inside `if` blocks etc — in other words, hooks rules). In some circumstances that might be untenable, so users could specify a key (if a key is reused, we would throw an error):

```js
// either this...
const random = teleport('random', () => Math.random());

// ...or this:
const random = teleport(() => Math.random(), 'random');
```

## Bikeshedding alert

If the key is optional, having it be the second argument would be more logical. But having it be the first argument would result in neater code:

```js
// prettier prefers string-first-function-second...
const object = teleport('object', () => ({
  answer: 42
}));

// ...to string-second-function-first:
const object = teleport(
  () => ({
    answer: 42
  }),
  'object'
)
```

## Reusing entire `load` functions

If you wanted to, you could easily reuse the entire function body:

```js
export const load = (event) => {
  return teleport(() => ({
    stuff: get_stuff(event.params.stuff),
    more_stuff: get_more_stuff(event.params.stuff),
  }));
};
```

## Promises

We could use the same promise serialization mechanism we currently use:

```js
export async function load({ reuse }) {
  const randomized = await reuse(async () => {
    const response = await fetch('https://api.example.com/things');
    const { things } = await response.json();
    return randomize(things);
  });

  return {
   randomized
  };
}
```

### Alternatives considered

* different name — `keep`, `sticky`, `reuse` etc
* key-first, key-second, key-optional

### Importance

nice to have

### Additional Information

_No response_

### LINKED ISSUE #10657: fetch with data URL throws error when used in SvelteKit
### Describe the bug

I have a web app that takes a zlib-compressed and base64-encoded blob as user input. I validate the data on the client, before sending it to the server, where it is validated again. 

The validation happens by passing the base64-encoded blob to `fetch()` as a data URL, which returns a `ReadableStream` that is then deflated using a `DecompressionStream`. The validation function works in the browser and in node.js, which was a priority to not have nearly identical duplicate code.

Adding the function call on the server side (`+page.server.ts`) raises an exception.

```
Error: Cannot use relative URL (data:application/octet-stream;base64,eNrtfV1vXMm…) with global fetch — use `event.fetch` instead: https://kit.svelte.dev/docs/web-standards#fetch-apis
    at globalThis.fetch …
```

Svelte is mistakenly identifying a data URL as a relative URL.
And forcibly raising an error when global `fetch()` is used is a problem as well, because this prevents the use of functions that are designed to work in both environments, client and server.

### Reproduction

Run this line in nodejs and in a `+page.server.js` file.

```js
await fetch("data:application/octet-stream;base64,eNrtfV==")
```

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 16.37 GB / 31.75 GB
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 7.25.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^4.0.5 => 4.2.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by danielniccoli**
Fixes #10657

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Conduitry** [comment]
I'm wondering whether we instead just want to ensure that the URLs begin with `\w+:`, and what sort of false negatives that would result in. I don't know. I don't know whether it makes sense to explicitly call out `data:` separately from all of the other URL schemes.

**Comment by danielniccoli** [comment]
That you would allow a relative url like

/items#detail:45

If you want to change that, I guess a proper url parser should be used instead of a simple regex. Maybe this issue can be used as a quick fix for the data urls, and we open a separate issue to rewrite the logic entirely?

**Comment by danielniccoli** [comment]
@Conduitry  @benmccann Would the approach above be acceptable? I'm ready to update this PR. Please let me know.

**Comment by benmccann** [comment]
That sounds fine, but I think your translation from text to reflex omitted uppercase letters and "+"

**Comment by danielniccoli** [comment]
Replaced by #10699 (Sorry, pull requests are somewhat challenging for me 🙂 )

**Pull request closed without merging**
