### PR TITLE
Implement keepfocus for goto.

### PR DESCRIPTION
**Pull request by mohe2015**
This allows you to navigate without loosing focus of the current element.
This may be useful if you want to e.g store the current filter or sorting order of a list in the url to allow sharing it.

Closes https://github.com/sveltejs/kit/issues/1022
### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` (**doesn't run on two different systems**) and lint the project with `pnpm lint` (success) and `pnpm check` (success)

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts

### CODE REVIEW

**Comment by dummdidumm** [comment]
This would only be part of the solution, right? What if you click on a `<a>` tag but want to keep focus?

**Comment by mohe2015** [comment]
> This would only be part of the solution, right? What if you click on a `<a>` tag but want to keep focus?

That's correct but for my use case (goto with replaceState, only changing query parameters) this is enough (I'm combining this with a custom store for the query parameters and the goto is in that store implementation). I wanted to start with the minimal changes so the chances of getting them in is higher.

@lukaszpolowczyk
@ahtcx @MatthiasGrandl (they seem to have the same usecase like me)
Which additional changes would you need and what do you think about the current ones?

**Comment by mohe2015** [comment]
@dummdidumm Do you think this has a chance of getting merged if the tests pass?

**Comment by Rich-Harris** [comment]
Thanks, I tweaked the docs and the types now that they're growing beyond what makes sense to have in a single block of text

**Pull request merged**
