### PR TITLE
[fix] Dynamic fallback for 404 Not Found

### PR DESCRIPTION
**Pull request by baseballyama**
fix: https://github.com/sveltejs/kit/issues/2454

As a result, I implemented a dynamic fallback for 404.
Before implementing this PR, always render root `__error.svelte` in case of 404.
But in this PR, it renders `__error.svelte` according to a path.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by baseballyama** [comment]
@benmccann 

What do you think about this PR?
My understanding is that you are currently working on rebuilding the router.
So I understood that this PR is pending until that is done.
Is that correct?
If this PR is fundamentally wrong, I would like to close it to clean up the PRs.
So I hope you can give me some comments when you have time.

Related issues : https://github.com/sveltejs/kit/issues/2454 , https://github.com/sveltejs/kit/issues/2866

**Comment by benmccann** [comment]
No, I don't have other PRs that would block this. But I haven't been able to keep up with reviewing all the PRs. Rich has been diving in now that he's full-time on Svelte, so hopefully we can get caught up at some point

**Comment by gyurielf** [comment]
Do you have any news when you can review / merge this PR ?

**Comment by Rich-Harris** [comment]
Thank you, but the current behaviour is intended — closing per https://github.com/sveltejs/kit/issues/2454#issuecomment-1004051345

**Pull request closed without merging**
