### PR TITLE
[fix] Minor change to rollup config to prevent duplication - issue #3428

### PR DESCRIPTION
**Pull request by JEbertPrime**
Externalized a dependency to reduce code duplication in `dist/chunks/index.js`

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by JEbertPrime** [comment]
Windows test failed bc path matching didn't account for differences in paths between OSs. Otherwise tests pass, although some skip. At least locally (ubuntu 20.04) it seems a similar amount skip as on main branch

**Comment by JEbertPrime** [comment]
Windows test `url-supplied anchor is ignored with onMount() scrolling on navigation to page ` fails. Unsure about why, but it appears(?) that this test fails regularly. 
Some thoughts about this solution:
- It muddies up the rollup config, which probably won't make maintenance easier
- My solution works but is kinda gross. Having a regex match in the config is probably less than ideal
- There is probably a reason why there aren't any imports between dist and assets folders. FWIW this import (from `src/core/dev/plugin.js`) seems to be the only one that references a module in the `runtime` folder (as evidenced by `grep -r '^import.*runtime'`) so this probably doesn't need to be a generalizable solution

**Comment by Rich-Harris** [comment]
Thank you. I changed the implementation a bit to make it clearer that the built version of the dev plugin is importing from an external file — this should hopefully make it a bit easier to diagnose if we end up moving files around

**Comment by benmccann** [comment]
What's the reason for externalizing this file vs removing the assets server bundle below? (the answer might be good to add as a code comment in the rollup config)

```
	{
		input: 'src/runtime/server/index.js',
		output: {
			format: 'esm',
			file: 'assets/server/index.js'
		},
		plugins: [
			resolve({
				extensions: ['.mjs', '.js', '.ts']
			})
		]
	},
```

**Comment by benmccann** [comment]
I'm also slightly confused what `${runtime}` is and why we don't use it here, but do use it elsewhere. E.g. I see:
```
node_modules/@sveltejs/kit/dist/chunks/index3.js:import { set_prerendering } from '${runtime}/env.js';
```

**Comment by Rich-Harris** [comment]
Good point, we can use the existing conditional import mechanism. Updated the PR.

> What's the reason for externalizing this file vs removing the assets server bundle below?

`assets` contains code that apps import, such as code for SSR. If we removed it, apps wouldn't work any more, you would only be able to `svelte-kit dev`

**Review by benmccann — APPROVED** [review]
awesome! thanks @JEbertPrime and @Rich-Harris for the help on this!

**Pull request merged**
