### PR TITLE
Remove pnpm lockfile

### PR DESCRIPTION
**Pull request by GrygrFlzr**
Forces CI to test against the latest versions of our dependencies.

### CODE REVIEW

**Comment by benmccann** [comment]
This seems like it could cause a lot of confusion. People could have tests that are passing then suddenly start failing on the CI without explanation and it's because someone introduced a new version of a library. The point of the lockfile is so that we have control over when new versions of dependencies are used in development and tests to avoid those sorts of issues

**Comment by pngwn** [comment]
Yeah. I don’t know what this is solving specifically but removing the lock file is not the solution. 

Even if it is does address some limitation we lose everything else the lock file brings, for all of our other dependencies, which isn’t something we want to do.

**Comment by Rich-Harris** [comment]
maybe we use dependabot?

**Comment by pngwn** [comment]
I'm not sure if dependabot works with `pnpm` we had some issues at work and are using [renovate](https://github.com/renovatebot/renovate) instead. 

I'm not sure if it will detect when those symlinked dependencies have changed (the version is `workspace:*`), but running `pnpm i --lockfile-only` should always update the lock file to reflect the latest kit version. We could set up a cron workflow for this if needed.

**Comment by Conduitry** [comment]
Luke's suggestion was to pin devdeps to particular versions in package.json (and to have no lock file). I think dependabot noise would be a bit oppressive though.

**Comment by benmccann** [comment]
I agree dependabot is noisy. Personally I'm not really sure what problem is being solved here and am perfectly fine with the status quo

**Pull request closed without merging**
