### PR TITLE
[fix] prevent unused types warning

### LINKED ISSUE #6290: 'PageLoad is declared but its value is never read' when running svelte-check
### Describe the bug

When running `svelte-check` against a new project with a `+page.ts` that uses the `PageLoad` type, the `PageLoad` type is not used in the generated `proxy+page.ts` in the `.svelte-kit` directory. This causes the hint `'PageLoad' is declared but its value is never read` to be thrown.

### Reproduction

Create a new Svelte Kit app:

```
npm create svelte@latest my-app

Need to install the following packages:
  create-svelte@latest
Ok to proceed? (y) y

create-svelte version 2.0.0-next.161

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

Problems? Open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › SvelteKit demo app
✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
✔ Add ESLint for code linting? Yes
✔ Add Prettier for code formatting? Yes
✔ Add Playwright for browser testing? Yes
```

Install dependencies:

```sh
cd my-app
npm i
```

Add the following code to the end of `src/routes/about/+page.ts`:

```ts
import type { PageLoad } from './$types';

export const load: PageLoad = () => {
  console.log('loading about page');
  return {};
};
```

Run Svelte Check:

```
npm run check
```

### Logs

```shell
npm run check

> my-app@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: /Users/ccamargo/Projects/my-app
Getting Svelte diagnostics...

/Users/ccamargo/Projects/my-app/.svelte-kit/types/src/routes/about/proxy+page.ts:15:1
Hint: 'PageLoad' is declared but its value is never read. 

import type { PageLoad } from './$types';
```

### System Info

```shell
System:
  OS: macOS 11.6.8
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 275.84 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.14.2 - /usr/local/opt/node@16/bin/node
  Yarn: 1.22.17 - /usr/local/bin/yarn
  npm: 8.5.0 - /usr/local/opt/node@16/bin/npm
Browsers:
  Chrome: 104.0.5112.101
  Edge: 104.0.1293.63
  Firefox: 101.0.1
  Safari: 15.6
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.66 
  @sveltejs/kit: next => 1.0.0-next.440 
  svelte: ^3.46.0 => 3.49.0 
  vite: ^3.0.8 => 3.0.9
```

### Severity

annoyance

### Additional Information

Here is the resulting section of the `proxy+page.ts` file in `.svelte-kit`:

```ts
import type { PageLoad } from './$types';

export const load = () => {
  console.log('loading about page');
  return {};
};
```

Notice `PageLoad` is imported but not used.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #6290

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dummdidumm** [comment]
Just realized it's also benefitial to add a ts-nocheck comment at the top of all of these, so in case there are type errors they don't show up twice

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
hahaha this is an incredible solution — i was thinking about walking the AST to see if the `import type` declaration was unused so we could remove it altogether. real 'the russians used a pencil' energy

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
rescinding my approval, but only so i don't accidentally merge it before the no-check stuff gets added

**Comment by benmccann** [comment]
This really does feel like we need type tests :smile:  I don't know that we need to hold this up for tests since there's so much on our plates right now, but it might be nice to do post-summit

**Comment by dummdidumm** [comment]
I agree we need type tests, but this one isn't really related to that. It's a hidden file generated from the user's file, and there are already tests for it.

**Review by Rich-Harris — APPROVED** [review]

**Comment by benmccann** [comment]
Ah, I missed that there's a test because it was in the `src` die and I'm so used to all our tests being integration tests. Thanks for correcting me!

**Pull request merged**
