### PR TITLE
[fix] render error page without root layout if that failed to load

### LINKED ISSUE #3068: Thrown exceptions from __layout.svelte load result in plain text error responses
### Describe the bug

Throwing an exception (or returning a rejecting promise) from a `load` function should be equivalent to returning `{ status: 500, error }` (apart from the former also resulting in a call to the `handleError` hook). However, currently, it results in a plain text error message response from the server, which should be returned only when the `__error.svelte` component fails to render.

### Reproduction

Starting from the demo app, add this to `__layout.svelte`:

```svelte
<script context="module">
	export function load() {
		throw new Error("FOO");
	}
</script>
```

Navigate to any page.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.36 GB / 12.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Yarn: 1.22.15
    npm: 8.1.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4
    @sveltejs/kit: next => 1.0.0-next.202
    svelte: ^3.44.0 => 3.44.3
```

### Severity

serious, but I can work around it

### Additional Information

This is inconvenient because I'd like to use the `handleError` hook as the sole place for performing certain kinds of error logging, but I'd also prefer to not return a plain text error response to users. This means that currently my `__layout.svelte`'s `load` function needs to catch the error and reimplement the `handleError` handling in a different way (since it has access to `load` arguments instead of to the `request` object).

### LINKED ISSUE #4815: Returning non-200 status from `load` in `__layout.svelte` causes a `Uncaught (in Promise) Error`
### Describe the bug

Returning a non-`200` status from `load` in `__layout.svelte` in a Svelte-Kit app results in an _uncaught promise error_.

It seems to me said function is called recursively when returning a non-`200` status. If you track the number of calls and return `200` after the first call to `load` everything seems to be fine.  

### Reproduction

https://github.com/poppa/svelte-kit-uncaught-in-promise-sample

### Logs

```shell
__layout.svelte? [sm]:26 Uncaught (in promise) Error: Authentication Required
    at load (__layout.svelte? [sm]:26:14)
    at load_node (start.js:946:37)
    at Object._hydrate (start.js:1575:25)
    at async start (start.js:1676:3)
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 53.85 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.54
    Firefox: 98.0.1
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40 
    @sveltejs/kit: next => 1.0.0-next.324 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

### Additional Information

You guys are doing a great job, and Svelte and Svelte-Kit is just awesome.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #4815
Fixes #3068

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I definitely don't think we should introduce this behaviour — it's effectively non-deterministic.

With the [new layouts proposal](https://github.com/sveltejs/kit/discussions/6124), it would be straightforward to have the fallback error page render inside a blank layout (or a layout that is guaranteed not to error, because it doesn't have an accompanying `load`).

That leaves the question of what to do if the root layout _does_ error. Provided we've given app developers the tools to avoid that scenario (which #6124 does), then a plain 500 response seems perfectly acceptable during SSR. If it happens on the client, the path of least resistance might be to simply reload the page.

**Comment by dummdidumm** [comment]
How is this non-determenistic? If the root layout fails, it's not used - this is equivalent to a blank layout with the difference that the user doesn't have to create a group just to guarantee that his root layout never errors. If you talk about non-determinism on the client due to the try-catch - that could be adjusted so that the same logic as on the server applies: if we detect that the root layout errored, not use it, else use it.

**Comment by Rich-Harris** [comment]
It's non-deterministic because failures are non-deterministic. As an app author I shouldn't have to design my error page such that it will work both inside and outside the layout depending on factors outside my control

**Comment by dummdidumm** [comment]
But how likely is it that you designed your error page that way? It could only fail if it references `$page.data` in a way thinking the data from the layout is present. I argue this is less likely than being surprised by "why do I get a blank error message" followed by "ugh, I need to create an empty layout and therefore a needless group just for that?"

**Comment by Rich-Harris** [comment]
It's very unlikely, and that's the problem!

**Comment by dummdidumm** [comment]
It's unlikely that the root layout errors. It's even more unlikely that someone uses things from the root layout in their root error page. It's very likely that someone wants to show something better than blank text if the root layout fails. Therefore everyone who wants that is forced to use a `(group)` (under the new proposal) to get around that. I don't think it's good that you are forced to create a blank layout and a otherwise unnecessary `(group)` just to be safe when rendering the error page - this feels like "losing" one layout to safety.

**Comment by Rich-Harris** [comment]
Totally agree that there should be something better than blank text, but what that thing _is_ absolutely has to be predictable. There will always be cases where we need to bail completely (even if layout `load` succeeds, the error page itself could reference `{data.nonexistent.property}`; if it fails, then even `data.existent.property` would blow up), and so if a plain text response is unacceptable then _that's_ the problem we need to tackle.

One possible idea: an optional `src/error.html` that can contain things like `%sveltekit.error.message%`. If unspecified, falls back to a default error page that's slightly nicer than the one we have now. Unlike `+error.svelte`, we can make a cast-iron guarantee that this will render successfully.

**Comment by dummdidumm** [comment]
People have expressed the desire previously to have a error page break out of the complete layout stack (including the root layout). Can we satisfy both needs by introducing a special `+error@<something>.svelte` which means "this error page is rendered without any layout"? `error.html` would be just that but you couldn't reuse your Svelte components there.

**Comment by Rich-Harris** [comment]
I think it's better to use the existing primitives. My reaction to 'but then you'll need to put everything inside a `(main)` group' is 'so what?' In practice it doesn't make it any harder to navigation around the codebase — it _feels_ superfluous in the case where you're only using the blank layout for error pages, but it avoids all these problems...

* what if I want to share some CSS between my error page and the rest of the app? it's easier to do that in a root layout than to duplicate it in my error page
* what if I want the analytics code in my root layout `afterNavigate` function to keep working as the user navigates to/from/between errors?
* what if I later discover another use for my blank layout?

...and that's _before_ we try to answer the design question (what is the `<something>`?), let alone the documentation and maintenance burden that comes from creating new scenario-solving primitives. 

`error.html` is solving a different problem, and I think it's worth considering on its own merits (but probably in a separate issue).

**Pull request closed without merging**
