### PR TITLE
Vite 6

### PR DESCRIPTION
**Pull request by benmccann**
https://vite.dev/blog/announcing-vite6

### CODE REVIEW

**Comment by benmccann** [comment]
I think there's a few errors here, but the biggest seems to be that Vite 6 is treating all `.json` files as being a `tsconfig.json` and then reloading the server when such a file changes. @dominikg had a PR out for this here: https://github.com/vitejs/vite/pull/17317

**Comment by benmccann** [comment]
The changes to the esbuild plugin have been reverted so the prior issue with tsconfck is gone. We're down to two errors now:

      [chromium-dev] › client.test.js:448:2 › Invalidation › server-only load functions are re-run following forced invalidation 
      [chromium-dev] › client.test.js:461:2 › Invalidation › server-only load functions are re-run following goto with forced invalidation

**Comment by eltigerchino** [comment]
It seems that Vite is loading the same module twice: once by the +layout.server module, then again by the +page.server module. However, it should only be loaded once by +layout.server then re-used by +page.server
https://github.com/sveltejs/kit/blob/main/packages/kit/test/apps/basics/src/routes/load/invalidation/forced/state.js

**Comment by Rich-Harris** [comment]
preview: https://svelte-dev-git-preview-kit-12270-svelte.vercel.app/

_this is an automated message_

**Review by eltigerchino — APPROVED** [review]

**Review by Magkoooh — APPROVED** [review]

**Pull request merged**
