### PR TITLE
feat: allow generated tsconfig to be modified

### LINKED ISSUE #6868: extending a tsconfig in .svelte-kit/tsconfig.json
### Describe the bug

I have a monorepo which shares a base tsconfig and I want sveltekit to extend it.
However the root sveltekit tsconfig extends `.svelte-kit/tsconfig.json` and I cannot modify `.svelte-kit/tsconfig.json` to extend my  base tsconfig because it gets overridden by the auto-generation.
So from what I understand my only choice if I want to extend my base tsconfig is to lose the autogenerated one ?

### Reproduction

Create a turborepo app and create a sveltekit app inside the app folder.

### Logs

_No response_

### System Info

```shell
Linux
```

### Severity

annoyance

### Additional Information

I created this package to be able to extend multiple tsconfigs: 
https://github.com/Alexandre-Fernandez/tsconfig-multiple-extends

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #6868, closes #8237

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
I believe this won't be necessary with TypeScript 5 due out in March because if I'm remembering correctly it will allow you to extend from multiple tsconfigs. I feel like that might be the preferable solution though it would require making users wait two months.

**Comment by Rich-Harris** [comment]
Interesting. I guess it comes down to whether there are other things beyond `extends` that people might need to change (though if the answer is 'no' then maybe we should have just merged #8237 instead...)

**Comment by benmccann** [comment]
If the user has to change things I think that's fine. They can decide whether they want to upgrade and if they care about extending multiple tsconfigs then they can do that.

I think it would become more problematic if there were things in SvelteKit that needed to be changed to allow you to run TypeScript 5. As far as I can tell, thus far we're probably safe and SvelteKit should work with TS 4 or 5: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes. `npm run check` runs successfully against the demo project with TypeScript `5.0.0-dev.20230119`

**Comment by Rich-Harris** [comment]
The question is 'aside from `extends`, is there something in the generated `tsconfig.json` that someone might have a reason to change' — unrelated to TypeScript 4 vs 5

**Comment by baisong** [comment]
Clarifying question, is this related to this typescript note from the [(experimental) `svelte-package` docs](https://kit.svelte.dev/docs/packaging)?

> Setting `"moduleResolution": "NodeNext"` in your `tsconfig.json` or `jsconfig.json` will help you with [adhering to Node's ESM algorithm].

Mentioning because I've recently been modifying the default `jsconfig.json`, `tsconfig.json` and `.svelte-kit/tsconfig.json` while troubleshooting using `svelte-package` to publish a component library npm module.

I noticed that, even when `"moduleResolution": "NodeNext"` is present in all three files, the autogenerated  `.svelte-kit/tsconfig.json` is always overwritten to `"moduleResolution": "node"`.

**Comment by Rich-Harris** [comment]
@baisong that's unrelated to this PR/issue — this is purely about the contents of `.svelte-kit/tsconfig.json`

**Comment by anthonator** [comment]
I'd be curious if this feature would solve an issue we're currently having.

When extending the `@typescript-eslint/recommended-requiring-type-checking` eslint config we get the following error.

```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/svelte.config.ts` using `parserOptions.project`: <tsconfigRootDir>/../../../../../users/tyranthosaur/projects/imable/ui/tsconfig.json
```

We've tried adding `./svelte.config.ts` to the `include` property in the project root's `tsconfig.json` but unfortunately this performs an override instead of a merge of the `include` from `./.svelte-kit/tsconfig.json`. We got around this issue by creating a `tsconfig.eslint.json` with an `include` property we copy/pasted from `./.svelte-kit/tsconfig.json`. Definitely not ideal.

It seems like this feature would allow people to get around issues like this in a more elegant way.

**Comment by Rich-Harris** [comment]
Yep, that seems like a good enough reason! Marking this PR ready

**Pull request merged**
