### PR TITLE
merge `resolve` options when using `sequence`

### LINKED ISSUE #4051: Consider how to pass options between handlers in sequence
### Describe the bug

When using the `sequence` helper to chain multiple handle functions, `transformPage` is only actually run in the last one. Not sure if it was intended or not, but it would be nice if we could use `transformPage` in all handles, regardless of order.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-wg5zme?file=src%2Fhooks.js&terminal=dev

You can see in the reproduction that the html `lang` attribute is not changed. If we swap the two handle functions so that the one that uses `transformPage` comes last, the html is changed.

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 19.88 GB / 39.76 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-vercel: 1.0.0-next.43 => 1.0.0-next.43
    @sveltejs/kit: ^1.0.0-next.278 => 1.0.0-next.278
    svelte: ^3.46.4 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Closes #4051.

After this change, a `transformPageChunk` option passed to the first `handle` in a sequence will be respected by later calls to `resolve`

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by benmccann** [comment]
are there docs that should be updated or added to?

**Comment by Rich-Harris** [comment]
had a crack at that in https://github.com/sveltejs/kit/pull/6401/commits/3862c84e91c6a0fc54f6bfe1bfbaa7703336e7fc

**Comment by benmccann** [comment]
How about https://kit.svelte.dev/docs/modules#sveltejs-kit-hooks ? I was guessing it would need to be updated

**Review by dummdidumm — COMMENTED** [review]
It feels weird to me that `transformPageChunk` is not called in order (last is first instead of last). Is there a reason to do it like this?

**Comment by Rich-Harris** [comment]
Ah, dangit — I thought adding the description to the source code would update the docs, forgot I needed to update `ambient.d.ts` instead. Would be great if the types came directly from the source code and we didn't need to `declare module` for `@sveltejs/kit/*`, not sure what it would look like to set that up.

> It feels weird to me that `transformPageChunk` is not called in order (last is first instead of last). Is there a reason to do it like this?

It's analogous to calling `add_a(add_b(add_c('x')))` — the result is `xcba` not `xabc`

**Comment by dummdidumm** [comment]
> It's analogous to calling `add_a(add_b(add_c('x')))` — the result is `xcba` not `xabc`

Yes, but because it's an array I read this left-to-right/top-to-bottom, not the other way around. Is there a situation where switching this behavior is strange/wrong?
I would at least make it more clear in the JSDoc that the last one runs first.

**Comment by Rich-Harris** [comment]
Is c7081b7950f5f2df6bd25bc822b48baff4583718 not clear enough? I'm not sure what more we can do.

> Is there a situation where switching this behavior is strange/wrong?

I mean... yeah! You'd literally be changing the semantics to `xabc`. I think it would be really weird if the `transformPageChunk` that's applied directly to the response coming from SvelteKit ran _after_ more distant transform functions. Think of it like this:

```js
// src/hooks.js
async function increment({ event, resolve }) {
  const response = await resolve(event, {
    transformPageChunk: ({ html }) => {
      return html.replace(/number: (\d+)/g, (_match, n) => `number: ${+n + 1}`);
    }
  });

  const number = response.headers.get('x-number');
  response.headers.set('x-number', String(+number + 1));

  return response;
}

async function double({ event, resolve }) {
  const response = await resolve(event, {
    transformPageChunk: ({ html }) => {
      return html.replace(/number: (\d+)/g, (_match, n) => `number: ${+n * 2}`);
    }
  });

  const number = response.headers.get('x-number');
  response.headers.set('x-number', String(+number * 2));

  return response;
}

export const handle = sequence(increment, double);
```

```js
// src/routes/+page.js
export function load({ setHeaders }) {
  const number = 100;

  setHeaders({ 'x-number': String(number) });

  return { number };
}
```

```svelte
<!-- src/routes/+page.svelte -->
<script>
  export let data;
</script>

<h1>number: {data.number}</h1>
```

The way it's currently implemented, `<h1>count: 100</h1>` would be transformed to `<h1>count: 201</h1>`, and `x-count` would be transformed from `100` to `201`, because `double` is applied to the response from SvelteKit followed by `increment`. 

If we reversed the order in which `transformPageChunk` was applied to make it `xabc` instead of `xcba`, you'd be left with an incorrect result — the header would say `201` but the HTML would say `202`. 

Unless, that is, we reversed the order altogether and did this...

```js
const handle = sequence(
  function a({ event, resolve }) {
    console.log('i am called last');
    return resolve(event); // calls SvelteKit
  },
  function b({ event, resolve }) {
    console.log('i am called in the middle');
    return resolve(event); // calls 'a'
  },
  function c({ event, resolve }) {
    console.log('i am called first');
    return resolve(event); // calls 'b'
  }
);
```

...but that seems deeply unintuitive.

**Review by dummdidumm — APPROVED** [review]
I see - yes this makes sense that way then. Thanks!

**Pull request merged**
