### PR TITLE
Upgrade to Vite 3.2

### PR DESCRIPTION
**Pull request by benmccann**
I wasn't sure if I should include a changeset and didn't for now. This mostly affects tests. `create-svelte` does use a newer version, but you'd have already gotten the latest upon using `npm install` previously, so I'm not sure there's really a user-visible change here

### CODE REVIEW

**Comment by Conduitry** [comment]
Does 3.2 provide any new features we're going to want to make use of? Before we hit SvelteKit 1.0 is the time to be doing any bumping of peerdeps.

**Comment by benmccann** [comment]
There's not much in 3.2 that affects us. Only thing I see in the changelog is https://github.com/vitejs/vite/pull/9970, which is a bug fix for https://github.com/sveltejs/kit/issues/1042

**Comment by dominikg** [comment]
just triggered a rerun of tests on https://github.com/sveltejs/kit/pull/7355  that should go in first otherwise it gets breaking changes from this here. ofc. we can also just redo it after, but would rather not

**Comment by benmccann** [comment]
We can't merge this anyway. `lint` is failing because of https://github.com/vitejs/vite/issues/10656

**Comment by dominikg** [comment]
someone mentioned adding types/picomatch to devDependencies as a workaround. We can either do that or wait until fixed in vite. Also checking if we can enable out lint in ecosystem-ci to catch these earlier.

**Comment by dominikg** [comment]
fix has already been merged in vite, so better to wait here and bump to 3.2.1

**Comment by Rich-Harris** [comment]
i bumped esbuild across the board so that we don't end up with two versions in the lockfile

**Comment by benmccann** [comment]
Sounds good

**Review by Rich-Harris — APPROVED** [review]

**Pull request merged**
