### PR TITLE
fix: adapter-cloudflare-workers prerendering bug [w/ reproduction]

### PR DESCRIPTION
**Pull request by f5io**
Hi there!

I noticed a slight discrepancy between `adapter-cloudflare` and `adapter-cloudflare-workers`. I need the ability to pass esbuild plugins into the adapter for some issues around running **Stripe** on cloudflare. ~Hopefully this small change is OK.~

__edit__: In investigating further issues whilst attempting to run `miniflare` against a `sveltekit build` output, I discovered that there is an error in the way
prerendered files are resolved from the asset KV.

- [Reproduction Repo](https://github.com/f5io/cloudflare-prerender-bug)
- [Live Example](https://cloudflare-prerender-bug.trustshare.workers.dev/)

__I am unable to complete a `test` run due to an error in `adapter-netlify`. I am also unable to complete a `check` due to an error in `packages/kit/test/apps/amp`.__

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by f5io** [comment]
there also seems to be an issue with the resolution of prerendered pages for the `cloudflare-workers` adapter. it seems the `getAssetFromKV`'s default `mapRequestToAsset` function doesnt quite cover the use-case properly.

i do have it working with some slight change to the manifest generation and by passing in a custom `mapRequestToAsset` function to `getAssetFromKV` however it is not yet part of this PR. happy to include it if needs be.

**Comment by dominikg** [comment]
fyi, there are more pending changes to adapter-cloudflare-workers. https://github.com/sveltejs/kit/pull/4276  there has been some discussion about kvAssetHandler in that PR too.

**Comment by f5io** [comment]
thanks for pointing me in the direction of the existing work @dominikg. in doing a bit more research, ive found that the current release of the adapter simply does not work correctly for prerendered pages. is there any chance this could be seen as a hotfix that could be released rather than waiting on the migration to Module Workers?

**Comment by Rich-Harris** [comment]
Closing in favour of #4626, which brings this up to date following #4276

**Pull request closed without merging**
