### PR TITLE
Include body and method in page

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/sveltejs/kit/issues/478

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I feel like I don't quite understand the ramifications of this. It feels a bit weird that the default behaviour if you POST to a page will be different than if you GET it, unless the `load` function has explicit handling for non-GET methods. What concrete use cases are we trying to address here? Right now my preference would be for page requests to 501 if `method !== 'GET'`.

(Also, `method` and `body` feel like properties of _events_ rather than _state_, unlike the other properties of the `page` store, which makes more sense in the context of an endpoint but feels out of place in the context of a page. I realise that's somewhat nebulous but it sets off my spidey senses.)

**Comment by benmccann** [comment]
This was to allow usage at Apple. You can see a description of their admittedly strange requirements here: https://discord.com/channels/457912077277855764/571775594002513921/818912804928094261

I'm not sure I have much of a preference as to whether `POST` returns 501 or the same content as `GET` does by default. If you can still make `POST` calls via an adapter without having them error then the Apple use case should work either way

To me `method` and `body` are part of an HTTP request and it seems reasonable that you should be able to get the HTTP request in a page

**Comment by Conduitry** [comment]
How's the Apple use case deal with client side nav? Rich's comment about the POST body not being part of the state made me wonder about this. Or do they just have everything server rendered?

**Comment by Rich-Harris** [comment]
It does feel a bit like scenario solving. Is Apple's use case something that could be handled by an adapter? For example one that created a server that responded to POST requests by putting the `body` off to one side and then simulating a GET request using the API exposed to adapters by `app.js`? That feels better to me than adding an impedance mismatch; the whole point of adapters is to be able to accommodate weird stuff

**Comment by benmccann** [comment]
When you have `body` off to the side how do you get it to the app? I think we'd need to provide some way to pass custom props to the page or something

**Comment by Rich-Harris** [comment]
as a query parameter? `?payload=[uuid]` or something? haven't totally thought about how the page retrieves the data associated with the payload ID but it feels possible

**Comment by Conduitry** [comment]
@benmccann Do you know how Apple handles subsequent SPA navigation around the app? Or is there no SPA navigation, and everything is a new page load? If the POST body is in the `$page` store (which updates when you navigate around the app), when should the initial POST body stop being in the `$page` store?

**Comment by benmccann** [comment]
I think they could just pass the actual payload in `?payload=` instead of just a `uuid`. Maybe we suggest that for now and see how it works to see if something else is necessary

I'm not sure about the client-side nav question

**Pull request closed without merging**
