### PR TITLE
prerender external links

### PR DESCRIPTION
**Pull request by Rich-Harris**
In #1679 we stopped crawling links with `rel="external"` during prerendering. `rel="external"` is often used to force a full page navigation (instead of a client-side navigation), and in those cases is orthogonal to the question of whether something should be prerendered (see e.g. #3331).

It seems like the simplest thing to do would simply be to follow those links, but @v1ack perhaps you can elaborate on the motivation for #1679?

The alternative would be to introduce a new construct for disabling client-side navigation on a link (i.e. a new `sveltekit:blah` attribute) but it would be better to avoid that unless we really need it.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by v1ack** [comment]
External needs when another page on the same host handled by another service. 

For example, my case is 
- main site on GitHub pages (v1ack.github.io) running on svelte kit 
- docs site for lib (https://v1ack.github.io/svelte-virtual-scroll-list/) running from another repository 

If I place link to lib site on main site without #1679 - crawler fails with 404.

Maybe the logic of crawler can be changed to something like this: 
- if we faced to `external` - try to crawl 
- if `external` page doesn't exist - make a warning (not error) and continue crawling

**Comment by Rich-Harris** [comment]
Yeah, I think I'm inclined to say that this can be handled via the `prerender.onError` option:

```js
// svelte.config.js
export default {
  kit: {
    prerender: {
      onError: ({ status, path }) => {
        if (path.startsWith('/svelte-virtual-scroll-list')) return;
        throw new Error(`${status} ${path}`);
      }
    }
  }
};
```

**Comment by v1ack** [comment]
Ok, it looks good 
But I think it better to be mentioned in docs, near `external`option, maybe as a link to FAQ

**Comment by Rich-Harris** [comment]
Added some docs: https://github.com/sveltejs/kit/pull/3826/commits/6a7f51b20e2a4ff3c256e312cff9b9cfabc2625a

**Comment by babichjacob** [comment]
Partially related discussion on Discord for those curious: https://discord.com/channels/457912077277855764/750401468569354431/943224194634764369

**Pull request merged**
