### PR TITLE
Allow user to define custom layoutPrefix for layout page

### PR DESCRIPTION
**Pull request by heinthanth**
This patch allow user to define custom layoutPrefix to be use as layout page. There're several users who don't like `__layout.svelte` convention. So, now, they can define `layoutPrefix: '__tmpl'` in `svelte.config.js` and can use `__tmpl.svelte` as their layout page.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by benmccann** [comment]
I'm not sure I love this idea. It makes projects using the feature far less approachable for people who are already familiar with SvelteKit. What's the reason for suggesting this?

**Comment by heinthanth** [comment]
Nothing special reason behind this pull request. 
Being able to customize is a must-have feature of a framework.
But some people ( including me ) don't like the default naming convention.

So, I thought of two options:
1. the first one is to create a patch file and apply it every time `npm install`.
2. the second one is to create a pull request so that everyone can take advantage of it.

I even hacked the kit to exclude `.svelte` from `[name]-[hash].js` client side output to make svelte detection harder.

**Comment by Conduitry** [comment]
> Being able to customize is a must-have feature of a framework.

Being able to rename arbitrary features is definitely not a must-have feature of a framework.

**Comment by Mlocik97** [comment]
sry, I'm against merging this. As it was already said, it would just add chaos for new developers that would try to contribute to existing projects that use it's own name convention.

**Comment by Conduitry** [comment]
The whole reason for using two-underscore prefixes for `__layout` and `__error` and preventing users from having other files with this prefix is so that there's no chance of future new `__` files SvelteKit might want to add colliding with other files users might have in their apps. Without this, SvelteKit adding any `__foo.js` with a special meaning would be a breaking change if people were previously allowed to have `__foo.js` with no special meaning.

This PR brings us right back into that, by letting people introduce collisions, which we don't want.

There have been discussions in other issues about renaming `__layout`, which may well still happen. We're going to be adding middleware for endpoints sometime before 1.0, and that may end up being something like `__middleware.js`. `__layout` might end up just being for things that truly are related to the visual layout. This is all still up in the air.

There's going to be an enforced convention, and it's not settled on yet. We'll endeavor to make these good names, but having them be configurable is not on the table. If you really hate the name for whatever reason and you don't care about the other people who might be reading your code, you're welcome to fork SvelteKit.

**Pull request closed without merging**
