### PR TITLE
Removed getStaticDirectory() 

### PR DESCRIPTION
**Pull request by mjh316**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

Removes getStaticDirectory() because of no more usage, as stated in #7800.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by mjh316** [comment]
It seems [svelte-adapter-firebase](https://github.com/jthegedus/svelte-adapter-firebase) has [one usage](https://github.com/jthegedus/svelte-adapter-firebase/blob/main/src/index.js).
Other than that, all the adapters on https://sveltesociety.dev/components#adapters do not use it.

**Comment by dummdidumm** [comment]
Thank you! We should ask them for what exactly they need it and if they can use something else to achieve what they want before merging this.

**Comment by benmccann** [comment]
@jthegedus it would be interesting to get your input on this PR. thanks!

**Comment by jthegedus** [comment]
We are using this in the Firebase adapter to resolve https://github.com/sveltejs/kit/issues/587 in our own way, but I believe we can work around it regardless. I need to do a big update/rewrite of the adapter now a lot of things have changed in Firebase and Kit.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!

**Comment by benmccann** [comment]
@jthegedus I was just reading your comment (https://github.com/sveltejs/kit/issues/587#issuecomment-831585946) on that issue to make sure we didn't cause you any trouble by merging this. What I would recommend is copying the assets from the output directory. The output directory will contain both the generated application files and assets from the `static` directory which should probably all be served by the CDN as they'll all static assets. Let me know if that would work or if there's anything I can do otherwise to help you get things running on the latest version of SvelteKit

**Pull request merged**
